from collections.abc import Sequence
from dataclasses import dataclass
from pathlib import Path

from foundation_probes.graph import SYNTHETIC_GRAPH, GraphRoute


@dataclass(frozen=True, slots=True)
class GeneratedCandidate:
    runtime: str
    stub: str | None


def _route(graph: Sequence[GraphRoute], name: str) -> GraphRoute:
    return next(route for route in graph if route.name == name)


def generate_runtime(graph: Sequence[GraphRoute] = SYNTHETIC_GRAPH) -> str:
    home = _route(graph, "home")
    user = _route(graph, "user")
    edit_segment = dict(user.children)["edit"]
    return f'''# Code generated by the foundation probe; DO NOT EDIT.
from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class UserNode:
    user_id: int

    @property
    def path(self) -> str:
        return f"{user.path.replace("{user_id:int}", "{self.user_id}")}"

    @property
    def edit(self) -> str:
        return f"{{self.path}}/{edit_segment}"


class URLs:
    @property
    def home(self) -> str:
        return "{home.path}"

    def user(self, user_id: int) -> UserNode:
        return UserNode(user_id)


urls = URLs()
'''


def generate_stub(graph: Sequence[GraphRoute] = SYNTHETIC_GRAPH) -> str:
    _route(graph, "home")
    _route(graph, "user")
    return """# Code generated by the foundation probe; DO NOT EDIT.
from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class UserNode:
    user_id: int

    @property
    def path(self) -> str: ...

    @property
    def edit(self) -> str: ...


class URLs:
    @property
    def home(self) -> str: ...

    def user(self, user_id: int) -> UserNode: ...


urls: URLs
"""


def candidate(kind: str) -> GeneratedCandidate:
    if kind == "py":
        return GeneratedCandidate(runtime=generate_runtime(), stub=None)
    if kind == "pyi":
        return GeneratedCandidate(runtime=generate_runtime(), stub=generate_stub())
    raise ValueError(f"typing-generation phase: unknown candidate {kind!r}")


def write_candidate(directory: Path, kind: str) -> None:
    generated = candidate(kind)
    directory.mkdir(parents=True, exist_ok=True)
    (directory / "generated_urls.py").write_text(generated.runtime, encoding="ascii")
    if generated.stub is not None:
        (directory / "generated_urls.pyi").write_text(generated.stub, encoding="ascii")
