# Code generated by pyganini; DO NOT EDIT.
"""Generated Pyganini asset interface."""

from __future__ import annotations

from dataclasses import dataclass as _dataclass

from pyganini._url_binding import quote_segment as _quote_segment

__all__ = ("Asset", "lookup", "manifest", "path")


@_dataclass(frozen=True, slots=True)
class Asset:
    """One fingerprinted browser-ready asset."""

    name: str
    path: str
    hash: str
    size: int


_MANIFEST: dict[str, Asset] = {
    "app.css": Asset(
        name="app.css",
        path="/assets/app.6a6f1590.css",
        hash="6a6f1590",
        size=993,
    ),
    "app.js": Asset(
        name="app.js",
        path="/assets/app.756fcb01.js",
        hash="756fcb01",
        size=34097,
    ),
    "vendor/htmx.min.js": Asset(
        name="vendor/htmx.min.js",
        path="/assets/vendor/htmx.min.28fae7bb.js",
        hash="28fae7bb",
        size=36282,
    ),
}


def _normalize_base_path(base_path: object) -> str:
    if not isinstance(base_path, str):
        raise TypeError("base_path must be str")
    if base_path in {"", "/"}:
        return ""
    if all(character == "/" for character in base_path):
        raise ValueError("base_path must not contain empty path segments")
    normalized = base_path if base_path.startswith("/") else "/" + base_path
    normalized = normalized.rstrip("/")
    segments = normalized[1:].split("/")
    if any(segment == "" for segment in segments):
        raise ValueError("base_path must not contain empty path segments")
    quoted = tuple(
        _quote_segment(f"base_path segment {index}", segment)
        for index, segment in enumerate(segments, start=1)
    )
    return "/" + "/".join(quoted)


def _validate_name(name: object) -> str:
    if not isinstance(name, str):
        raise TypeError("name must be str")
    return name


def path(name: str, *, base_path: str = "") -> str:
    """Return the mounted URL for one logical asset name."""
    logical = _validate_name(name)
    prefix = _normalize_base_path(base_path)
    asset = _MANIFEST.get(logical)
    if asset is None:
        raise KeyError(f"unknown asset: {logical}")
    return prefix + asset.path


def lookup(name: str, *, base_path: str = "") -> str | None:
    """Return a mounted asset URL or None for an unknown name."""
    logical = _validate_name(name)
    prefix = _normalize_base_path(base_path)
    asset = _MANIFEST.get(logical)
    if asset is None:
        return None
    return prefix + asset.path


def manifest() -> dict[str, Asset]:
    """Return an isolated logical-name asset manifest copy."""
    return dict(_MANIFEST)
