# Code generated by pyganini; DO NOT EDIT.
"""Generated Pyganini ASGI routing surface."""

from jinja2 import Environment as _Environment
from starlette.routing import Router as _Router

from pyganini import AdditionalPageSource as _AdditionalPageSource
from pyganini._dispatch import AdditionalPagePlan as _SourcePlan
from pyganini._dispatch import AdditionalPageRouter as _SourceRouter
from pyganini import RouteErrorHandler as _RouteErrorHandler
from pyganini import TemplateInspectionMode as _TemplateInspectionMode
from pyganini._dispatch import build_endpoint as _build_endpoint
from pyganini._dispatch import load_route as _load_route
from pyganini._dispatch import load_middleware as _load_middleware
from pyganini._dispatch import PathPriorityRoute as _Route
from pyganini._dispatch import RouteErrorRouter as _ErrorRouter
from pyganini._dispatch import prepare_environment as _prepare_environment
from pyganini._dispatch import prepare_route_error_handler as _prepare_route_error_handler
from pyganini._dispatch import prepare_template_inspection as _prepare_template_inspection
from pyganini._dispatch import select_handler as _select_handler

_template_names = ('routes/error_page.jinja', 'routes/layout.jinja', 'routes/page.jinja')
_source_template_names = ('routes/layout.jinja', 'routes/privacy/layout.jinja')
_error_rendering = (
    ('routes/error_page.jinja', 'app/routes/error_page.jinja', 1, 1, None, ('app/routes/route.py', 10, 25)),
    None,
    (('app/routes/layout.py', 1, 1, '/', ('routes/layout.jinja', 'app/routes/layout.jinja', 1, 1, None, None)),),
    ('page', 'root-error-page', '/', 'routes/error_page.jinja', 'app/routes/error_page.jinja:1:1', 'app/routes/route.py:10:25', 'app/routes/route.py:1:1', 'route_error_handler', 'none'),
    None,
    (('layout', 'root-error-page', '/', 'routes/layout.jinja', 'app/routes/layout.jinja:1:1', 'none', 'app/routes/layout.py:1:1', 'none', 'none'),),
)

_route_0 = _load_route(
    module='app.routes.route',
    source_path='app/routes/route.py',
    expected=(
        ('page', 'GET', '/', '/', ('GET', 'HEAD'), 'app.routes.handlers', 'page', 'page', 'app/routes/route.py', 8, 10, 'page.jinja', 'app/routes/route.py', None, None, None, None),
        ('fragment', 'GET', '/declared', '/declared', ('GET', 'HEAD'), 'app.routes.handlers', 'declared', 'declared', 'app/routes/route.py', 11, 16, None, 'app/routes/route.py', None, None, None, None),
    ),
    expected_creator=None,
    expected_template_root=None,
    expected_error_page_template='error_page.jinja',
    expected_error_fragment_template=None,
)

_handler_0 = _select_handler(
    _route_0,
    kind='page',
    method='GET',
    local_path='/',
)

_handler_1 = _select_handler(
    _route_0,
    kind='fragment',
    method='GET',
    local_path='/declared',
)

def create_router(
    *,
    environment: _Environment | None = None,
    error_handler: _RouteErrorHandler | None = None,
    additional_page_source: _AdditionalPageSource | None = None,
    template_inspection: _TemplateInspectionMode = _TemplateInspectionMode.OFF,
) -> _Router:
    selected_template_inspection = _prepare_template_inspection(
        template_inspection,
        source_path='app/_pyganini/asgi.py',
    )
    selected_environment = _prepare_environment(
        environment,
        template_names=(
            _template_names if additional_page_source is None
            else (*_template_names, *_source_template_names)
        ),
        source_path='app/_pyganini/asgi.py',
    )
    selected_error_handler = _prepare_route_error_handler(
        error_handler,
        template_inspection=selected_template_inspection,
        environment=selected_environment,
        rendering=_error_rendering,
        owner=('app/routes/route.py', 1, 1),
        source_path='app/_pyganini/asgi.py',
    )
    endpoint_0 = _build_endpoint(
        handlers={
            'GET': _handler_0,
        },
        evidence={
            'GET': ('page', '/', ('GET', 'HEAD'), 'app/routes/route.py', 1, 1, 'app.routes.handlers', 'page', 'page', 'app/routes/route.py', None, None, 1, 1, '/'),
        },
        embedded_expectations={
            'GET': (),
        },
        rendering={
            'GET': (('routes/page.jinja', 'app/routes/page.jinja', 1, 1, None, ('app/routes/route.py', 9, 14)), (('app/routes/layout.py', 1, 1, '/', ('routes/layout.jinja', 'app/routes/layout.jinja', 1, 1, None, None)),), ('page', 'page', '/', 'routes/page.jinja', 'app/routes/page.jinja:1:1', 'app/routes/route.py:9:14', 'app/routes/route.py:1:1', 'app.routes.handlers:page', 'none'), (('layout', 'page', '/', 'routes/layout.jinja', 'app/routes/layout.jinja:1:1', 'none', 'app/routes/layout.py:1:1', 'none', 'none'),), ()),
        },
        parameters=(),
        environment=selected_environment,
        template_inspection=selected_template_inspection,
        error_rendering=_error_rendering,
    )
    endpoint_1 = _build_endpoint(
        handlers={
            'GET': _handler_1,
        },
        evidence={
            'GET': ('fragment', '/declared', ('GET', 'HEAD'), 'app/routes/route.py', 1, 1, 'app.routes.handlers', 'declared', 'declared', 'app/routes/route.py', None, None, 1, 1, '/'),
        },
        embedded_expectations={
            'GET': (),
        },
        rendering={
            'GET': (None, (('app/routes/layout.py', 1, 1, '/', ('routes/layout.jinja', 'app/routes/layout.jinja', 1, 1, None, None)),), None, (('layout', 'page', '/', 'routes/layout.jinja', 'app/routes/layout.jinja:1:1', 'none', 'app/routes/layout.py:1:1', 'none', 'none'),), ()),
        },
        parameters=(),
        environment=selected_environment,
        template_inspection=selected_template_inspection,
        error_rendering=_error_rendering,
    )
    _generated_routes: list[_Route] = [
            _Route(
                '/',
                endpoint_0,
                methods=['GET', 'HEAD'],
                error_handler=selected_error_handler,
                error_layouts={'GET': (('app/routes/layout.py', 1, 1, '/', ('routes/layout.jinja', 'app/routes/layout.jinja', 1, 1, None, None)),)},
                error_inspection={'GET': (('page', 'matched-error-page', '/', 'routes/error_page.jinja', 'app/routes/error_page.jinja:1:1', 'app/routes/route.py:10:25', 'app/routes/route.py:1:1', 'route_error_handler', 'none'), None, (('layout', 'matched-error-page', '/', 'routes/layout.jinja', 'app/routes/layout.jinja:1:1', 'none', 'app/routes/layout.py:1:1', 'none', 'none'),))},
                error_evidence={'GET': ('page', '/', ('GET', 'HEAD'), 'app/routes/route.py', 1, 1, 'app.routes.handlers', 'page', 'page', 'app/routes/route.py', None, None, 1, 1, '/')},
                error_templates=(('routes/error_page.jinja', 'app/routes/error_page.jinja', 1, 1, None, ('app/routes/route.py', 10, 25)), None),
            ),
            _Route(
                '/declared',
                endpoint_1,
                methods=['GET', 'HEAD'],
                error_handler=selected_error_handler,
                error_layouts={'GET': (('app/routes/layout.py', 1, 1, '/', ('routes/layout.jinja', 'app/routes/layout.jinja', 1, 1, None, None)),)},
                error_inspection={'GET': (('page', 'matched-error-page', '/declared', 'routes/error_page.jinja', 'app/routes/error_page.jinja:1:1', 'app/routes/route.py:10:25', 'app/routes/route.py:1:1', 'route_error_handler', 'none'), None, (('layout', 'matched-error-page', '/', 'routes/layout.jinja', 'app/routes/layout.jinja:1:1', 'none', 'app/routes/layout.py:1:1', 'none', 'none'),))},
                error_evidence={'GET': ('fragment', '/declared', ('GET', 'HEAD'), 'app/routes/route.py', 1, 1, 'app.routes.handlers', 'declared', 'declared', 'app/routes/route.py', None, None, 1, 1, '/')},
                error_templates=(('routes/error_page.jinja', 'app/routes/error_page.jinja', 1, 1, None, ('app/routes/route.py', 10, 25)), None),
            ),
    ]
    if additional_page_source is not None:
        _source_middleware_0 = _load_middleware(
            module='app.routes.privacy.middleware',
            source_path='app/routes/privacy/middleware.py',
            route_prefix='/privacy',
            expected_entries=((26, 15),),
            binding=(26, 1),
            consumers=(),
        )
        _source_plans = (
            _SourcePlan(
                prefix='/',
                layouts=(('app/routes/layout.py', 1, 1, '/', ('routes/layout.jinja', 'app/routes/layout.jinja', 1, 1, None, None)),),
                layout_markers=(('layout', 'additional-page', '/', 'routes/layout.jinja', 'app/routes/layout.jinja:1:1', 'none', 'app/routes/layout.py:1:1', 'none', 'none'),),
                middleware=(),
                chain=(),
            ),
            _SourcePlan(
                prefix='/privacy',
                layouts=(('app/routes/layout.py', 1, 1, '/', ('routes/layout.jinja', 'app/routes/layout.jinja', 1, 1, None, None)), ('app/routes/privacy/layout.py', 1, 1, '/privacy', ('routes/privacy/layout.jinja', 'app/routes/privacy/layout.jinja', 1, 1, None, None))),
                layout_markers=(('layout', 'additional-page', '/', 'routes/layout.jinja', 'app/routes/layout.jinja:1:1', 'none', 'app/routes/layout.py:1:1', 'none', 'none'), ('layout', 'additional-page', '/privacy', 'routes/privacy/layout.jinja', 'app/routes/privacy/layout.jinja:1:1', 'none', 'app/routes/privacy/layout.py:1:1', 'none', 'none')),
                middleware=(*_source_middleware_0,),
                chain=(('app/routes/privacy/middleware.py', 26, 1, '/privacy', ((26, 15),)),),
            ),
        )
        return _SourceRouter(
            routes=_generated_routes, source=additional_page_source,
            plans=_source_plans, environment=selected_environment,
            template_inspection=selected_template_inspection,
            error_handler=selected_error_handler,
        )
    if selected_error_handler is None:
        return _Router(
            routes=_generated_routes,
            redirect_slashes=False,
        )
    return _ErrorRouter(
        routes=_generated_routes,
        redirect_slashes=False,
        error_handler=selected_error_handler,
    )


router: _Router = create_router()
