# pyright: reportPrivateUsage=false

import os
import time
from collections.abc import Callable
from pathlib import Path, PurePosixPath
from typing import Any, cast

import pytest

import pyganini._filesystem as filesystem_module
import pyganini._generation as generation_module
from pyganini._generation import (
    GeneratedArtifact,
    GenerationError,
    bootstrap_plan,
    check_generated_state,
    generate,
)
from pyganini._paths import ProjectPaths, select_project_paths

MARKER = b"pyganini-generated-directory-v1\n"
BOOTSTRAP = (
    b"# Code generated by pyganini; DO NOT EDIT.\n"
    b'"""Generated Pyganini application package."""\n'
)


def _paths(application: Path) -> ProjectPaths:
    return select_project_paths(explicit=application, start=application)


def _snapshot(root: Path) -> tuple[tuple[str, str, bytes | None, int], ...]:
    records: list[tuple[str, str, bytes | None, int]] = []
    for path in sorted(root.rglob("*")):
        relative = path.relative_to(root).as_posix()
        if path.is_symlink():
            records.append(
                (relative, "link", os.readlink(path).encode(), path.lstat().st_mtime_ns)
            )
        elif path.is_dir():
            records.append((relative, "directory", None, path.stat().st_mtime_ns))
        else:
            records.append(
                (relative, "file", path.read_bytes(), path.stat().st_mtime_ns)
            )
    return tuple(records)


def test_first_generation_is_exact_and_idempotent(
    tmp_path: Path, make_app: Callable[..., Path]
) -> None:
    application = make_app(tmp_path / "application")
    paths = _paths(application)

    first = generate(paths, bootstrap_plan())
    assert [path.as_posix() for path in first.written] == [
        "app/_pyganini/.pyganini-root",
        "app/_pyganini/__init__.py",
    ]
    assert not first.unchanged
    assert not first.removed
    assert (paths.generated / ".pyganini-root").read_bytes() == MARKER
    assert (paths.generated / "__init__.py").read_bytes() == BOOTSTRAP

    bootstrap = paths.generated / "__init__.py"
    before = bootstrap.stat().st_mtime_ns
    time.sleep(0.002)
    second = generate(paths, bootstrap_plan())
    assert not second.written
    assert [path.as_posix() for path in second.unchanged] == [
        "app/_pyganini/.pyganini-root",
        "app/_pyganini/__init__.py",
    ]
    assert bootstrap.stat().st_mtime_ns == before
    assert not check_generated_state(paths, bootstrap_plan())


def test_check_reports_all_reachable_differences_without_writing(
    tmp_path: Path, make_app: Callable[..., Path]
) -> None:
    application = make_app(tmp_path / "application")
    paths = _paths(application)
    generate(paths, bootstrap_plan())
    (paths.generated / "__init__.py").write_text("stale\n", encoding="ascii")
    (paths.generated / "obsolete.txt").write_text("old\n", encoding="ascii")
    before = _snapshot(application)

    differences = check_generated_state(paths, bootstrap_plan())
    assert [difference.path.as_posix() for difference in differences] == [
        "app/_pyganini/__init__.py",
        "app/_pyganini/obsolete.txt",
    ]
    assert [difference.code for difference in differences] == [
        "PYGANINI005",
        "PYGANINI005",
    ]
    assert _snapshot(application) == before


def test_check_of_empty_generated_root_reports_sorted_missing_files(
    tmp_path: Path, make_app: Callable[..., Path]
) -> None:
    application = make_app(tmp_path / "application")
    paths = _paths(application)
    paths.generated.mkdir()
    before = _snapshot(application)
    differences = check_generated_state(paths, bootstrap_plan())
    assert [difference.path.as_posix() for difference in differences] == [
        "app/_pyganini/.pyganini-root",
        "app/_pyganini/__init__.py",
    ]
    assert _snapshot(application) == before


def test_obsolete_cleanup_is_leaf_first_and_preserves_application_source(
    tmp_path: Path, make_app: Callable[..., Path]
) -> None:
    application = make_app(tmp_path / "application")
    paths = _paths(application)
    generate(paths, bootstrap_plan())
    obsolete = paths.generated / "old" / "nested"
    obsolete.mkdir(parents=True)
    (obsolete / "old.py").write_text("old\n", encoding="ascii")
    source = paths.routes / "keep.py"
    source.write_text("keep\n", encoding="ascii")

    result = generate(paths, bootstrap_plan())
    assert [path.as_posix() for path in result.removed] == [
        "app/_pyganini/old",
        "app/_pyganini/old/nested",
        "app/_pyganini/old/nested/old.py",
    ]
    assert source.read_text(encoding="ascii") == "keep\n"
    assert not (paths.generated / "old").exists()


def test_obsolete_symlink_is_removed_without_touching_target(
    tmp_path: Path, make_app: Callable[..., Path]
) -> None:
    application = make_app(tmp_path / "application")
    other_application = make_app(tmp_path / "other")
    target = other_application / "app" / "routes" / "target.py"
    target.write_text("safe\n", encoding="ascii")
    paths = _paths(application)
    generate(paths, bootstrap_plan())
    link = paths.generated / "obsolete-link"
    link.symlink_to(target)

    result = generate(paths, bootstrap_plan())
    assert result.removed == (PurePosixPath("app/_pyganini/obsolete-link"),)
    assert not link.exists()
    assert target.read_text(encoding="ascii") == "safe\n"


@pytest.mark.parametrize("kind", ["unmarked", "corrupt"])
def test_generated_ownership_conflicts_fail_closed(
    tmp_path: Path, make_app: Callable[..., Path], kind: str
) -> None:
    application = make_app(tmp_path / "application")
    paths = _paths(application)
    paths.generated.mkdir()
    if kind == "unmarked":
        (paths.generated / "mine.txt").write_text("application\n", encoding="ascii")
    else:
        (paths.generated / ".pyganini-root").write_text("wrong\n", encoding="ascii")
    before = _snapshot(application)

    differences = check_generated_state(paths, bootstrap_plan())
    assert len(differences) == 1
    assert differences[0].code == "PYGANINI006"
    assert differences[0].phase == "generated-ownership"
    assert _snapshot(application) == before

    with pytest.raises(GenerationError) as captured:
        generate(paths, bootstrap_plan())
    assert captured.value.code == "PYGANINI006"
    assert captured.value.phase == "generated-ownership"
    assert _snapshot(application) == before


@pytest.mark.parametrize(
    "artifacts",
    [
        (GeneratedArtifact(PurePosixPath("../escape.py"), BOOTSTRAP),),
        (
            GeneratedArtifact(PurePosixPath("app/_pyganini/same.py"), BOOTSTRAP),
            GeneratedArtifact(PurePosixPath("app/_pyganini/same.py"), BOOTSTRAP),
        ),
        (
            GeneratedArtifact(PurePosixPath("app/_pyganini/parent"), b"bytes"),
            GeneratedArtifact(PurePosixPath("app/_pyganini/parent/child"), b"bytes"),
        ),
        (
            GeneratedArtifact(
                PurePosixPath("app/_pyganini/not-generated.py"), b"print('no')\n"
            ),
        ),
        (
            GeneratedArtifact(
                PurePosixPath("app/_pyganini/content.txt"), cast(bytes, "text")
            ),
        ),
        (GeneratedArtifact(PurePosixPath("app/_pyganini/.pyganini-root"), b"wrong\n"),),
    ],
)
def test_invalid_plan_fails_before_mutation(
    tmp_path: Path,
    make_app: Callable[..., Path],
    artifacts: tuple[GeneratedArtifact, ...],
) -> None:
    application = make_app(tmp_path / "application")
    paths = _paths(application)
    before = _snapshot(application)
    with pytest.raises(GenerationError) as captured:
        generate(paths, artifacts)
    assert captured.value.code == "PYGANINI007"
    assert captured.value.phase == "generation-plan"
    assert _snapshot(application) == before


def test_case_normalized_collision_is_rejected(
    tmp_path: Path,
    make_app: Callable[..., Path],
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    application = make_app(tmp_path / "application")
    paths = _paths(application)

    def case_insensitive(_: ProjectPaths) -> bool:
        return True

    monkeypatch.setattr(generation_module, "_case_insensitive", case_insensitive)
    plan = (
        GeneratedArtifact(PurePosixPath("app/_pyganini/A.txt"), b"a"),
        GeneratedArtifact(PurePosixPath("app/_pyganini/a.txt"), b"b"),
    )
    with pytest.raises(GenerationError, match="collides") as captured:
        generate(paths, plan)
    assert captured.value.code == "PYGANINI007"
    assert not paths.generated.exists()


def test_case_normalized_parent_file_collision_is_rejected(
    tmp_path: Path,
    make_app: Callable[..., Path],
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    application = make_app(tmp_path / "application")
    paths = _paths(application)

    def case_insensitive(_: ProjectPaths) -> bool:
        return True

    monkeypatch.setattr(generation_module, "_case_insensitive", case_insensitive)
    plan = (
        GeneratedArtifact(PurePosixPath("app/_pyganini/Parent"), b"parent\n"),
        GeneratedArtifact(PurePosixPath("app/_pyganini/parent/child"), b"child\n"),
    )
    with pytest.raises(GenerationError, match="parent conflicts") as captured:
        generate(paths, plan)
    assert captured.value.code == "PYGANINI007"
    assert not paths.generated.exists()


@pytest.mark.parametrize(
    "name",
    [
        "redirect\\escape.txt",
        "C:escape.txt",
        "CON.txt",
        "trailing. ",
        "question?.txt",
        "unicode-\N{SNOWMAN}.txt",
    ],
)
def test_nonportable_plan_path_fails_before_mutation(
    tmp_path: Path,
    make_app: Callable[..., Path],
    name: str,
) -> None:
    application = make_app(tmp_path / "application")
    paths = _paths(application)
    plan = (GeneratedArtifact(PurePosixPath("app/_pyganini") / name, b"safe\n"),)
    with pytest.raises(GenerationError) as captured:
        generate(paths, plan)
    assert captured.value.code == "PYGANINI007"
    assert not paths.generated.exists()


def test_nested_artifact_uses_the_same_writer_lifecycle(
    tmp_path: Path, make_app: Callable[..., Path]
) -> None:
    application = make_app(tmp_path / "application")
    paths = _paths(application)
    plan = (
        GeneratedArtifact(
            PurePosixPath("app/_pyganini/inspection/state.txt"), b"current\n"
        ),
    )
    result = generate(paths, plan)
    assert [path.as_posix() for path in result.written] == [
        "app/_pyganini/.pyganini-root",
        "app/_pyganini/inspection/state.txt",
    ]
    assert (paths.generated / "inspection" / "state.txt").read_bytes() == b"current\n"
    assert not check_generated_state(paths, plan)


def test_expected_parent_symlink_fails_before_mutation(
    tmp_path: Path, make_app: Callable[..., Path]
) -> None:
    application = make_app(tmp_path / "application")
    paths = _paths(application)
    generate(paths, bootstrap_plan())
    outside = tmp_path / "outside"
    outside.mkdir()
    parent = paths.generated / "redirect"
    parent.symlink_to(outside, target_is_directory=True)
    before = _snapshot(application)
    plan = (
        GeneratedArtifact(PurePosixPath("app/_pyganini/redirect/file.txt"), b"safe\n"),
    )
    with pytest.raises(GenerationError) as captured:
        generate(paths, plan)
    assert captured.value.code == "PYGANINI006"
    assert _snapshot(application) == before
    assert not (outside / "file.txt").exists()


def test_staging_failure_before_mutation_is_pylrd007(
    tmp_path: Path,
    make_app: Callable[..., Path],
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    application = make_app(tmp_path / "application")
    paths = _paths(application)
    generate(paths, bootstrap_plan())
    bootstrap = paths.generated / "__init__.py"
    bootstrap.write_text("stale\n", encoding="ascii")
    before = _snapshot(application)

    def fail_stage(_: object, __: PurePosixPath, ___: bytes) -> object:
        raise OSError("injected staging failure")

    monkeypatch.setattr(generation_module, "_stage", fail_stage)
    with pytest.raises(GenerationError) as captured:
        generate(paths, bootstrap_plan())
    assert captured.value.code == "PYGANINI007"
    assert _snapshot(application) == before


def test_internal_staging_failure_cleans_private_file(
    tmp_path: Path,
    make_app: Callable[..., Path],
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    application = make_app(tmp_path / "application")
    paths = _paths(application)
    generate(paths, bootstrap_plan())
    (paths.generated / "__init__.py").write_bytes(b"stale\n")

    def fail_fsync(_: int) -> None:
        raise OSError("injected fsync failure")

    monkeypatch.setattr(os, "fsync", fail_fsync)
    with pytest.raises(GenerationError) as captured:
        generate(paths, bootstrap_plan())
    assert captured.value.code == "PYGANINI007"
    assert "injected fsync failure" in captured.value.message
    assert not tuple(paths.generated.rglob("._pyganini-*"))


def test_internal_staging_cleanup_failure_preserves_primary_error(
    tmp_path: Path,
    make_app: Callable[..., Path],
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    application = make_app(tmp_path / "application")
    paths = _paths(application)
    generate(paths, bootstrap_plan())
    (paths.generated / "__init__.py").write_bytes(b"stale\n")
    original_unlink = cast(Callable[..., object], os.unlink)

    def fail_unlink(name: object, *args: object, **kwargs: object) -> object:
        if isinstance(name, str) and name.startswith("._pyganini-"):
            raise OSError("injected staging cleanup failure")
        return original_unlink(name, *args, **kwargs)

    def fail_fsync(_: int) -> None:
        raise OSError("injected fsync failure")

    monkeypatch.setattr(os, "unlink", fail_unlink)
    monkeypatch.setattr(os, "fsync", fail_fsync)
    with pytest.raises(GenerationError) as captured:
        generate(paths, bootstrap_plan())
    assert captured.value.code == "PYGANINI007"
    assert "injected fsync failure" in captured.value.message
    assert "injected staging cleanup failure" in captured.value.message
    assert tuple(paths.generated.rglob("._pyganini-*"))


def test_failure_after_initialization_reports_completed_mutations(
    tmp_path: Path,
    make_app: Callable[..., Path],
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    application = make_app(tmp_path / "application")
    paths = _paths(application)

    def fail_replace(self: object, staged: object) -> None:
        raise OSError("injected replacement failure")

    monkeypatch.setattr(
        filesystem_module._PosixGeneratedFilesystem, "replace", fail_replace
    )
    with pytest.raises(GenerationError) as captured:
        generate(paths, bootstrap_plan())
    assert captured.value.code == "PYGANINI008"
    assert captured.value.phase == "partial-generation"
    assert (
        "rerun pyganini generate followed by pyganini check" in captured.value.message
    )
    assert captured.value.details == ("completed mutation: created app/_pyganini",)


def test_root_mutation_is_reported_when_root_anchor_fails(
    tmp_path: Path,
    make_app: Callable[..., Path],
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    application = make_app(tmp_path / "application")
    paths = _paths(application)

    def fail_root_anchor(_: object) -> int:
        raise OSError("injected root anchor failure")

    monkeypatch.setattr(
        filesystem_module._PosixGeneratedFilesystem, "_open_root", fail_root_anchor
    )
    with pytest.raises(GenerationError) as captured:
        generate(paths, bootstrap_plan())
    assert captured.value.code == "PYGANINI008"
    assert captured.value.details == ("completed mutation: created app/_pyganini",)
    assert paths.generated.is_dir()


def test_parent_mutations_are_reported_when_parent_anchor_fails(
    tmp_path: Path,
    make_app: Callable[..., Path],
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    application = make_app(tmp_path / "application")
    paths = _paths(application)
    generate(paths, bootstrap_plan())
    original_open = cast(Callable[..., int], os.open)

    def fail_parent_anchor(
        path: object, flags: int, *args: object, **kwargs: object
    ) -> int:
        if path == "nested" and "dir_fd" in kwargs:
            raise OSError("injected parent anchor failure")
        return original_open(path, flags, *args, **kwargs)

    monkeypatch.setattr(os, "open", fail_parent_anchor)
    plan = (
        GeneratedArtifact(PurePosixPath("app/_pyganini/nested/file.txt"), b"file\n"),
    )
    with pytest.raises(GenerationError) as captured:
        generate(paths, plan)
    assert captured.value.code == "PYGANINI008"
    assert captured.value.details == (
        "completed mutation: created app/_pyganini/nested",
    )
    assert (paths.generated / "nested").is_dir()


def test_cleanup_failure_after_replacement_reports_partial_state(
    tmp_path: Path,
    make_app: Callable[..., Path],
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    application = make_app(tmp_path / "application")
    paths = _paths(application)
    generate(paths, bootstrap_plan())
    bootstrap = paths.generated / "__init__.py"
    bootstrap.write_text("stale\n", encoding="ascii")
    obsolete = paths.generated / "obsolete.txt"
    obsolete.write_text("old\n", encoding="ascii")

    def fail_cleanup(self: object, entry: object) -> None:
        raise OSError("injected cleanup failure")

    monkeypatch.setattr(
        filesystem_module._PosixGeneratedFilesystem, "remove", fail_cleanup
    )
    with pytest.raises(GenerationError) as captured:
        generate(paths, bootstrap_plan())
    assert captured.value.code == "PYGANINI008"
    assert captured.value.phase == "partial-generation"
    assert bootstrap.read_bytes() == BOOTSTRAP
    assert obsolete.exists()
    assert any(
        "replaced app/_pyganini/__init__.py" in item for item in captured.value.details
    )


def test_transient_bytecode_is_excluded_from_state(
    tmp_path: Path, make_app: Callable[..., Path]
) -> None:
    application = make_app(tmp_path / "application")
    paths = _paths(application)
    generate(paths, bootstrap_plan())
    cache = paths.generated / "__pycache__"
    cache.mkdir()
    (cache / "generated.pyc").write_bytes(b"cache")
    (paths.generated / "loose.pyc").write_bytes(b"cache")
    assert not check_generated_state(paths, bootstrap_plan())
    result = generate(paths, bootstrap_plan())
    assert not result.removed
    assert cache.exists()
    assert (paths.generated / "loose.pyc").exists()


def test_expected_fifo_is_reported_without_opening_content(
    tmp_path: Path, make_app: Callable[..., Path]
) -> None:
    application = make_app(tmp_path / "application")
    paths = _paths(application)
    generate(paths, bootstrap_plan())
    bootstrap = paths.generated / "__init__.py"
    bootstrap.unlink()
    os.mkfifo(bootstrap)

    differences = check_generated_state(paths, bootstrap_plan())
    assert [(item.code, item.path.as_posix()) for item in differences] == [
        ("PYGANINI006", "app/_pyganini/__init__.py")
    ]
    with pytest.raises(GenerationError) as captured:
        generate(paths, bootstrap_plan())
    assert captured.value.code == "PYGANINI006"


def test_all_files_stage_before_any_replacement(
    tmp_path: Path,
    make_app: Callable[..., Path],
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    application = make_app(tmp_path / "application")
    paths = _paths(application)
    plan = (
        GeneratedArtifact(PurePosixPath("app/_pyganini/a.txt"), b"a\n"),
        GeneratedArtifact(PurePosixPath("app/_pyganini/b.txt"), b"b\n"),
    )
    generate(paths, plan)
    (paths.generated / "a.txt").write_bytes(b"old-a\n")
    (paths.generated / "b.txt").write_bytes(b"old-b\n")
    events: list[str] = []
    original_stage = filesystem_module._PosixGeneratedFilesystem.stage
    original_replace = filesystem_module._PosixGeneratedFilesystem.replace

    def record_stage(self: Any, relative: PurePosixPath, content: bytes) -> object:
        events.append(f"stage:{relative}")
        return original_stage(self, relative, content)

    def record_replace(self: Any, staged: Any) -> None:
        events.append(f"replace:{staged.destination_name}")
        original_replace(self, staged)

    monkeypatch.setattr(
        filesystem_module._PosixGeneratedFilesystem, "stage", record_stage
    )
    monkeypatch.setattr(
        filesystem_module._PosixGeneratedFilesystem, "replace", record_replace
    )
    generate(paths, plan)
    assert events == ["stage:a.txt", "stage:b.txt", "replace:a.txt", "replace:b.txt"]


def test_initial_generation_stages_marker_before_any_replacement(
    tmp_path: Path,
    make_app: Callable[..., Path],
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    application = make_app(tmp_path / "application")
    paths = _paths(application)
    plan = (
        GeneratedArtifact(PurePosixPath("app/_pyganini/a.txt"), b"a\n"),
        GeneratedArtifact(PurePosixPath("app/_pyganini/b.txt"), b"b\n"),
    )
    events: list[str] = []
    original_stage = filesystem_module._PosixGeneratedFilesystem.stage
    original_replace = filesystem_module._PosixGeneratedFilesystem.replace

    def record_stage(self: Any, relative: PurePosixPath, content: bytes) -> object:
        events.append(f"stage:{relative}")
        return original_stage(self, relative, content)

    def record_replace(self: Any, staged: Any) -> None:
        events.append(f"replace:{staged.destination_name}")
        original_replace(self, staged)

    monkeypatch.setattr(
        filesystem_module._PosixGeneratedFilesystem, "stage", record_stage
    )
    monkeypatch.setattr(
        filesystem_module._PosixGeneratedFilesystem, "replace", record_replace
    )
    generate(paths, plan)
    assert events == [
        "stage:.pyganini-root",
        "stage:a.txt",
        "stage:b.txt",
        "replace:.pyganini-root",
        "replace:a.txt",
        "replace:b.txt",
    ]


def test_second_replacement_failure_cleans_remaining_stage_and_reports_partial(
    tmp_path: Path,
    make_app: Callable[..., Path],
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    application = make_app(tmp_path / "application")
    paths = _paths(application)
    plan = (
        GeneratedArtifact(PurePosixPath("app/_pyganini/a.txt"), b"a\n"),
        GeneratedArtifact(PurePosixPath("app/_pyganini/b.txt"), b"b\n"),
    )
    generate(paths, plan)
    (paths.generated / "a.txt").write_bytes(b"old-a\n")
    (paths.generated / "b.txt").write_bytes(b"old-b\n")
    original = filesystem_module._PosixGeneratedFilesystem.replace
    replacements = 0

    def fail_second(self: Any, staged: Any) -> None:
        nonlocal replacements
        replacements += 1
        if replacements == 2:
            raise OSError("injected second replacement failure")
        original(self, staged)

    monkeypatch.setattr(
        filesystem_module._PosixGeneratedFilesystem, "replace", fail_second
    )
    with pytest.raises(GenerationError) as captured:
        generate(paths, plan)
    assert captured.value.code == "PYGANINI008"
    assert any(
        "replaced app/_pyganini/a.txt" in item for item in captured.value.details
    )
    assert not tuple(paths.generated.rglob("._pyganini-*"))
    assert check_generated_state(paths, plan) != ()
    monkeypatch.undo()
    generate(paths, plan)
    assert not check_generated_state(paths, plan)


def test_post_replacement_scan_failure_is_partial_generation(
    tmp_path: Path,
    make_app: Callable[..., Path],
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    application = make_app(tmp_path / "application")
    paths = _paths(application)
    generate(paths, bootstrap_plan())
    (paths.generated / "__init__.py").write_bytes(b"stale\n")
    original = filesystem_module._PosixGeneratedFilesystem.entries
    calls = 0

    def fail_after_replace(self: Any) -> object:
        nonlocal calls
        calls += 1
        if calls == 2:
            raise RuntimeError("injected post-mutation scan failure")
        return original(self)

    monkeypatch.setattr(
        filesystem_module._PosixGeneratedFilesystem, "entries", fail_after_replace
    )
    with pytest.raises(GenerationError) as captured:
        generate(paths, bootstrap_plan())
    assert captured.value.code == "PYGANINI008"
    assert "replaced app/_pyganini/__init__.py" in captured.value.details[0]
