# Code generated by pyganini; DO NOT EDIT.
"""Generated Pyganini ASGI routing surface."""

from jinja2 import Environment as _Environment
from starlette.routing import Router as _Router
from typing import TYPE_CHECKING as _TYPE_CHECKING

from pyganini import KitRouteDef as _KitRouteDef
from pyganini import KitRouteMount as _KitRouteMount
from pyganini import RouteErrorHandler as _RouteErrorHandler
from pyganini import TemplateInspectionMode as _TemplateInspectionMode
from pyganini._dispatch import build_endpoint as _build_endpoint
from pyganini._dispatch import load_route as _load_route
from pyganini._dispatch import load_mount_owner as _load_mount_owner
from pyganini._dispatch import PathPriorityRoute as _Route
from pyganini._dispatch import RouteErrorRouter as _ErrorRouter
from pyganini._dispatch import prepare_environment as _prepare_environment
from pyganini._dispatch import prepare_route_error_handler as _prepare_route_error_handler
from pyganini._dispatch import prepare_template_inspection as _prepare_template_inspection
from pyganini._dispatch import select_creator as _select_creator
from pyganini._dispatch import select_handler as _select_handler

_template_names = ('mounts/reports/audit/page.jinja', 'mounts/reports/layout.jinja', 'mounts/reports/page.jinja', 'mounts/reports/table.jinja', 'routes/layout.jinja', 'routes/page.jinja')

_route_0 = _load_mount_owner(
    module='app.routes.admin.reports.route',
    source_path='app/routes/admin/reports/route.py',
    expected_creator=('app.routes.admin.reports.route', 'create_admin_reports', 'create_admin_reports', 'app/routes/admin/reports/route.py', 41, 12),
    expected_mount='reports',
    expected_routes=('/', '/audit'),
    expected_bindings=(('/', 'app/mounts/reports/route.py', '/admin/reports'), ('/audit', 'app/mounts/reports/audit/route.py', '/admin/reports/audit')),
    expected_selections=(('/', None, ()), ('/audit', None, ())),
)

_source_0 = _load_route(
    module='app.mounts.reports.audit.route',
    source_path='app/mounts/reports/audit/route.py',
    expected=(
        ('page', 'GET', '/', '/admin/reports/audit', ('GET', 'HEAD'), 'app.mounts.reports.audit.handlers', 'page', 'page', 'app/mounts/reports/audit/route.py', 5, 24, 'page.jinja', 'app/routes/admin/reports/route.py', 'reports', '/audit', None, None),
    ),
    expected_creator=None,
    expected_template_root=None,
    expected_kit=True,
)

_source_1 = _load_route(
    module='app.mounts.reports.route',
    source_path='app/mounts/reports/route.py',
    expected=(
        ('page', 'GET', '/', '/admin/reports', ('GET', 'HEAD'), 'app.mounts.reports.handlers', 'page', 'page', 'app/mounts/reports/route.py', 6, 10, 'page.jinja', 'app/routes/admin/reports/route.py', 'reports', '/', None, None),
        ('fragment', 'GET', '/table', '/admin/reports/table', ('GET', 'HEAD'), 'app.mounts.reports.handlers', 'table', 'table', 'app/mounts/reports/route.py', 8, 16, 'table.jinja', 'app/routes/admin/reports/route.py', 'reports', '/', None, None),
    ),
    expected_creator=None,
    expected_template_root=None,
    expected_nav=('Reports', None),
    expected_destinations=(),
    expected_kit=True,
)

_route_1 = _load_route(
    module='app.routes.route',
    source_path='app/routes/route.py',
    expected=(
        ('page', 'GET', '/', '/', ('GET', 'HEAD'), 'app.routes.handlers', 'page', 'page', 'app/routes/route.py', 5, 20, 'page.jinja', 'app/routes/route.py', None, None, None, None),
    ),
    expected_creator=None,
    expected_template_root=None,
)

_route_2 = _load_mount_owner(
    module='app.routes.user.reports.route',
    source_path='app/routes/user/reports/route.py',
    expected_creator=('app.routes.user.reports.route', 'create_user_reports', 'create_user_reports', 'app/routes/user/reports/route.py', 41, 12),
    expected_mount='reports',
    expected_routes=('/',),
    expected_bindings=(('/', 'app/mounts/reports/route.py', '/user/reports'),),
    expected_selections=(('/', None, ()),),
)

_source_2 = _load_route(
    module='app.mounts.reports.route',
    source_path='app/mounts/reports/route.py',
    expected=(
        ('page', 'GET', '/', '/user/reports', ('GET', 'HEAD'), 'app.mounts.reports.handlers', 'page', 'page', 'app/mounts/reports/route.py', 6, 10, 'page.jinja', 'app/routes/user/reports/route.py', 'reports', '/', None, None),
        ('fragment', 'GET', '/table', '/user/reports/table', ('GET', 'HEAD'), 'app.mounts.reports.handlers', 'table', 'table', 'app/mounts/reports/route.py', 8, 16, 'table.jinja', 'app/routes/user/reports/route.py', 'reports', '/', None, None),
    ),
    expected_creator=None,
    expected_template_root=None,
    expected_nav=('Reports', None),
    expected_destinations=(),
    expected_kit=True,
)

if _TYPE_CHECKING:
    def _check_mounted_kit[K](
        owner: _KitRouteMount[K],
        source: _KitRouteDef[K],
    ) -> None:
        ...
    # Owner/source generic type witness.
    from app.routes.admin.reports.route import Route as _owner_route_0
    from app.mounts.reports.audit.route import Route as _source_route_0
    _check_mounted_kit(_owner_route_0, _source_route_0)
    from app.routes.admin.reports.route import Route as _owner_route_0
    from app.mounts.reports.route import Route as _source_route_1
    _check_mounted_kit(_owner_route_0, _source_route_1)
    # Owner/source generic type witness.
    from app.routes.user.reports.route import Route as _owner_route_2
    from app.mounts.reports.route import Route as _source_route_2
    _check_mounted_kit(_owner_route_2, _source_route_2)

_handler_0 = _select_handler(
    _route_1,
    kind='page',
    method='GET',
    local_path='/',
)

_handler_1 = _select_handler(
    _source_1,
    kind='page',
    method='GET',
    local_path='/',
)

_creator_1 = _select_creator(
    _route_0,
)

_handler_2 = _select_handler(
    _source_1,
    kind='fragment',
    method='GET',
    local_path='/table',
)

_creator_2 = _select_creator(
    _route_0,
)

_handler_3 = _select_handler(
    _source_0,
    kind='page',
    method='GET',
    local_path='/',
)

_creator_3 = _select_creator(
    _route_0,
)

_handler_4 = _select_handler(
    _source_2,
    kind='page',
    method='GET',
    local_path='/',
)

_creator_4 = _select_creator(
    _route_2,
)

_handler_5 = _select_handler(
    _source_2,
    kind='fragment',
    method='GET',
    local_path='/table',
)

_creator_5 = _select_creator(
    _route_2,
)

def create_router(
    *,
    environment: _Environment | None = None,
    error_handler: _RouteErrorHandler | None = None,
    template_inspection: _TemplateInspectionMode = _TemplateInspectionMode.OFF,
) -> _Router:
    selected_template_inspection = _prepare_template_inspection(
        template_inspection,
        source_path='app/_pyganini/asgi.py',
    )
    selected_environment = _prepare_environment(
        environment,
        template_names=_template_names,
        source_path='app/_pyganini/asgi.py',
    )
    selected_error_handler = _prepare_route_error_handler(
        error_handler,
        template_inspection=selected_template_inspection,
        source_path='app/_pyganini/asgi.py',
    )
    endpoint_0 = _build_endpoint(
        handlers={
            'GET': _handler_0,
        },
        evidence={
            'GET': ('page', '/', ('GET', 'HEAD'), 'app/routes/route.py', 1, 1, 'app.routes.handlers', 'page', 'page', 'app/routes/route.py', None, None, 1, 1, '/'),
        },
        embedded_expectations={
            'GET': (),
        },
        rendering={
            'GET': (('routes/page.jinja', 'app/routes/page.jinja', 1, 1, None, ('app/routes/route.py', 5, 35)), (('app/routes/layout.py', 1, 1, '/', ('routes/layout.jinja', 'app/routes/layout.jinja', 1, 1, None, None)),), ('page', 'page', '/', 'routes/page.jinja', 'app/routes/page.jinja:1:1', 'app/routes/route.py:5:35', 'app/routes/route.py:1:1', 'app.routes.handlers:page', 'none'), (('layout', 'page', '/', 'routes/layout.jinja', 'app/routes/layout.jinja:1:1', 'none', 'app/routes/layout.py:1:1', 'none', 'none'),), ()),
        },
        parameters=(),
        environment=selected_environment,
        template_inspection=selected_template_inspection,
    )
    endpoint_1 = _build_endpoint(
        handlers={
            'GET': _handler_1,
        },
        creators={
            'GET': _creator_1,
        },
        navigation={'GET': (('Reports', None, '/admin/reports', True),)},
        evidence={
            'GET': ('page', '/admin/reports', ('GET', 'HEAD'), 'app/mounts/reports/route.py', 1, 1, 'app.mounts.reports.handlers', 'page', 'page', 'app/routes/admin/reports/route.py', 'reports', '/', 1, 1, '/admin/reports'),
        },
        embedded_expectations={
            'GET': (('/table', ('fragment', '/admin/reports/table', ('GET', 'HEAD'), 'app/mounts/reports/route.py', 1, 1, 'app.mounts.reports.handlers', 'table', 'table', 'app/routes/admin/reports/route.py', 'reports', '/', 1, 1, '/admin/reports'), ('mounts/reports/table.jinja', 'app/mounts/reports/table.jinja', 1, 1, None, ('app/mounts/reports/route.py', 8, 61))),),
        },
        rendering={
            'GET': (('mounts/reports/page.jinja', 'app/mounts/reports/page.jinja', 1, 1, None, ('app/mounts/reports/route.py', 7, 14)), (('app/routes/layout.py', 1, 1, '/', ('routes/layout.jinja', 'app/routes/layout.jinja', 1, 1, None, None)), ('app/mounts/reports/layout.py', 1, 1, '/', ('mounts/reports/layout.jinja', 'app/mounts/reports/layout.jinja', 1, 1, None, None))), ('page', 'page', '/admin/reports', 'mounts/reports/page.jinja', 'app/mounts/reports/page.jinja:1:1', 'app/mounts/reports/route.py:7:14', 'app/routes/admin/reports/route.py:1:1', 'app.mounts.reports.handlers:page', 'reports:/'), (('layout', 'page', '/', 'routes/layout.jinja', 'app/routes/layout.jinja:1:1', 'none', 'app/routes/layout.py:1:1', 'none', 'none'), ('layout', 'page', '/admin/reports', 'mounts/reports/layout.jinja', 'app/mounts/reports/layout.jinja:1:1', 'none', 'app/mounts/reports/layout.py:1:1', 'none', 'reports:/')), (('/table', ('fragment', 'embedded-fragment', '/admin/reports/table', 'mounts/reports/table.jinja', 'app/mounts/reports/table.jinja:1:1', 'app/mounts/reports/route.py:8:61', 'app/routes/admin/reports/route.py:1:1', 'app.mounts.reports.handlers:table', 'reports:/')),)),
        },
        parameters=(),
        environment=selected_environment,
        template_inspection=selected_template_inspection,
    )
    endpoint_2 = _build_endpoint(
        handlers={
            'GET': _handler_2,
        },
        creators={
            'GET': _creator_2,
        },
        navigation={'GET': (('Reports', None, '/admin/reports', True),)},
        evidence={
            'GET': ('fragment', '/admin/reports/table', ('GET', 'HEAD'), 'app/mounts/reports/route.py', 1, 1, 'app.mounts.reports.handlers', 'table', 'table', 'app/routes/admin/reports/route.py', 'reports', '/', 1, 1, '/admin/reports'),
        },
        embedded_expectations={
            'GET': (('/table', ('fragment', '/admin/reports/table', ('GET', 'HEAD'), 'app/mounts/reports/route.py', 1, 1, 'app.mounts.reports.handlers', 'table', 'table', 'app/routes/admin/reports/route.py', 'reports', '/', 1, 1, '/admin/reports'), ('mounts/reports/table.jinja', 'app/mounts/reports/table.jinja', 1, 1, None, ('app/mounts/reports/route.py', 8, 61))),),
        },
        rendering={
            'GET': (('mounts/reports/table.jinja', 'app/mounts/reports/table.jinja', 1, 1, None, ('app/mounts/reports/route.py', 8, 61)), (('app/routes/layout.py', 1, 1, '/', ('routes/layout.jinja', 'app/routes/layout.jinja', 1, 1, None, None)), ('app/mounts/reports/layout.py', 1, 1, '/', ('mounts/reports/layout.jinja', 'app/mounts/reports/layout.jinja', 1, 1, None, None))), ('fragment', 'fragment', '/admin/reports/table', 'mounts/reports/table.jinja', 'app/mounts/reports/table.jinja:1:1', 'app/mounts/reports/route.py:8:61', 'app/routes/admin/reports/route.py:1:1', 'app.mounts.reports.handlers:table', 'reports:/'), (('layout', 'page', '/', 'routes/layout.jinja', 'app/routes/layout.jinja:1:1', 'none', 'app/routes/layout.py:1:1', 'none', 'none'), ('layout', 'page', '/admin/reports', 'mounts/reports/layout.jinja', 'app/mounts/reports/layout.jinja:1:1', 'none', 'app/mounts/reports/layout.py:1:1', 'none', 'reports:/')), (('/table', ('fragment', 'embedded-fragment', '/admin/reports/table', 'mounts/reports/table.jinja', 'app/mounts/reports/table.jinja:1:1', 'app/mounts/reports/route.py:8:61', 'app/routes/admin/reports/route.py:1:1', 'app.mounts.reports.handlers:table', 'reports:/')),)),
        },
        parameters=(),
        environment=selected_environment,
        template_inspection=selected_template_inspection,
    )
    endpoint_3 = _build_endpoint(
        handlers={
            'GET': _handler_3,
        },
        creators={
            'GET': _creator_3,
        },
        navigation={'GET': (('Reports', None, '/admin/reports', False),)},
        evidence={
            'GET': ('page', '/admin/reports/audit', ('GET', 'HEAD'), 'app/mounts/reports/audit/route.py', 1, 1, 'app.mounts.reports.audit.handlers', 'page', 'page', 'app/routes/admin/reports/route.py', 'reports', '/audit', 1, 1, '/admin/reports'),
        },
        embedded_expectations={
            'GET': (),
        },
        rendering={
            'GET': (('mounts/reports/audit/page.jinja', 'app/mounts/reports/audit/page.jinja', 1, 1, None, ('app/mounts/reports/audit/route.py', 5, 39)), (('app/routes/layout.py', 1, 1, '/', ('routes/layout.jinja', 'app/routes/layout.jinja', 1, 1, None, None)), ('app/mounts/reports/layout.py', 1, 1, '/', ('mounts/reports/layout.jinja', 'app/mounts/reports/layout.jinja', 1, 1, None, None))), ('page', 'page', '/admin/reports/audit', 'mounts/reports/audit/page.jinja', 'app/mounts/reports/audit/page.jinja:1:1', 'app/mounts/reports/audit/route.py:5:39', 'app/routes/admin/reports/route.py:1:1', 'app.mounts.reports.audit.handlers:page', 'reports:/audit'), (('layout', 'page', '/', 'routes/layout.jinja', 'app/routes/layout.jinja:1:1', 'none', 'app/routes/layout.py:1:1', 'none', 'none'), ('layout', 'page', '/admin/reports', 'mounts/reports/layout.jinja', 'app/mounts/reports/layout.jinja:1:1', 'none', 'app/mounts/reports/layout.py:1:1', 'none', 'reports:/audit')), ()),
        },
        parameters=(),
        environment=selected_environment,
        template_inspection=selected_template_inspection,
    )
    endpoint_4 = _build_endpoint(
        handlers={
            'GET': _handler_4,
        },
        creators={
            'GET': _creator_4,
        },
        navigation={'GET': (('Reports', None, '/user/reports', True),)},
        evidence={
            'GET': ('page', '/user/reports', ('GET', 'HEAD'), 'app/mounts/reports/route.py', 1, 1, 'app.mounts.reports.handlers', 'page', 'page', 'app/routes/user/reports/route.py', 'reports', '/', 1, 1, '/user/reports'),
        },
        embedded_expectations={
            'GET': (('/table', ('fragment', '/user/reports/table', ('GET', 'HEAD'), 'app/mounts/reports/route.py', 1, 1, 'app.mounts.reports.handlers', 'table', 'table', 'app/routes/user/reports/route.py', 'reports', '/', 1, 1, '/user/reports'), ('mounts/reports/table.jinja', 'app/mounts/reports/table.jinja', 1, 1, None, ('app/mounts/reports/route.py', 8, 61))),),
        },
        rendering={
            'GET': (('mounts/reports/page.jinja', 'app/mounts/reports/page.jinja', 1, 1, None, ('app/mounts/reports/route.py', 7, 14)), (('app/routes/layout.py', 1, 1, '/', ('routes/layout.jinja', 'app/routes/layout.jinja', 1, 1, None, None)), ('app/mounts/reports/layout.py', 1, 1, '/', ('mounts/reports/layout.jinja', 'app/mounts/reports/layout.jinja', 1, 1, None, None))), ('page', 'page', '/user/reports', 'mounts/reports/page.jinja', 'app/mounts/reports/page.jinja:1:1', 'app/mounts/reports/route.py:7:14', 'app/routes/user/reports/route.py:1:1', 'app.mounts.reports.handlers:page', 'reports:/'), (('layout', 'page', '/', 'routes/layout.jinja', 'app/routes/layout.jinja:1:1', 'none', 'app/routes/layout.py:1:1', 'none', 'none'), ('layout', 'page', '/user/reports', 'mounts/reports/layout.jinja', 'app/mounts/reports/layout.jinja:1:1', 'none', 'app/mounts/reports/layout.py:1:1', 'none', 'reports:/')), (('/table', ('fragment', 'embedded-fragment', '/user/reports/table', 'mounts/reports/table.jinja', 'app/mounts/reports/table.jinja:1:1', 'app/mounts/reports/route.py:8:61', 'app/routes/user/reports/route.py:1:1', 'app.mounts.reports.handlers:table', 'reports:/')),)),
        },
        parameters=(),
        environment=selected_environment,
        template_inspection=selected_template_inspection,
    )
    endpoint_5 = _build_endpoint(
        handlers={
            'GET': _handler_5,
        },
        creators={
            'GET': _creator_5,
        },
        navigation={'GET': (('Reports', None, '/user/reports', True),)},
        evidence={
            'GET': ('fragment', '/user/reports/table', ('GET', 'HEAD'), 'app/mounts/reports/route.py', 1, 1, 'app.mounts.reports.handlers', 'table', 'table', 'app/routes/user/reports/route.py', 'reports', '/', 1, 1, '/user/reports'),
        },
        embedded_expectations={
            'GET': (('/table', ('fragment', '/user/reports/table', ('GET', 'HEAD'), 'app/mounts/reports/route.py', 1, 1, 'app.mounts.reports.handlers', 'table', 'table', 'app/routes/user/reports/route.py', 'reports', '/', 1, 1, '/user/reports'), ('mounts/reports/table.jinja', 'app/mounts/reports/table.jinja', 1, 1, None, ('app/mounts/reports/route.py', 8, 61))),),
        },
        rendering={
            'GET': (('mounts/reports/table.jinja', 'app/mounts/reports/table.jinja', 1, 1, None, ('app/mounts/reports/route.py', 8, 61)), (('app/routes/layout.py', 1, 1, '/', ('routes/layout.jinja', 'app/routes/layout.jinja', 1, 1, None, None)), ('app/mounts/reports/layout.py', 1, 1, '/', ('mounts/reports/layout.jinja', 'app/mounts/reports/layout.jinja', 1, 1, None, None))), ('fragment', 'fragment', '/user/reports/table', 'mounts/reports/table.jinja', 'app/mounts/reports/table.jinja:1:1', 'app/mounts/reports/route.py:8:61', 'app/routes/user/reports/route.py:1:1', 'app.mounts.reports.handlers:table', 'reports:/'), (('layout', 'page', '/', 'routes/layout.jinja', 'app/routes/layout.jinja:1:1', 'none', 'app/routes/layout.py:1:1', 'none', 'none'), ('layout', 'page', '/user/reports', 'mounts/reports/layout.jinja', 'app/mounts/reports/layout.jinja:1:1', 'none', 'app/mounts/reports/layout.py:1:1', 'none', 'reports:/')), (('/table', ('fragment', 'embedded-fragment', '/user/reports/table', 'mounts/reports/table.jinja', 'app/mounts/reports/table.jinja:1:1', 'app/mounts/reports/route.py:8:61', 'app/routes/user/reports/route.py:1:1', 'app.mounts.reports.handlers:table', 'reports:/')),)),
        },
        parameters=(),
        environment=selected_environment,
        template_inspection=selected_template_inspection,
    )
    _generated_routes: list[_Route] = [
            _Route(
                '/',
                endpoint_0,
                methods=['GET', 'HEAD'],
                error_handler=selected_error_handler,
                error_evidence={'GET': ('page', '/', ('GET', 'HEAD'), 'app/routes/route.py', 1, 1, 'app.routes.handlers', 'page', 'page', 'app/routes/route.py', None, None, 1, 1, '/')},
                error_templates=(None, None),
            ),
            _Route(
                '/admin/reports',
                endpoint_1,
                methods=['GET', 'HEAD'],
                error_handler=selected_error_handler,
                error_evidence={'GET': ('page', '/admin/reports', ('GET', 'HEAD'), 'app/mounts/reports/route.py', 1, 1, 'app.mounts.reports.handlers', 'page', 'page', 'app/routes/admin/reports/route.py', 'reports', '/', 1, 1, '/admin/reports')},
                error_templates=(None, None),
            ),
            _Route(
                '/admin/reports/table',
                endpoint_2,
                methods=['GET', 'HEAD'],
                error_handler=selected_error_handler,
                error_evidence={'GET': ('fragment', '/admin/reports/table', ('GET', 'HEAD'), 'app/mounts/reports/route.py', 1, 1, 'app.mounts.reports.handlers', 'table', 'table', 'app/routes/admin/reports/route.py', 'reports', '/', 1, 1, '/admin/reports')},
                error_templates=(None, None),
            ),
            _Route(
                '/admin/reports/audit',
                endpoint_3,
                methods=['GET', 'HEAD'],
                error_handler=selected_error_handler,
                error_evidence={'GET': ('page', '/admin/reports/audit', ('GET', 'HEAD'), 'app/mounts/reports/audit/route.py', 1, 1, 'app.mounts.reports.audit.handlers', 'page', 'page', 'app/routes/admin/reports/route.py', 'reports', '/audit', 1, 1, '/admin/reports')},
                error_templates=(None, None),
            ),
            _Route(
                '/user/reports',
                endpoint_4,
                methods=['GET', 'HEAD'],
                error_handler=selected_error_handler,
                error_evidence={'GET': ('page', '/user/reports', ('GET', 'HEAD'), 'app/mounts/reports/route.py', 1, 1, 'app.mounts.reports.handlers', 'page', 'page', 'app/routes/user/reports/route.py', 'reports', '/', 1, 1, '/user/reports')},
                error_templates=(None, None),
            ),
            _Route(
                '/user/reports/table',
                endpoint_5,
                methods=['GET', 'HEAD'],
                error_handler=selected_error_handler,
                error_evidence={'GET': ('fragment', '/user/reports/table', ('GET', 'HEAD'), 'app/mounts/reports/route.py', 1, 1, 'app.mounts.reports.handlers', 'table', 'table', 'app/routes/user/reports/route.py', 'reports', '/', 1, 1, '/user/reports')},
                error_templates=(None, None),
            ),
    ]
    if selected_error_handler is None:
        return _Router(
            routes=_generated_routes,
            redirect_slashes=False,
        )
    return _ErrorRouter(
        routes=_generated_routes,
        redirect_slashes=False,
        error_handler=selected_error_handler,
    )


router: _Router = create_router()
