# Code generated by pyganini; DO NOT EDIT.
"""Generated Pyganini URL helper interface."""

from __future__ import annotations

from dataclasses import dataclass as _dataclass
from typing import overload as _overload
from urllib.parse import quote as _quote

__all__ = ("mount_urls", "urls")

def _quote_segment(label: str, value: object) -> str:
    if not isinstance(value, str):
        raise TypeError(f"{label} must be str")
    if value == "":
        raise ValueError(f"{label} must not be empty")
    if value in {".", ".."}:
        raise ValueError(f"{label} must not be '.' or '..'")
    if "/" in value or chr(92) in value:
        raise ValueError(
            f"{label} must not contain '/' or '" + chr(92) + "'"
        )
    if any(
        ord(character) < 32 or ord(character) == 127
        for character in value
    ):
        raise ValueError(
            f"{label} must not contain ASCII control characters"
        )
    try:
        value.encode("utf-8")
    except UnicodeEncodeError as error:
        raise ValueError(
            f"{label} must contain valid Unicode text"
        ) from error
    return _quote(value, safe="")

def _normalize_base_path(base_path: object) -> str:
    if not isinstance(base_path, str):
        raise TypeError("base_path must be str")
    if base_path in {"", "/"}:
        return ""
    if all(character == "/" for character in base_path):
        raise ValueError("base_path must not contain empty path segments")
    normalized = base_path if base_path.startswith("/") else "/" + base_path
    normalized = normalized.rstrip("/")
    segments = normalized[1:].split("/")
    if any(segment == "" for segment in segments):
        raise ValueError("base_path must not contain empty path segments")
    quoted = tuple(
        _quote_segment(f"base_path segment {index}", segment)
        for index, segment in enumerate(segments, start=1)
    )
    return "/" + "/".join(quoted)

@_dataclass(frozen=True, slots=True)
class _URLRootPath:
    _base_path: str
    _owner_key: str | None

    @property
    def path(self) -> str:
        return self._base_path + "/"


@_dataclass(frozen=True, slots=True)
class _URLNode0:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    def with_base_path(self, base_path: str) -> _URLNode0:
        """Return this surface bound to a decoded path prefix."""
        return _URLNode0(_normalize_base_path(base_path), "", self._owner_key)

    @property
    def root(self) -> _URLRootPath:
        return _URLRootPath(self._base_path, self._owner_key)

    @property
    def admin(self) -> _URLNode1:
        return _URLNode1(
            self._base_path,
            self._local_path + '/admin',
            None,
        )

    @property
    def user(self) -> _URLNode5:
        return _URLNode5(
            self._base_path,
            self._local_path + '/user',
            None,
        )


@_dataclass(frozen=True, slots=True)
class _URLNode1:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def reports(self) -> _URLNode2:
        return _URLNode2(
            self._base_path,
            self._local_path + '/reports',
            'app/routes/admin/reports/route.py',
        )


@_dataclass(frozen=True, slots=True)
class _URLNode2:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def path(self) -> str:
        return self._base_path + self._local_path

    @property
    def audit(self) -> _URLNode3:
        return _URLNode3(
            self._base_path,
            self._local_path + '/audit',
            None,
        )

    @property
    def table(self) -> _URLNode4:
        return _URLNode4(
            self._base_path,
            self._local_path + '/table',
            None,
        )


@_dataclass(frozen=True, slots=True)
class _URLNode3:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def path(self) -> str:
        return self._base_path + self._local_path


@_dataclass(frozen=True, slots=True)
class _URLNode4:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def path(self) -> str:
        return self._base_path + self._local_path


@_dataclass(frozen=True, slots=True)
class _URLNode5:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def reports(self) -> _URLNode6:
        return _URLNode6(
            self._base_path,
            self._local_path + '/reports',
            'app/routes/user/reports/route.py',
        )


@_dataclass(frozen=True, slots=True)
class _URLNode6:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def path(self) -> str:
        return self._base_path + self._local_path

    @property
    def table(self) -> _URLNode7:
        return _URLNode7(
            self._base_path,
            self._local_path + '/table',
            None,
        )


@_dataclass(frozen=True, slots=True)
class _URLNode7:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def path(self) -> str:
        return self._base_path + self._local_path


urls: _URLNode0 = _URLNode0("", "", None)


@_dataclass(frozen=True, slots=True)
class _MountBound0Node0:
    _base_path: str
    _local_path: str

    @property
    def path(self) -> str:
        return self._base_path + (self._local_path or '/')

    @property
    def audit(self) -> _MountBound0Node1:
        return _MountBound0Node1(
            self._base_path,
            self._local_path + '/audit',
        )

    @property
    def table(self) -> _MountBound0Node2:
        return _MountBound0Node2(
            self._base_path,
            self._local_path + '/table',
        )


@_dataclass(frozen=True, slots=True)
class _MountBound0Node1:
    _base_path: str
    _local_path: str

    @property
    def path(self) -> str:
        return self._base_path + (self._local_path or '/')


@_dataclass(frozen=True, slots=True)
class _MountBound0Node2:
    _base_path: str
    _local_path: str

    @property
    def path(self) -> str:
        return self._base_path + (self._local_path or '/')


@_dataclass(frozen=True, slots=True)
class _MountBound1Node0:
    _base_path: str
    _local_path: str

    @property
    def path(self) -> str:
        return self._base_path + (self._local_path or '/')

    @property
    def table(self) -> _MountBound1Node1:
        return _MountBound1Node1(
            self._base_path,
            self._local_path + '/table',
        )


@_dataclass(frozen=True, slots=True)
class _MountBound1Node1:
    _base_path: str
    _local_path: str

    @property
    def path(self) -> str:
        return self._base_path + (self._local_path or '/')


@_dataclass(frozen=True, slots=True)
class _MountCatalogRoot_0:

    @_overload
    def bind(self, owner: _URLNode2) -> _MountBound0Node0:
        ...

    @_overload
    def bind(self, owner: _URLNode6) -> _MountBound1Node0:
        ...

    def bind(self, owner: object) -> object:
        owner_key = getattr(owner, '_owner_key', None)
        if owner_key == 'app/routes/admin/reports/route.py':
            base_path = getattr(owner, '_base_path', None)
            local_path = getattr(owner, '_local_path', None)
            if not isinstance(base_path, str) or not isinstance(
                local_path, str
            ):
                raise ValueError(
                    'owner is not a generated live URL node for mount reports'
                )
            return _MountBound0Node0(base_path, local_path)
        if owner_key == 'app/routes/user/reports/route.py':
            base_path = getattr(owner, '_base_path', None)
            local_path = getattr(owner, '_local_path', None)
            if not isinstance(base_path, str) or not isinstance(
                local_path, str
            ):
                raise ValueError(
                    'owner is not a generated live URL node for mount reports'
                )
            return _MountBound1Node0(base_path, local_path)
        raise ValueError(
            'owner is not a live owner of mount reports'
        )


@_dataclass(frozen=True, slots=True)
class _MountCatalogRoot:

    @property
    def reports(self) -> _MountCatalogRoot_0:
        return _MountCatalogRoot_0()


mount_urls: _MountCatalogRoot = _MountCatalogRoot()
