# Code generated by pyganini; DO NOT EDIT.
"""Generated Pyganini ASGI routing surface."""

from jinja2 import Environment as _Environment
from starlette.routing import Router as _Router

from pyganini import RouteErrorHandler as _RouteErrorHandler
from pyganini import TemplateInspectionMode as _TemplateInspectionMode
from pyganini._dispatch import build_endpoint as _build_endpoint
from pyganini._dispatch import load_route as _load_route
from pyganini._dispatch import PathPriorityRoute as _Route
from pyganini._dispatch import RouteErrorRouter as _ErrorRouter
from pyganini._dispatch import prepare_environment as _prepare_environment
from pyganini._dispatch import prepare_route_error_handler as _prepare_route_error_handler
from pyganini._dispatch import prepare_template_inspection as _prepare_template_inspection
from pyganini._dispatch import select_handler as _select_handler

_template_names = ('routes/chat/composer.jinja', 'routes/chat/page.jinja', 'routes/join_form.jinja', 'routes/layout.jinja', 'routes/page.jinja')

_route_0 = _load_route(
    module='app.routes.chat.route',
    source_path='app/routes/chat/route.py',
    expected=(
        ('page', 'GET', '/', '/chat', ('GET', 'HEAD'), 'app.routes.chat.handlers', 'page', 'page', 'app/routes/chat/route.py', 7, 10, 'page.jinja', 'app/routes/chat/route.py', None, None, None, None),
        ('action', 'POST', '/message', '/chat/message', ('POST',), 'app.routes.chat.handlers', 'post_message', 'post_message', 'app/routes/chat/route.py', 10, 9, 'composer.jinja', 'app/routes/chat/route.py', None, None, ('form', (1, 4, 65536, 65536)), ('app/routes/chat/route.py', 15, 26)),
        ('action', 'POST', '/sign-out', '/chat/sign-out', ('POST',), 'app.routes.chat.handlers', 'post_sign_out', 'post_sign_out', 'app/routes/chat/route.py', 22, 9, None, 'app/routes/chat/route.py', None, None, None, None),
    ),
    expected_creator=None,
    expected_template_root=None,
)

_route_1 = _load_route(
    module='app.routes.route',
    source_path='app/routes/route.py',
    expected=(
        ('page', 'GET', '/', '/', ('GET', 'HEAD'), 'app.routes.handlers', 'page', 'page', 'app/routes/route.py', 7, 10, 'page.jinja', 'app/routes/route.py', None, None, None, None),
        ('action', 'POST', '/join', '/join', ('POST',), 'app.routes.handlers', 'post_join', 'post_join', 'app/routes/route.py', 10, 9, 'join_form.jinja', 'app/routes/route.py', None, None, ('form', (1, 4, 4096, 4096)), ('app/routes/route.py', 15, 26)),
    ),
    expected_creator=None,
    expected_template_root=None,
)

_handler_0 = _select_handler(
    _route_1,
    kind='page',
    method='GET',
    local_path='/',
)

_handler_1 = _select_handler(
    _route_1,
    kind='action',
    method='POST',
    local_path='/join',
)

_handler_2 = _select_handler(
    _route_0,
    kind='page',
    method='GET',
    local_path='/',
)

_handler_3 = _select_handler(
    _route_0,
    kind='action',
    method='POST',
    local_path='/message',
)

_handler_4 = _select_handler(
    _route_0,
    kind='action',
    method='POST',
    local_path='/sign-out',
)

def create_router(
    *,
    environment: _Environment | None = None,
    error_handler: _RouteErrorHandler | None = None,
    template_inspection: _TemplateInspectionMode = _TemplateInspectionMode.OFF,
) -> _Router:
    selected_template_inspection = _prepare_template_inspection(
        template_inspection,
        source_path='app/_pyganini/asgi.py',
    )
    selected_environment = _prepare_environment(
        environment,
        template_names=_template_names,
        source_path='app/_pyganini/asgi.py',
    )
    selected_error_handler = _prepare_route_error_handler(
        error_handler,
        template_inspection=selected_template_inspection,
        source_path='app/_pyganini/asgi.py',
    )
    endpoint_0 = _build_endpoint(
        handlers={
            'GET': _handler_0,
        },
        evidence={
            'GET': ('page', '/', ('GET', 'HEAD'), 'app/routes/route.py', 1, 1, 'app.routes.handlers', 'page', 'page', 'app/routes/route.py', None, None, 1, 1, '/'),
        },
        embedded_expectations={
            'GET': (),
        },
        rendering={
            'GET': (('routes/page.jinja', 'app/routes/page.jinja', 1, 1, None, ('app/routes/route.py', 8, 14)), (('app/routes/layout.py', 1, 1, '/', ('routes/layout.jinja', 'app/routes/layout.jinja', 1, 1, None, None)),), ('page', 'page', '/', 'routes/page.jinja', 'app/routes/page.jinja:1:1', 'app/routes/route.py:8:14', 'app/routes/route.py:1:1', 'app.routes.handlers:page', 'none'), (('layout', 'page', '/', 'routes/layout.jinja', 'app/routes/layout.jinja:1:1', 'none', 'app/routes/layout.py:1:1', 'none', 'none'),), ()),
        },
        parameters=(),
        environment=selected_environment,
        template_inspection=selected_template_inspection,
    )
    endpoint_1 = _build_endpoint(
        handlers={
            'POST': _handler_1,
        },
        request_data={
            'POST': ('form', (1, 4, 4096, 4096)),
        },
        evidence={
            'POST': ('action', '/join', ('POST',), 'app/routes/route.py', 1, 1, 'app.routes.handlers', 'post_join', 'post_join', 'app/routes/route.py', None, None, 1, 1, '/'),
        },
        embedded_expectations={
            'POST': (),
        },
        rendering={
            'POST': (('routes/join_form.jinja', 'app/routes/join_form.jinja', 1, 1, None, ('app/routes/route.py', 14, 22)), (('app/routes/layout.py', 1, 1, '/', ('routes/layout.jinja', 'app/routes/layout.jinja', 1, 1, None, None)),), ('action', 'action', '/join', 'routes/join_form.jinja', 'app/routes/join_form.jinja:1:1', 'app/routes/route.py:14:22', 'app/routes/route.py:1:1', 'app.routes.handlers:post_join', 'none'), (('layout', 'action-page', '/', 'routes/layout.jinja', 'app/routes/layout.jinja:1:1', 'none', 'app/routes/layout.py:1:1', 'none', 'none'),), ()),
        },
        parameters=(),
        environment=selected_environment,
        template_inspection=selected_template_inspection,
    )
    endpoint_2 = _build_endpoint(
        handlers={
            'GET': _handler_2,
        },
        evidence={
            'GET': ('page', '/chat', ('GET', 'HEAD'), 'app/routes/chat/route.py', 1, 1, 'app.routes.chat.handlers', 'page', 'page', 'app/routes/chat/route.py', None, None, 1, 1, '/chat'),
        },
        embedded_expectations={
            'GET': (),
        },
        rendering={
            'GET': (('routes/chat/page.jinja', 'app/routes/chat/page.jinja', 1, 1, None, ('app/routes/chat/route.py', 8, 14)), (('app/routes/layout.py', 1, 1, '/', ('routes/layout.jinja', 'app/routes/layout.jinja', 1, 1, None, None)),), ('page', 'page', '/chat', 'routes/chat/page.jinja', 'app/routes/chat/page.jinja:1:1', 'app/routes/chat/route.py:8:14', 'app/routes/chat/route.py:1:1', 'app.routes.chat.handlers:page', 'none'), (('layout', 'page', '/', 'routes/layout.jinja', 'app/routes/layout.jinja:1:1', 'none', 'app/routes/layout.py:1:1', 'none', 'none'),), ()),
        },
        parameters=(),
        environment=selected_environment,
        template_inspection=selected_template_inspection,
    )
    endpoint_3 = _build_endpoint(
        handlers={
            'POST': _handler_3,
        },
        request_data={
            'POST': ('form', (1, 4, 65536, 65536)),
        },
        evidence={
            'POST': ('action', '/chat/message', ('POST',), 'app/routes/chat/route.py', 1, 1, 'app.routes.chat.handlers', 'post_message', 'post_message', 'app/routes/chat/route.py', None, None, 1, 1, '/chat'),
        },
        embedded_expectations={
            'POST': (),
        },
        rendering={
            'POST': (('routes/chat/composer.jinja', 'app/routes/chat/composer.jinja', 1, 1, None, ('app/routes/chat/route.py', 14, 22)), (('app/routes/layout.py', 1, 1, '/', ('routes/layout.jinja', 'app/routes/layout.jinja', 1, 1, None, None)),), ('action', 'action', '/chat/message', 'routes/chat/composer.jinja', 'app/routes/chat/composer.jinja:1:1', 'app/routes/chat/route.py:14:22', 'app/routes/chat/route.py:1:1', 'app.routes.chat.handlers:post_message', 'none'), (('layout', 'action-page', '/', 'routes/layout.jinja', 'app/routes/layout.jinja:1:1', 'none', 'app/routes/layout.py:1:1', 'none', 'none'),), ()),
        },
        parameters=(),
        environment=selected_environment,
        template_inspection=selected_template_inspection,
    )
    endpoint_4 = _build_endpoint(
        handlers={
            'POST': _handler_4,
        },
        evidence={
            'POST': ('action', '/chat/sign-out', ('POST',), 'app/routes/chat/route.py', 1, 1, 'app.routes.chat.handlers', 'post_sign_out', 'post_sign_out', 'app/routes/chat/route.py', None, None, 1, 1, '/chat'),
        },
        embedded_expectations={
            'POST': (),
        },
        rendering={
            'POST': (None, (('app/routes/layout.py', 1, 1, '/', ('routes/layout.jinja', 'app/routes/layout.jinja', 1, 1, None, None)),), None, (('layout', 'action-page', '/', 'routes/layout.jinja', 'app/routes/layout.jinja:1:1', 'none', 'app/routes/layout.py:1:1', 'none', 'none'),), ()),
        },
        parameters=(),
        environment=selected_environment,
        template_inspection=selected_template_inspection,
    )
    _generated_routes: list[_Route] = [
            _Route(
                '/',
                endpoint_0,
                methods=['GET', 'HEAD'],
                error_handler=selected_error_handler,
                error_evidence={'GET': ('page', '/', ('GET', 'HEAD'), 'app/routes/route.py', 1, 1, 'app.routes.handlers', 'page', 'page', 'app/routes/route.py', None, None, 1, 1, '/')},
                error_templates=(None, None),
            ),
            _Route(
                '/join',
                endpoint_1,
                methods=['POST'],
                error_handler=selected_error_handler,
                error_evidence={'POST': ('action', '/join', ('POST',), 'app/routes/route.py', 1, 1, 'app.routes.handlers', 'post_join', 'post_join', 'app/routes/route.py', None, None, 1, 1, '/')},
                error_templates=(None, None),
            ),
            _Route(
                '/chat',
                endpoint_2,
                methods=['GET', 'HEAD'],
                error_handler=selected_error_handler,
                error_evidence={'GET': ('page', '/chat', ('GET', 'HEAD'), 'app/routes/chat/route.py', 1, 1, 'app.routes.chat.handlers', 'page', 'page', 'app/routes/chat/route.py', None, None, 1, 1, '/chat')},
                error_templates=(None, None),
            ),
            _Route(
                '/chat/message',
                endpoint_3,
                methods=['POST'],
                error_handler=selected_error_handler,
                error_evidence={'POST': ('action', '/chat/message', ('POST',), 'app/routes/chat/route.py', 1, 1, 'app.routes.chat.handlers', 'post_message', 'post_message', 'app/routes/chat/route.py', None, None, 1, 1, '/chat')},
                error_templates=(None, None),
            ),
            _Route(
                '/chat/sign-out',
                endpoint_4,
                methods=['POST'],
                error_handler=selected_error_handler,
                error_evidence={'POST': ('action', '/chat/sign-out', ('POST',), 'app/routes/chat/route.py', 1, 1, 'app.routes.chat.handlers', 'post_sign_out', 'post_sign_out', 'app/routes/chat/route.py', None, None, 1, 1, '/chat')},
                error_templates=(None, None),
            ),
    ]
    if selected_error_handler is None:
        return _Router(
            routes=_generated_routes,
            redirect_slashes=False,
        )
    return _ErrorRouter(
        routes=_generated_routes,
        redirect_slashes=False,
        error_handler=selected_error_handler,
    )


router: _Router = create_router()
