# Code generated by pyganini; DO NOT EDIT.
"""Generated Pyganini URL helper interface."""

from __future__ import annotations

from dataclasses import dataclass as _dataclass
from urllib.parse import quote as _quote

__all__ = ("mount_urls", "urls")

def _quote_segment(label: str, value: object) -> str:
    if not isinstance(value, str):
        raise TypeError(f"{label} must be str")
    if value == "":
        raise ValueError(f"{label} must not be empty")
    if value in {".", ".."}:
        raise ValueError(f"{label} must not be '.' or '..'")
    if "/" in value or chr(92) in value:
        raise ValueError(
            f"{label} must not contain '/' or '" + chr(92) + "'"
        )
    if any(
        ord(character) < 32 or ord(character) == 127
        for character in value
    ):
        raise ValueError(
            f"{label} must not contain ASCII control characters"
        )
    try:
        value.encode("utf-8")
    except UnicodeEncodeError as error:
        raise ValueError(
            f"{label} must contain valid Unicode text"
        ) from error
    return _quote(value, safe="")

def _normalize_base_path(base_path: object) -> str:
    if not isinstance(base_path, str):
        raise TypeError("base_path must be str")
    if base_path in {"", "/"}:
        return ""
    if all(character == "/" for character in base_path):
        raise ValueError("base_path must not contain empty path segments")
    normalized = base_path if base_path.startswith("/") else "/" + base_path
    normalized = normalized.rstrip("/")
    segments = normalized[1:].split("/")
    if any(segment == "" for segment in segments):
        raise ValueError("base_path must not contain empty path segments")
    quoted = tuple(
        _quote_segment(f"base_path segment {index}", segment)
        for index, segment in enumerate(segments, start=1)
    )
    return "/" + "/".join(quoted)

@_dataclass(frozen=True, slots=True)
class _URLRootPath:
    _base_path: str
    _owner_key: str | None

    @property
    def path(self) -> str:
        return self._base_path + "/"


@_dataclass(frozen=True, slots=True)
class _URLNode0:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    def with_base_path(self, base_path: str) -> _URLNode0:
        """Return this surface bound to a decoded path prefix."""
        return _URLNode0(_normalize_base_path(base_path), "", self._owner_key)

    @property
    def root(self) -> _URLRootPath:
        return _URLRootPath(self._base_path, self._owner_key)

    @property
    def chat(self) -> _URLNode1:
        return _URLNode1(
            self._base_path,
            self._local_path + '/chat',
            None,
        )

    @property
    def join(self) -> _URLNode4:
        return _URLNode4(
            self._base_path,
            self._local_path + '/join',
            None,
        )


@_dataclass(frozen=True, slots=True)
class _URLNode1:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def path(self) -> str:
        return self._base_path + self._local_path

    @property
    def message(self) -> _URLNode2:
        return _URLNode2(
            self._base_path,
            self._local_path + '/message',
            None,
        )

    @property
    def sign_out(self) -> _URLNode3:
        return _URLNode3(
            self._base_path,
            self._local_path + '/sign-out',
            None,
        )


@_dataclass(frozen=True, slots=True)
class _URLNode2:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def path(self) -> str:
        return self._base_path + self._local_path


@_dataclass(frozen=True, slots=True)
class _URLNode3:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def path(self) -> str:
        return self._base_path + self._local_path


@_dataclass(frozen=True, slots=True)
class _URLNode4:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def path(self) -> str:
        return self._base_path + self._local_path


urls: _URLNode0 = _URLNode0("", "", None)


@_dataclass(frozen=True, slots=True)
class _MountCatalogRoot:
    pass


mount_urls: _MountCatalogRoot = _MountCatalogRoot()
