# Code generated by pyganini; DO NOT EDIT.
"""Generated Pyganini ASGI routing surface."""

from jinja2 import Environment as _Environment
from starlette.routing import Router as _Router
from typing import TYPE_CHECKING as _TYPE_CHECKING

from pyganini import KitRouteDef as _KitRouteDef
from pyganini import KitRouteMount as _KitRouteMount
from pyganini import RouteErrorHandler as _RouteErrorHandler
from pyganini import TemplateInspectionMode as _TemplateInspectionMode
from pyganini._dispatch import DispatchError as _DispatchError
from pyganini._dispatch import build_endpoint as _build_endpoint
from pyganini._dispatch import load_route as _load_route
from pyganini._dispatch import load_middleware as _load_middleware
from pyganini._dispatch import middleware_construction_error as _middleware_construction_error
from pyganini._dispatch import load_mount_owner as _load_mount_owner
from pyganini._dispatch import PathPriorityRoute as _Route
from pyganini._dispatch import RouteErrorRouter as _ErrorRouter
from pyganini._dispatch import prepare_environment as _prepare_environment
from pyganini._dispatch import prepare_route_error_handler as _prepare_route_error_handler
from pyganini._dispatch import prepare_template_inspection as _prepare_template_inspection
from pyganini._dispatch import select_creator as _select_creator
from pyganini._dispatch import select_handler as _select_handler

_template_names = ('mounts/contact_directory/by_id/page.jinja', 'mounts/contact_directory/create/directory.jinja', 'mounts/contact_directory/layout.jinja', 'mounts/contact_directory/page.jinja', 'mounts/contact_directory/table.jinja', 'routes/error_fragment.jinja', 'routes/error_page.jinja', 'routes/layout.jinja', 'routes/page.jinja', 'routes/settings/page.jinja', 'routes/settings/users/layout.jinja', 'routes/users/layout.jinja')
_error_rendering = (
    ('routes/error_page.jinja', 'app/routes/error_page.jinja', 1, 1, None, ('app/routes/route.py', 9, 25)),
    ('routes/error_fragment.jinja', 'app/routes/error_fragment.jinja', 1, 1, None, ('app/routes/route.py', 10, 29)),
    (('app/routes/layout.py', 1, 1, '/', ('routes/layout.jinja', 'app/routes/layout.jinja', 1, 1, None, None)),),
    ('page', 'root-error-page', '/', 'routes/error_page.jinja', 'app/routes/error_page.jinja:1:1', 'app/routes/route.py:9:25', 'app/routes/route.py:1:1', 'route_error_handler', 'none'),
    ('fragment', 'root-error-fragment', '/', 'routes/error_fragment.jinja', 'app/routes/error_fragment.jinja:1:1', 'app/routes/route.py:10:29', 'app/routes/route.py:1:1', 'route_error_handler', 'none'),
    (('layout', 'root-error-page', '/', 'routes/layout.jinja', 'app/routes/layout.jinja:1:1', 'none', 'app/routes/layout.py:1:1', 'none', 'none'),),
)

_route_0 = _load_route(
    module='app.routes.problem.route',
    source_path='app/routes/problem/route.py',
    expected=(
        ('page', 'GET', '/', '/problem', ('GET', 'HEAD'), 'app.routes.problem.handlers', 'page', 'page', 'app/routes/problem/route.py', 5, 20, None, 'app/routes/problem/route.py', None, None, None, None),
    ),
    expected_creator=None,
    expected_template_root=None,
)

_route_1 = _load_route(
    module='app.routes.route',
    source_path='app/routes/route.py',
    expected=(
        ('page', 'GET', '/', '/', ('GET', 'HEAD'), 'app.routes.handlers', 'page', 'page', 'app/routes/route.py', 6, 10, 'page.jinja', 'app/routes/route.py', None, None, None, None),
    ),
    expected_creator=None,
    expected_template_root=None,
    expected_nav=('Home', None),
    expected_destinations=(),
    expected_error_page_template='error_page.jinja',
    expected_error_fragment_template='error_fragment.jinja',
)

_route_2 = _load_route(
    module='app.routes.settings.route',
    source_path='app/routes/settings/route.py',
    expected=(
        ('page', 'GET', '/', '/settings', ('GET', 'HEAD'), 'app.routes.settings.handlers', 'page', 'page', 'app/routes/settings/route.py', 5, 20, 'page.jinja', 'app/routes/settings/route.py', None, None, None, None),
    ),
    expected_creator=None,
    expected_template_root=None,
    expected_nav=('Settings', None),
    expected_destinations=(),
)

_route_3 = _load_mount_owner(
    module='app.routes.settings.users.route',
    source_path='app/routes/settings/users/route.py',
    expected_creator=('app.routes.settings.users.route', 'create_settings_users', 'create_settings_users', 'app/routes/settings/users/route.py', 34, 12),
    expected_mount='contact_directory',
    expected_routes=('/',),
    expected_bindings=(('/', 'app/mounts/contact_directory/route.py', '/settings/users'),),
    expected_selections=(('/', None, ()),),
)

_source_0 = _load_route(
    module='app.mounts.contact_directory.route',
    source_path='app/mounts/contact_directory/route.py',
    expected=(
        ('page', 'GET', '/', '/settings/users', ('GET', 'HEAD'), 'app.mounts.contact_directory.handlers', 'page', 'page', 'app/mounts/contact_directory/route.py', 6, 10, 'page.jinja', 'app/routes/settings/users/route.py', 'contact_directory', '/', None, None),
        ('fragment', 'GET', '/table', '/settings/users/table', ('GET', 'HEAD'), 'app.mounts.contact_directory.handlers', 'table', 'table', 'app/mounts/contact_directory/route.py', 8, 16, 'table.jinja', 'app/routes/settings/users/route.py', 'contact_directory', '/', None, None),
    ),
    expected_creator=None,
    expected_template_root=None,
    expected_nav=('Directory', None),
    expected_destinations=(),
    expected_kit=True,
)

_route_4 = _load_mount_owner(
    module='app.routes.users.route',
    source_path='app/routes/users/route.py',
    expected_creator=('app.routes.users.route', 'create_users', 'create_users', 'app/routes/users/route.py', 37, 12),
    expected_mount='contact_directory',
    expected_routes=('/', '/create', '/{id}'),
    expected_bindings=(('/', 'app/mounts/contact_directory/route.py', '/users'), ('/create', 'app/mounts/contact_directory/create/route.py', '/users/create'), ('/{id}', 'app/mounts/contact_directory/by_id/route.py', '/users/{id}')),
    expected_selections=(('/', ('Contacts', None), (('contact-detail', '/users/{id}', 'from-contacts'),)), ('/create', None, ()), ('/{id}', None, ())),
)

_source_1 = _load_route(
    module='app.mounts.contact_directory.by_id.route',
    source_path='app/mounts/contact_directory/by_id/route.py',
    expected=(
        ('page', 'GET', '/', '/users/{id}', ('GET', 'HEAD'), 'app.mounts.contact_directory.by_id.handlers', 'page', 'page', 'app/mounts/contact_directory/by_id/route.py', 6, 10, 'page.jinja', 'app/routes/users/route.py', 'contact_directory', '/{id}', None, None),
    ),
    expected_creator=None,
    expected_template_root=None,
    expected_nav=(None, 'contact'),
    expected_destinations=(),
    expected_kit=True,
)

_source_2 = _load_route(
    module='app.mounts.contact_directory.create.route',
    source_path='app/mounts/contact_directory/create/route.py',
    expected=(
        ('action', 'POST', '/', '/users/create', ('POST',), 'app.mounts.contact_directory.create.handlers', 'post_create', 'post_create', 'app/mounts/contact_directory/create/route.py', 8, 9, 'directory.jinja', 'app/routes/users/route.py', 'contact_directory', '/create', ('form', (4, 16, 65536, 65536)), ('app/mounts/contact_directory/create/route.py', 12, 26)),
    ),
    expected_creator=None,
    expected_template_root=None,
    expected_kit=True,
)

_source_3 = _load_route(
    module='app.mounts.contact_directory.route',
    source_path='app/mounts/contact_directory/route.py',
    expected=(
        ('page', 'GET', '/', '/users', ('GET', 'HEAD'), 'app.mounts.contact_directory.handlers', 'page', 'page', 'app/mounts/contact_directory/route.py', 6, 10, 'page.jinja', 'app/routes/users/route.py', 'contact_directory', '/', None, None),
        ('fragment', 'GET', '/table', '/users/table', ('GET', 'HEAD'), 'app.mounts.contact_directory.handlers', 'table', 'table', 'app/mounts/contact_directory/route.py', 8, 16, 'table.jinja', 'app/routes/users/route.py', 'contact_directory', '/', None, None),
    ),
    expected_creator=None,
    expected_template_root=None,
    expected_nav=('Directory', None),
    expected_destinations=(),
    expected_kit=True,
)

if _TYPE_CHECKING:
    def _check_mounted_kit[K](
        owner: _KitRouteMount[K],
        source: _KitRouteDef[K],
    ) -> None:
        ...
    # Owner/source generic type witness.
    from app.routes.settings.users.route import Route as _owner_route_3
    from app.mounts.contact_directory.route import Route as _source_route_0
    _check_mounted_kit(_owner_route_3, _source_route_0)
    # Owner/source generic type witness.
    from app.routes.users.route import Route as _owner_route_4
    from app.mounts.contact_directory.by_id.route import Route as _source_route_1
    _check_mounted_kit(_owner_route_4, _source_route_1)
    from app.routes.users.route import Route as _owner_route_4
    from app.mounts.contact_directory.create.route import Route as _source_route_2
    _check_mounted_kit(_owner_route_4, _source_route_2)
    from app.routes.users.route import Route as _owner_route_4
    from app.mounts.contact_directory.route import Route as _source_route_3
    _check_mounted_kit(_owner_route_4, _source_route_3)

_handler_0 = _select_handler(
    _route_1,
    kind='page',
    method='GET',
    local_path='/',
)

_handler_1 = _select_handler(
    _route_0,
    kind='page',
    method='GET',
    local_path='/',
)

_handler_2 = _select_handler(
    _route_2,
    kind='page',
    method='GET',
    local_path='/',
)

_handler_3 = _select_handler(
    _source_0,
    kind='page',
    method='GET',
    local_path='/',
)

_creator_3 = _select_creator(
    _route_3,
)

_handler_4 = _select_handler(
    _source_0,
    kind='fragment',
    method='GET',
    local_path='/table',
)

_creator_4 = _select_creator(
    _route_3,
)

_handler_5 = _select_handler(
    _source_3,
    kind='page',
    method='GET',
    local_path='/',
)

_creator_5 = _select_creator(
    _route_4,
)

_handler_6 = _select_handler(
    _source_3,
    kind='fragment',
    method='GET',
    local_path='/table',
)

_creator_6 = _select_creator(
    _route_4,
)

_handler_7 = _select_handler(
    _source_2,
    kind='action',
    method='POST',
    local_path='/',
)

_creator_7 = _select_creator(
    _route_4,
)

_handler_8 = _select_handler(
    _source_1,
    kind='page',
    method='GET',
    local_path='/',
)

_creator_8 = _select_creator(
    _route_4,
)

_middleware_0 = _load_middleware(
    module='app.routes.settings.users.middleware',
    source_path='app/routes/settings/users/middleware.py',
    route_prefix='/settings/users',
    expected_entries=((6, 5),),
    binding=(5, 1),
    consumers=(('GET', 'page', '/settings/users', ('GET', 'HEAD'), 'app/routes/settings/users/route.py', 1, 1, 'contact_directory', 'app/mounts/contact_directory/route.py', '/', (('app/routes/settings/users/middleware.py', 5, 1, '/settings/users', ((6, 5),)),)), ('GET', 'fragment', '/settings/users/table', ('GET', 'HEAD'), 'app/routes/settings/users/route.py', 1, 1, 'contact_directory', 'app/mounts/contact_directory/route.py', '/', (('app/routes/settings/users/middleware.py', 5, 1, '/settings/users', ((6, 5),)),))),
)

_middleware_1 = _load_middleware(
    module='app.routes.users.middleware',
    source_path='app/routes/users/middleware.py',
    route_prefix='/users',
    expected_entries=((6, 5),),
    binding=(5, 1),
    consumers=(('GET', 'page', '/users', ('GET', 'HEAD'), 'app/routes/users/route.py', 1, 1, 'contact_directory', 'app/mounts/contact_directory/route.py', '/', (('app/routes/users/middleware.py', 5, 1, '/users', ((6, 5),)),)), ('GET', 'fragment', '/users/table', ('GET', 'HEAD'), 'app/routes/users/route.py', 1, 1, 'contact_directory', 'app/mounts/contact_directory/route.py', '/', (('app/routes/users/middleware.py', 5, 1, '/users', ((6, 5),)),)), ('POST', 'action', '/users/create', ('POST',), 'app/routes/users/route.py', 1, 1, 'contact_directory', 'app/mounts/contact_directory/create/route.py', '/create', (('app/routes/users/middleware.py', 5, 1, '/users', ((6, 5),)),)), ('GET', 'page', '/users/{id}', ('GET', 'HEAD'), 'app/routes/users/route.py', 1, 1, 'contact_directory', 'app/mounts/contact_directory/by_id/route.py', '/{id}', (('app/routes/users/middleware.py', 5, 1, '/users', ((6, 5),)),))),
)

def create_router(
    *,
    environment: _Environment | None = None,
    error_handler: _RouteErrorHandler | None = None,
    template_inspection: _TemplateInspectionMode = _TemplateInspectionMode.OFF,
) -> _Router:
    selected_template_inspection = _prepare_template_inspection(
        template_inspection,
        source_path='app/_pyganini/asgi.py',
    )
    selected_environment = _prepare_environment(
        environment,
        template_names=_template_names,
        source_path='app/_pyganini/asgi.py',
    )
    selected_error_handler = _prepare_route_error_handler(
        error_handler,
        template_inspection=selected_template_inspection,
        environment=selected_environment,
        rendering=_error_rendering,
        owner=('app/routes/route.py', 1, 1),
        source_path='app/_pyganini/asgi.py',
    )
    endpoint_0 = _build_endpoint(
        handlers={
            'GET': _handler_0,
        },
        navigation={'GET': (('Home', None, '/', True),)},
        evidence={
            'GET': ('page', '/', ('GET', 'HEAD'), 'app/routes/route.py', 1, 1, 'app.routes.handlers', 'page', 'page', 'app/routes/route.py', None, None, 1, 1, '/'),
        },
        embedded_expectations={
            'GET': (),
        },
        rendering={
            'GET': (('routes/page.jinja', 'app/routes/page.jinja', 1, 1, None, ('app/routes/route.py', 7, 14)), (('app/routes/layout.py', 1, 1, '/', ('routes/layout.jinja', 'app/routes/layout.jinja', 1, 1, None, None)),), ('page', 'page', '/', 'routes/page.jinja', 'app/routes/page.jinja:1:1', 'app/routes/route.py:7:14', 'app/routes/route.py:1:1', 'app.routes.handlers:page', 'none'), (('layout', 'page', '/', 'routes/layout.jinja', 'app/routes/layout.jinja:1:1', 'none', 'app/routes/layout.py:1:1', 'none', 'none'),), ()),
        },
        parameters=(),
        environment=selected_environment,
        template_inspection=selected_template_inspection,
        error_rendering=_error_rendering,
    )
    endpoint_1 = _build_endpoint(
        handlers={
            'GET': _handler_1,
        },
        navigation={'GET': (('Home', None, '/', False),)},
        evidence={
            'GET': ('page', '/problem', ('GET', 'HEAD'), 'app/routes/problem/route.py', 1, 1, 'app.routes.problem.handlers', 'page', 'page', 'app/routes/problem/route.py', None, None, 1, 1, '/problem'),
        },
        embedded_expectations={
            'GET': (),
        },
        rendering={
            'GET': (None, (('app/routes/layout.py', 1, 1, '/', ('routes/layout.jinja', 'app/routes/layout.jinja', 1, 1, None, None)),), None, (('layout', 'page', '/', 'routes/layout.jinja', 'app/routes/layout.jinja:1:1', 'none', 'app/routes/layout.py:1:1', 'none', 'none'),), ()),
        },
        parameters=(),
        environment=selected_environment,
        template_inspection=selected_template_inspection,
        error_rendering=_error_rendering,
    )
    endpoint_2 = _build_endpoint(
        handlers={
            'GET': _handler_2,
        },
        navigation={'GET': (('Home', None, '/', False), ('Settings', None, '/settings', True))},
        evidence={
            'GET': ('page', '/settings', ('GET', 'HEAD'), 'app/routes/settings/route.py', 1, 1, 'app.routes.settings.handlers', 'page', 'page', 'app/routes/settings/route.py', None, None, 1, 1, '/settings'),
        },
        embedded_expectations={
            'GET': (),
        },
        rendering={
            'GET': (('routes/settings/page.jinja', 'app/routes/settings/page.jinja', 1, 1, None, ('app/routes/settings/route.py', 5, 35)), (('app/routes/layout.py', 1, 1, '/', ('routes/layout.jinja', 'app/routes/layout.jinja', 1, 1, None, None)),), ('page', 'page', '/settings', 'routes/settings/page.jinja', 'app/routes/settings/page.jinja:1:1', 'app/routes/settings/route.py:5:35', 'app/routes/settings/route.py:1:1', 'app.routes.settings.handlers:page', 'none'), (('layout', 'page', '/', 'routes/layout.jinja', 'app/routes/layout.jinja:1:1', 'none', 'app/routes/layout.py:1:1', 'none', 'none'),), ()),
        },
        parameters=(),
        environment=selected_environment,
        template_inspection=selected_template_inspection,
        error_rendering=_error_rendering,
    )
    endpoint_3 = _build_endpoint(
        handlers={
            'GET': _handler_3,
        },
        creators={
            'GET': _creator_3,
        },
        navigation={'GET': (('Home', None, '/', False), ('Settings', None, '/settings', False), ('Directory', None, '/settings/users', True))},
        evidence={
            'GET': ('page', '/settings/users', ('GET', 'HEAD'), 'app/mounts/contact_directory/route.py', 1, 1, 'app.mounts.contact_directory.handlers', 'page', 'page', 'app/routes/settings/users/route.py', 'contact_directory', '/', 1, 1, '/settings/users'),
        },
        embedded_expectations={
            'GET': (('/table', ('fragment', '/settings/users/table', ('GET', 'HEAD'), 'app/mounts/contact_directory/route.py', 1, 1, 'app.mounts.contact_directory.handlers', 'table', 'table', 'app/routes/settings/users/route.py', 'contact_directory', '/', 1, 1, '/settings/users'), ('mounts/contact_directory/table.jinja', 'app/mounts/contact_directory/table.jinja', 1, 1, None, ('app/mounts/contact_directory/route.py', 8, 61))),),
        },
        rendering={
            'GET': (('mounts/contact_directory/page.jinja', 'app/mounts/contact_directory/page.jinja', 1, 1, None, ('app/mounts/contact_directory/route.py', 7, 14)), (('app/routes/layout.py', 1, 1, '/', ('routes/layout.jinja', 'app/routes/layout.jinja', 1, 1, None, None)), ('app/routes/settings/users/layout.py', 1, 1, '/settings/users', ('routes/settings/users/layout.jinja', 'app/routes/settings/users/layout.jinja', 1, 1, None, None)), ('app/mounts/contact_directory/layout.py', 1, 1, '/', ('mounts/contact_directory/layout.jinja', 'app/mounts/contact_directory/layout.jinja', 1, 1, None, None))), ('page', 'page', '/settings/users', 'mounts/contact_directory/page.jinja', 'app/mounts/contact_directory/page.jinja:1:1', 'app/mounts/contact_directory/route.py:7:14', 'app/routes/settings/users/route.py:1:1', 'app.mounts.contact_directory.handlers:page', 'contact_directory:/'), (('layout', 'page', '/', 'routes/layout.jinja', 'app/routes/layout.jinja:1:1', 'none', 'app/routes/layout.py:1:1', 'none', 'none'), ('layout', 'page', '/settings/users', 'routes/settings/users/layout.jinja', 'app/routes/settings/users/layout.jinja:1:1', 'none', 'app/routes/settings/users/layout.py:1:1', 'none', 'none'), ('layout', 'page', '/settings/users', 'mounts/contact_directory/layout.jinja', 'app/mounts/contact_directory/layout.jinja:1:1', 'none', 'app/mounts/contact_directory/layout.py:1:1', 'none', 'contact_directory:/')), (('/table', ('fragment', 'embedded-fragment', '/settings/users/table', 'mounts/contact_directory/table.jinja', 'app/mounts/contact_directory/table.jinja:1:1', 'app/mounts/contact_directory/route.py:8:61', 'app/routes/settings/users/route.py:1:1', 'app.mounts.contact_directory.handlers:table', 'contact_directory:/')),)),
        },
        parameters=(),
        environment=selected_environment,
        template_inspection=selected_template_inspection,
        error_rendering=_error_rendering,
    )
    endpoint_4 = _build_endpoint(
        handlers={
            'GET': _handler_4,
        },
        creators={
            'GET': _creator_4,
        },
        navigation={'GET': (('Home', None, '/', False), ('Settings', None, '/settings', False), ('Directory', None, '/settings/users', True))},
        evidence={
            'GET': ('fragment', '/settings/users/table', ('GET', 'HEAD'), 'app/mounts/contact_directory/route.py', 1, 1, 'app.mounts.contact_directory.handlers', 'table', 'table', 'app/routes/settings/users/route.py', 'contact_directory', '/', 1, 1, '/settings/users'),
        },
        embedded_expectations={
            'GET': (('/table', ('fragment', '/settings/users/table', ('GET', 'HEAD'), 'app/mounts/contact_directory/route.py', 1, 1, 'app.mounts.contact_directory.handlers', 'table', 'table', 'app/routes/settings/users/route.py', 'contact_directory', '/', 1, 1, '/settings/users'), ('mounts/contact_directory/table.jinja', 'app/mounts/contact_directory/table.jinja', 1, 1, None, ('app/mounts/contact_directory/route.py', 8, 61))),),
        },
        rendering={
            'GET': (('mounts/contact_directory/table.jinja', 'app/mounts/contact_directory/table.jinja', 1, 1, None, ('app/mounts/contact_directory/route.py', 8, 61)), (('app/routes/layout.py', 1, 1, '/', ('routes/layout.jinja', 'app/routes/layout.jinja', 1, 1, None, None)), ('app/routes/settings/users/layout.py', 1, 1, '/settings/users', ('routes/settings/users/layout.jinja', 'app/routes/settings/users/layout.jinja', 1, 1, None, None)), ('app/mounts/contact_directory/layout.py', 1, 1, '/', ('mounts/contact_directory/layout.jinja', 'app/mounts/contact_directory/layout.jinja', 1, 1, None, None))), ('fragment', 'fragment', '/settings/users/table', 'mounts/contact_directory/table.jinja', 'app/mounts/contact_directory/table.jinja:1:1', 'app/mounts/contact_directory/route.py:8:61', 'app/routes/settings/users/route.py:1:1', 'app.mounts.contact_directory.handlers:table', 'contact_directory:/'), (('layout', 'page', '/', 'routes/layout.jinja', 'app/routes/layout.jinja:1:1', 'none', 'app/routes/layout.py:1:1', 'none', 'none'), ('layout', 'page', '/settings/users', 'routes/settings/users/layout.jinja', 'app/routes/settings/users/layout.jinja:1:1', 'none', 'app/routes/settings/users/layout.py:1:1', 'none', 'none'), ('layout', 'page', '/settings/users', 'mounts/contact_directory/layout.jinja', 'app/mounts/contact_directory/layout.jinja:1:1', 'none', 'app/mounts/contact_directory/layout.py:1:1', 'none', 'contact_directory:/')), (('/table', ('fragment', 'embedded-fragment', '/settings/users/table', 'mounts/contact_directory/table.jinja', 'app/mounts/contact_directory/table.jinja:1:1', 'app/mounts/contact_directory/route.py:8:61', 'app/routes/settings/users/route.py:1:1', 'app.mounts.contact_directory.handlers:table', 'contact_directory:/')),)),
        },
        parameters=(),
        environment=selected_environment,
        template_inspection=selected_template_inspection,
        error_rendering=_error_rendering,
    )
    endpoint_5 = _build_endpoint(
        handlers={
            'GET': _handler_5,
        },
        creators={
            'GET': _creator_5,
        },
        navigation={'GET': (('Home', None, '/', False), ('Contacts', None, '/users', True))},
        evidence={
            'GET': ('page', '/users', ('GET', 'HEAD'), 'app/mounts/contact_directory/route.py', 1, 1, 'app.mounts.contact_directory.handlers', 'page', 'page', 'app/routes/users/route.py', 'contact_directory', '/', 1, 1, '/users'),
        },
        embedded_expectations={
            'GET': (('/table', ('fragment', '/users/table', ('GET', 'HEAD'), 'app/mounts/contact_directory/route.py', 1, 1, 'app.mounts.contact_directory.handlers', 'table', 'table', 'app/routes/users/route.py', 'contact_directory', '/', 1, 1, '/users'), ('mounts/contact_directory/table.jinja', 'app/mounts/contact_directory/table.jinja', 1, 1, None, ('app/mounts/contact_directory/route.py', 8, 61))),),
        },
        rendering={
            'GET': (('mounts/contact_directory/page.jinja', 'app/mounts/contact_directory/page.jinja', 1, 1, None, ('app/mounts/contact_directory/route.py', 7, 14)), (('app/routes/layout.py', 1, 1, '/', ('routes/layout.jinja', 'app/routes/layout.jinja', 1, 1, None, None)), ('app/routes/users/layout.py', 1, 1, '/users', ('routes/users/layout.jinja', 'app/routes/users/layout.jinja', 1, 1, None, None)), ('app/mounts/contact_directory/layout.py', 1, 1, '/', ('mounts/contact_directory/layout.jinja', 'app/mounts/contact_directory/layout.jinja', 1, 1, None, None))), ('page', 'page', '/users', 'mounts/contact_directory/page.jinja', 'app/mounts/contact_directory/page.jinja:1:1', 'app/mounts/contact_directory/route.py:7:14', 'app/routes/users/route.py:1:1', 'app.mounts.contact_directory.handlers:page', 'contact_directory:/'), (('layout', 'page', '/', 'routes/layout.jinja', 'app/routes/layout.jinja:1:1', 'none', 'app/routes/layout.py:1:1', 'none', 'none'), ('layout', 'page', '/users', 'routes/users/layout.jinja', 'app/routes/users/layout.jinja:1:1', 'none', 'app/routes/users/layout.py:1:1', 'none', 'none'), ('layout', 'page', '/users', 'mounts/contact_directory/layout.jinja', 'app/mounts/contact_directory/layout.jinja:1:1', 'none', 'app/mounts/contact_directory/layout.py:1:1', 'none', 'contact_directory:/')), (('/table', ('fragment', 'embedded-fragment', '/users/table', 'mounts/contact_directory/table.jinja', 'app/mounts/contact_directory/table.jinja:1:1', 'app/mounts/contact_directory/route.py:8:61', 'app/routes/users/route.py:1:1', 'app.mounts.contact_directory.handlers:table', 'contact_directory:/')),)),
        },
        parameters=(),
        environment=selected_environment,
        template_inspection=selected_template_inspection,
        error_rendering=_error_rendering,
    )
    endpoint_6 = _build_endpoint(
        handlers={
            'GET': _handler_6,
        },
        creators={
            'GET': _creator_6,
        },
        navigation={'GET': (('Home', None, '/', False), ('Contacts', None, '/users', True))},
        evidence={
            'GET': ('fragment', '/users/table', ('GET', 'HEAD'), 'app/mounts/contact_directory/route.py', 1, 1, 'app.mounts.contact_directory.handlers', 'table', 'table', 'app/routes/users/route.py', 'contact_directory', '/', 1, 1, '/users'),
        },
        embedded_expectations={
            'GET': (('/table', ('fragment', '/users/table', ('GET', 'HEAD'), 'app/mounts/contact_directory/route.py', 1, 1, 'app.mounts.contact_directory.handlers', 'table', 'table', 'app/routes/users/route.py', 'contact_directory', '/', 1, 1, '/users'), ('mounts/contact_directory/table.jinja', 'app/mounts/contact_directory/table.jinja', 1, 1, None, ('app/mounts/contact_directory/route.py', 8, 61))),),
        },
        rendering={
            'GET': (('mounts/contact_directory/table.jinja', 'app/mounts/contact_directory/table.jinja', 1, 1, None, ('app/mounts/contact_directory/route.py', 8, 61)), (('app/routes/layout.py', 1, 1, '/', ('routes/layout.jinja', 'app/routes/layout.jinja', 1, 1, None, None)), ('app/routes/users/layout.py', 1, 1, '/users', ('routes/users/layout.jinja', 'app/routes/users/layout.jinja', 1, 1, None, None)), ('app/mounts/contact_directory/layout.py', 1, 1, '/', ('mounts/contact_directory/layout.jinja', 'app/mounts/contact_directory/layout.jinja', 1, 1, None, None))), ('fragment', 'fragment', '/users/table', 'mounts/contact_directory/table.jinja', 'app/mounts/contact_directory/table.jinja:1:1', 'app/mounts/contact_directory/route.py:8:61', 'app/routes/users/route.py:1:1', 'app.mounts.contact_directory.handlers:table', 'contact_directory:/'), (('layout', 'page', '/', 'routes/layout.jinja', 'app/routes/layout.jinja:1:1', 'none', 'app/routes/layout.py:1:1', 'none', 'none'), ('layout', 'page', '/users', 'routes/users/layout.jinja', 'app/routes/users/layout.jinja:1:1', 'none', 'app/routes/users/layout.py:1:1', 'none', 'none'), ('layout', 'page', '/users', 'mounts/contact_directory/layout.jinja', 'app/mounts/contact_directory/layout.jinja:1:1', 'none', 'app/mounts/contact_directory/layout.py:1:1', 'none', 'contact_directory:/')), (('/table', ('fragment', 'embedded-fragment', '/users/table', 'mounts/contact_directory/table.jinja', 'app/mounts/contact_directory/table.jinja:1:1', 'app/mounts/contact_directory/route.py:8:61', 'app/routes/users/route.py:1:1', 'app.mounts.contact_directory.handlers:table', 'contact_directory:/')),)),
        },
        parameters=(),
        environment=selected_environment,
        template_inspection=selected_template_inspection,
        error_rendering=_error_rendering,
    )
    endpoint_7 = _build_endpoint(
        handlers={
            'POST': _handler_7,
        },
        creators={
            'POST': _creator_7,
        },
        request_data={
            'POST': ('form', (4, 16, 65536, 65536)),
        },
        navigation={'POST': (('Home', None, '/', False), ('Contacts', None, '/users', False))},
        evidence={
            'POST': ('action', '/users/create', ('POST',), 'app/mounts/contact_directory/create/route.py', 1, 1, 'app.mounts.contact_directory.create.handlers', 'post_create', 'post_create', 'app/routes/users/route.py', 'contact_directory', '/create', 1, 1, '/users'),
        },
        embedded_expectations={
            'POST': (),
        },
        rendering={
            'POST': (('mounts/contact_directory/create/directory.jinja', 'app/mounts/contact_directory/create/directory.jinja', 1, 1, None, ('app/mounts/contact_directory/create/route.py', 18, 22)), (('app/routes/layout.py', 1, 1, '/', ('routes/layout.jinja', 'app/routes/layout.jinja', 1, 1, None, None)), ('app/routes/users/layout.py', 1, 1, '/users', ('routes/users/layout.jinja', 'app/routes/users/layout.jinja', 1, 1, None, None)), ('app/mounts/contact_directory/layout.py', 1, 1, '/', ('mounts/contact_directory/layout.jinja', 'app/mounts/contact_directory/layout.jinja', 1, 1, None, None))), ('action', 'action', '/users/create', 'mounts/contact_directory/create/directory.jinja', 'app/mounts/contact_directory/create/directory.jinja:1:1', 'app/mounts/contact_directory/create/route.py:18:22', 'app/routes/users/route.py:1:1', 'app.mounts.contact_directory.create.handlers:post_create', 'contact_directory:/create'), (('layout', 'action-page', '/', 'routes/layout.jinja', 'app/routes/layout.jinja:1:1', 'none', 'app/routes/layout.py:1:1', 'none', 'none'), ('layout', 'action-page', '/users', 'routes/users/layout.jinja', 'app/routes/users/layout.jinja:1:1', 'none', 'app/routes/users/layout.py:1:1', 'none', 'none'), ('layout', 'action-page', '/users', 'mounts/contact_directory/layout.jinja', 'app/mounts/contact_directory/layout.jinja:1:1', 'none', 'app/mounts/contact_directory/layout.py:1:1', 'none', 'contact_directory:/create')), ()),
        },
        parameters=(),
        environment=selected_environment,
        template_inspection=selected_template_inspection,
        error_rendering=_error_rendering,
    )
    endpoint_8 = _build_endpoint(
        handlers={
            'GET': _handler_8,
        },
        creators={
            'GET': _creator_8,
        },
        navigation={'GET': (('Home', None, '/', False), ('Contacts', None, '/users', False), (None, 'contact', '/users/{id}', True))},
        trail_keys={'GET': ('from-contacts',)},
        evidence={
            'GET': ('page', '/users/{id}', ('GET', 'HEAD'), 'app/mounts/contact_directory/by_id/route.py', 1, 1, 'app.mounts.contact_directory.by_id.handlers', 'page', 'page', 'app/routes/users/route.py', 'contact_directory', '/{id}', 1, 1, '/users'),
        },
        embedded_expectations={
            'GET': (),
        },
        rendering={
            'GET': (('mounts/contact_directory/by_id/page.jinja', 'app/mounts/contact_directory/by_id/page.jinja', 1, 1, None, ('app/mounts/contact_directory/by_id/route.py', 7, 14)), (('app/routes/layout.py', 1, 1, '/', ('routes/layout.jinja', 'app/routes/layout.jinja', 1, 1, None, None)), ('app/routes/users/layout.py', 1, 1, '/users', ('routes/users/layout.jinja', 'app/routes/users/layout.jinja', 1, 1, None, None)), ('app/mounts/contact_directory/layout.py', 1, 1, '/', ('mounts/contact_directory/layout.jinja', 'app/mounts/contact_directory/layout.jinja', 1, 1, None, None))), ('page', 'page', '/users/{id}', 'mounts/contact_directory/by_id/page.jinja', 'app/mounts/contact_directory/by_id/page.jinja:1:1', 'app/mounts/contact_directory/by_id/route.py:7:14', 'app/routes/users/route.py:1:1', 'app.mounts.contact_directory.by_id.handlers:page', 'contact_directory:/{id}'), (('layout', 'page', '/', 'routes/layout.jinja', 'app/routes/layout.jinja:1:1', 'none', 'app/routes/layout.py:1:1', 'none', 'none'), ('layout', 'page', '/users', 'routes/users/layout.jinja', 'app/routes/users/layout.jinja:1:1', 'none', 'app/routes/users/layout.py:1:1', 'none', 'none'), ('layout', 'page', '/users', 'mounts/contact_directory/layout.jinja', 'app/mounts/contact_directory/layout.jinja:1:1', 'none', 'app/mounts/contact_directory/layout.py:1:1', 'none', 'contact_directory:/{id}')), ()),
        },
        parameters=('id',),
        environment=selected_environment,
        template_inspection=selected_template_inspection,
        error_rendering=_error_rendering,
    )
    try:
        _generated_route_3 = _Route(
            '/settings/users',
            endpoint_3,
            methods=['GET', 'HEAD'],
            middleware=(*_middleware_0,),
            error_handler=selected_error_handler,
            error_layouts={'GET': (('app/routes/layout.py', 1, 1, '/', ('routes/layout.jinja', 'app/routes/layout.jinja', 1, 1, None, None)), ('app/routes/settings/users/layout.py', 1, 1, '/settings/users', ('routes/settings/users/layout.jinja', 'app/routes/settings/users/layout.jinja', 1, 1, None, None)), ('app/mounts/contact_directory/layout.py', 1, 1, '/', ('mounts/contact_directory/layout.jinja', 'app/mounts/contact_directory/layout.jinja', 1, 1, None, None)))},
            error_inspection={'GET': (('page', 'matched-error-page', '/settings/users', 'routes/error_page.jinja', 'app/routes/error_page.jinja:1:1', 'app/routes/route.py:9:25', 'app/routes/settings/users/route.py:1:1', 'route_error_handler', 'contact_directory:/'), ('fragment', 'matched-error-fragment', '/settings/users', 'routes/error_fragment.jinja', 'app/routes/error_fragment.jinja:1:1', 'app/routes/route.py:10:29', 'app/routes/settings/users/route.py:1:1', 'route_error_handler', 'contact_directory:/'), (('layout', 'matched-error-page', '/', 'routes/layout.jinja', 'app/routes/layout.jinja:1:1', 'none', 'app/routes/layout.py:1:1', 'none', 'none'), ('layout', 'matched-error-page', '/settings/users', 'routes/settings/users/layout.jinja', 'app/routes/settings/users/layout.jinja:1:1', 'none', 'app/routes/settings/users/layout.py:1:1', 'none', 'none'), ('layout', 'matched-error-page', '/settings/users', 'mounts/contact_directory/layout.jinja', 'app/mounts/contact_directory/layout.jinja:1:1', 'none', 'app/mounts/contact_directory/layout.py:1:1', 'none', 'contact_directory:/')))},
            error_evidence={'GET': ('page', '/settings/users', ('GET', 'HEAD'), 'app/mounts/contact_directory/route.py', 1, 1, 'app.mounts.contact_directory.handlers', 'page', 'page', 'app/routes/settings/users/route.py', 'contact_directory', '/', 1, 1, '/settings/users')},
            error_templates=(('routes/error_page.jinja', 'app/routes/error_page.jinja', 1, 1, None, ('app/routes/route.py', 9, 25)), ('routes/error_fragment.jinja', 'app/routes/error_fragment.jinja', 1, 1, None, ('app/routes/route.py', 10, 29))),
        )
    except BaseException as error:
        if (
            isinstance(error, _DispatchError)
            and error.code == 'PYGANINI015'
            and error.phase == 'render-configuration'
        ):
            raise
        raise _middleware_construction_error(
            path='/settings/users',
            methods=('GET', 'HEAD'),
            chain=(('app/routes/settings/users/middleware.py', 5, 1, '/settings/users', ((6, 5),)),),
            consumers=(('GET', 'page', '/settings/users', ('GET', 'HEAD'), 'app/routes/settings/users/route.py', 1, 1, 'contact_directory', 'app/mounts/contact_directory/route.py', '/', (('app/routes/settings/users/middleware.py', 5, 1, '/settings/users', ((6, 5),)),)),),
        ) from error
    try:
        _generated_route_4 = _Route(
            '/settings/users/table',
            endpoint_4,
            methods=['GET', 'HEAD'],
            middleware=(*_middleware_0,),
            error_handler=selected_error_handler,
            error_layouts={'GET': (('app/routes/layout.py', 1, 1, '/', ('routes/layout.jinja', 'app/routes/layout.jinja', 1, 1, None, None)), ('app/routes/settings/users/layout.py', 1, 1, '/settings/users', ('routes/settings/users/layout.jinja', 'app/routes/settings/users/layout.jinja', 1, 1, None, None)), ('app/mounts/contact_directory/layout.py', 1, 1, '/', ('mounts/contact_directory/layout.jinja', 'app/mounts/contact_directory/layout.jinja', 1, 1, None, None)))},
            error_inspection={'GET': (('page', 'matched-error-page', '/settings/users/table', 'routes/error_page.jinja', 'app/routes/error_page.jinja:1:1', 'app/routes/route.py:9:25', 'app/routes/settings/users/route.py:1:1', 'route_error_handler', 'contact_directory:/'), ('fragment', 'matched-error-fragment', '/settings/users/table', 'routes/error_fragment.jinja', 'app/routes/error_fragment.jinja:1:1', 'app/routes/route.py:10:29', 'app/routes/settings/users/route.py:1:1', 'route_error_handler', 'contact_directory:/'), (('layout', 'matched-error-page', '/', 'routes/layout.jinja', 'app/routes/layout.jinja:1:1', 'none', 'app/routes/layout.py:1:1', 'none', 'none'), ('layout', 'matched-error-page', '/settings/users', 'routes/settings/users/layout.jinja', 'app/routes/settings/users/layout.jinja:1:1', 'none', 'app/routes/settings/users/layout.py:1:1', 'none', 'none'), ('layout', 'matched-error-page', '/settings/users', 'mounts/contact_directory/layout.jinja', 'app/mounts/contact_directory/layout.jinja:1:1', 'none', 'app/mounts/contact_directory/layout.py:1:1', 'none', 'contact_directory:/')))},
            error_evidence={'GET': ('fragment', '/settings/users/table', ('GET', 'HEAD'), 'app/mounts/contact_directory/route.py', 1, 1, 'app.mounts.contact_directory.handlers', 'table', 'table', 'app/routes/settings/users/route.py', 'contact_directory', '/', 1, 1, '/settings/users')},
            error_templates=(('routes/error_page.jinja', 'app/routes/error_page.jinja', 1, 1, None, ('app/routes/route.py', 9, 25)), ('routes/error_fragment.jinja', 'app/routes/error_fragment.jinja', 1, 1, None, ('app/routes/route.py', 10, 29))),
        )
    except BaseException as error:
        if (
            isinstance(error, _DispatchError)
            and error.code == 'PYGANINI015'
            and error.phase == 'render-configuration'
        ):
            raise
        raise _middleware_construction_error(
            path='/settings/users/table',
            methods=('GET', 'HEAD'),
            chain=(('app/routes/settings/users/middleware.py', 5, 1, '/settings/users', ((6, 5),)),),
            consumers=(('GET', 'fragment', '/settings/users/table', ('GET', 'HEAD'), 'app/routes/settings/users/route.py', 1, 1, 'contact_directory', 'app/mounts/contact_directory/route.py', '/', (('app/routes/settings/users/middleware.py', 5, 1, '/settings/users', ((6, 5),)),)),),
        ) from error
    try:
        _generated_route_5 = _Route(
            '/users',
            endpoint_5,
            methods=['GET', 'HEAD'],
            middleware=(*_middleware_1,),
            error_handler=selected_error_handler,
            error_layouts={'GET': (('app/routes/layout.py', 1, 1, '/', ('routes/layout.jinja', 'app/routes/layout.jinja', 1, 1, None, None)), ('app/routes/users/layout.py', 1, 1, '/users', ('routes/users/layout.jinja', 'app/routes/users/layout.jinja', 1, 1, None, None)), ('app/mounts/contact_directory/layout.py', 1, 1, '/', ('mounts/contact_directory/layout.jinja', 'app/mounts/contact_directory/layout.jinja', 1, 1, None, None)))},
            error_inspection={'GET': (('page', 'matched-error-page', '/users', 'routes/error_page.jinja', 'app/routes/error_page.jinja:1:1', 'app/routes/route.py:9:25', 'app/routes/users/route.py:1:1', 'route_error_handler', 'contact_directory:/'), ('fragment', 'matched-error-fragment', '/users', 'routes/error_fragment.jinja', 'app/routes/error_fragment.jinja:1:1', 'app/routes/route.py:10:29', 'app/routes/users/route.py:1:1', 'route_error_handler', 'contact_directory:/'), (('layout', 'matched-error-page', '/', 'routes/layout.jinja', 'app/routes/layout.jinja:1:1', 'none', 'app/routes/layout.py:1:1', 'none', 'none'), ('layout', 'matched-error-page', '/users', 'routes/users/layout.jinja', 'app/routes/users/layout.jinja:1:1', 'none', 'app/routes/users/layout.py:1:1', 'none', 'none'), ('layout', 'matched-error-page', '/users', 'mounts/contact_directory/layout.jinja', 'app/mounts/contact_directory/layout.jinja:1:1', 'none', 'app/mounts/contact_directory/layout.py:1:1', 'none', 'contact_directory:/')))},
            error_evidence={'GET': ('page', '/users', ('GET', 'HEAD'), 'app/mounts/contact_directory/route.py', 1, 1, 'app.mounts.contact_directory.handlers', 'page', 'page', 'app/routes/users/route.py', 'contact_directory', '/', 1, 1, '/users')},
            error_templates=(('routes/error_page.jinja', 'app/routes/error_page.jinja', 1, 1, None, ('app/routes/route.py', 9, 25)), ('routes/error_fragment.jinja', 'app/routes/error_fragment.jinja', 1, 1, None, ('app/routes/route.py', 10, 29))),
        )
    except BaseException as error:
        if (
            isinstance(error, _DispatchError)
            and error.code == 'PYGANINI015'
            and error.phase == 'render-configuration'
        ):
            raise
        raise _middleware_construction_error(
            path='/users',
            methods=('GET', 'HEAD'),
            chain=(('app/routes/users/middleware.py', 5, 1, '/users', ((6, 5),)),),
            consumers=(('GET', 'page', '/users', ('GET', 'HEAD'), 'app/routes/users/route.py', 1, 1, 'contact_directory', 'app/mounts/contact_directory/route.py', '/', (('app/routes/users/middleware.py', 5, 1, '/users', ((6, 5),)),)),),
        ) from error
    try:
        _generated_route_6 = _Route(
            '/users/table',
            endpoint_6,
            methods=['GET', 'HEAD'],
            middleware=(*_middleware_1,),
            error_handler=selected_error_handler,
            error_layouts={'GET': (('app/routes/layout.py', 1, 1, '/', ('routes/layout.jinja', 'app/routes/layout.jinja', 1, 1, None, None)), ('app/routes/users/layout.py', 1, 1, '/users', ('routes/users/layout.jinja', 'app/routes/users/layout.jinja', 1, 1, None, None)), ('app/mounts/contact_directory/layout.py', 1, 1, '/', ('mounts/contact_directory/layout.jinja', 'app/mounts/contact_directory/layout.jinja', 1, 1, None, None)))},
            error_inspection={'GET': (('page', 'matched-error-page', '/users/table', 'routes/error_page.jinja', 'app/routes/error_page.jinja:1:1', 'app/routes/route.py:9:25', 'app/routes/users/route.py:1:1', 'route_error_handler', 'contact_directory:/'), ('fragment', 'matched-error-fragment', '/users/table', 'routes/error_fragment.jinja', 'app/routes/error_fragment.jinja:1:1', 'app/routes/route.py:10:29', 'app/routes/users/route.py:1:1', 'route_error_handler', 'contact_directory:/'), (('layout', 'matched-error-page', '/', 'routes/layout.jinja', 'app/routes/layout.jinja:1:1', 'none', 'app/routes/layout.py:1:1', 'none', 'none'), ('layout', 'matched-error-page', '/users', 'routes/users/layout.jinja', 'app/routes/users/layout.jinja:1:1', 'none', 'app/routes/users/layout.py:1:1', 'none', 'none'), ('layout', 'matched-error-page', '/users', 'mounts/contact_directory/layout.jinja', 'app/mounts/contact_directory/layout.jinja:1:1', 'none', 'app/mounts/contact_directory/layout.py:1:1', 'none', 'contact_directory:/')))},
            error_evidence={'GET': ('fragment', '/users/table', ('GET', 'HEAD'), 'app/mounts/contact_directory/route.py', 1, 1, 'app.mounts.contact_directory.handlers', 'table', 'table', 'app/routes/users/route.py', 'contact_directory', '/', 1, 1, '/users')},
            error_templates=(('routes/error_page.jinja', 'app/routes/error_page.jinja', 1, 1, None, ('app/routes/route.py', 9, 25)), ('routes/error_fragment.jinja', 'app/routes/error_fragment.jinja', 1, 1, None, ('app/routes/route.py', 10, 29))),
        )
    except BaseException as error:
        if (
            isinstance(error, _DispatchError)
            and error.code == 'PYGANINI015'
            and error.phase == 'render-configuration'
        ):
            raise
        raise _middleware_construction_error(
            path='/users/table',
            methods=('GET', 'HEAD'),
            chain=(('app/routes/users/middleware.py', 5, 1, '/users', ((6, 5),)),),
            consumers=(('GET', 'fragment', '/users/table', ('GET', 'HEAD'), 'app/routes/users/route.py', 1, 1, 'contact_directory', 'app/mounts/contact_directory/route.py', '/', (('app/routes/users/middleware.py', 5, 1, '/users', ((6, 5),)),)),),
        ) from error
    try:
        _generated_route_7 = _Route(
            '/users/create',
            endpoint_7,
            methods=['POST'],
            middleware=(*_middleware_1,),
            error_handler=selected_error_handler,
            error_layouts={'POST': (('app/routes/layout.py', 1, 1, '/', ('routes/layout.jinja', 'app/routes/layout.jinja', 1, 1, None, None)), ('app/routes/users/layout.py', 1, 1, '/users', ('routes/users/layout.jinja', 'app/routes/users/layout.jinja', 1, 1, None, None)), ('app/mounts/contact_directory/layout.py', 1, 1, '/', ('mounts/contact_directory/layout.jinja', 'app/mounts/contact_directory/layout.jinja', 1, 1, None, None)))},
            error_inspection={'POST': (('page', 'matched-error-page', '/users/create', 'routes/error_page.jinja', 'app/routes/error_page.jinja:1:1', 'app/routes/route.py:9:25', 'app/routes/users/route.py:1:1', 'route_error_handler', 'contact_directory:/create'), ('fragment', 'matched-error-fragment', '/users/create', 'routes/error_fragment.jinja', 'app/routes/error_fragment.jinja:1:1', 'app/routes/route.py:10:29', 'app/routes/users/route.py:1:1', 'route_error_handler', 'contact_directory:/create'), (('layout', 'matched-error-page', '/', 'routes/layout.jinja', 'app/routes/layout.jinja:1:1', 'none', 'app/routes/layout.py:1:1', 'none', 'none'), ('layout', 'matched-error-page', '/users', 'routes/users/layout.jinja', 'app/routes/users/layout.jinja:1:1', 'none', 'app/routes/users/layout.py:1:1', 'none', 'none'), ('layout', 'matched-error-page', '/users', 'mounts/contact_directory/layout.jinja', 'app/mounts/contact_directory/layout.jinja:1:1', 'none', 'app/mounts/contact_directory/layout.py:1:1', 'none', 'contact_directory:/create')))},
            error_evidence={'POST': ('action', '/users/create', ('POST',), 'app/mounts/contact_directory/create/route.py', 1, 1, 'app.mounts.contact_directory.create.handlers', 'post_create', 'post_create', 'app/routes/users/route.py', 'contact_directory', '/create', 1, 1, '/users')},
            error_templates=(('routes/error_page.jinja', 'app/routes/error_page.jinja', 1, 1, None, ('app/routes/route.py', 9, 25)), ('routes/error_fragment.jinja', 'app/routes/error_fragment.jinja', 1, 1, None, ('app/routes/route.py', 10, 29))),
        )
    except BaseException as error:
        if (
            isinstance(error, _DispatchError)
            and error.code == 'PYGANINI015'
            and error.phase == 'render-configuration'
        ):
            raise
        raise _middleware_construction_error(
            path='/users/create',
            methods=('POST',),
            chain=(('app/routes/users/middleware.py', 5, 1, '/users', ((6, 5),)),),
            consumers=(('POST', 'action', '/users/create', ('POST',), 'app/routes/users/route.py', 1, 1, 'contact_directory', 'app/mounts/contact_directory/create/route.py', '/create', (('app/routes/users/middleware.py', 5, 1, '/users', ((6, 5),)),)),),
        ) from error
    try:
        _generated_route_8 = _Route(
            '/users/{id}',
            endpoint_8,
            methods=['GET', 'HEAD'],
            middleware=(*_middleware_1,),
            error_handler=selected_error_handler,
            error_layouts={'GET': (('app/routes/layout.py', 1, 1, '/', ('routes/layout.jinja', 'app/routes/layout.jinja', 1, 1, None, None)), ('app/routes/users/layout.py', 1, 1, '/users', ('routes/users/layout.jinja', 'app/routes/users/layout.jinja', 1, 1, None, None)), ('app/mounts/contact_directory/layout.py', 1, 1, '/', ('mounts/contact_directory/layout.jinja', 'app/mounts/contact_directory/layout.jinja', 1, 1, None, None)))},
            error_inspection={'GET': (('page', 'matched-error-page', '/users/{id}', 'routes/error_page.jinja', 'app/routes/error_page.jinja:1:1', 'app/routes/route.py:9:25', 'app/routes/users/route.py:1:1', 'route_error_handler', 'contact_directory:/{id}'), ('fragment', 'matched-error-fragment', '/users/{id}', 'routes/error_fragment.jinja', 'app/routes/error_fragment.jinja:1:1', 'app/routes/route.py:10:29', 'app/routes/users/route.py:1:1', 'route_error_handler', 'contact_directory:/{id}'), (('layout', 'matched-error-page', '/', 'routes/layout.jinja', 'app/routes/layout.jinja:1:1', 'none', 'app/routes/layout.py:1:1', 'none', 'none'), ('layout', 'matched-error-page', '/users', 'routes/users/layout.jinja', 'app/routes/users/layout.jinja:1:1', 'none', 'app/routes/users/layout.py:1:1', 'none', 'none'), ('layout', 'matched-error-page', '/users', 'mounts/contact_directory/layout.jinja', 'app/mounts/contact_directory/layout.jinja:1:1', 'none', 'app/mounts/contact_directory/layout.py:1:1', 'none', 'contact_directory:/{id}')))},
            error_evidence={'GET': ('page', '/users/{id}', ('GET', 'HEAD'), 'app/mounts/contact_directory/by_id/route.py', 1, 1, 'app.mounts.contact_directory.by_id.handlers', 'page', 'page', 'app/routes/users/route.py', 'contact_directory', '/{id}', 1, 1, '/users')},
            error_templates=(('routes/error_page.jinja', 'app/routes/error_page.jinja', 1, 1, None, ('app/routes/route.py', 9, 25)), ('routes/error_fragment.jinja', 'app/routes/error_fragment.jinja', 1, 1, None, ('app/routes/route.py', 10, 29))),
        )
    except BaseException as error:
        if (
            isinstance(error, _DispatchError)
            and error.code == 'PYGANINI015'
            and error.phase == 'render-configuration'
        ):
            raise
        raise _middleware_construction_error(
            path='/users/{id}',
            methods=('GET', 'HEAD'),
            chain=(('app/routes/users/middleware.py', 5, 1, '/users', ((6, 5),)),),
            consumers=(('GET', 'page', '/users/{id}', ('GET', 'HEAD'), 'app/routes/users/route.py', 1, 1, 'contact_directory', 'app/mounts/contact_directory/by_id/route.py', '/{id}', (('app/routes/users/middleware.py', 5, 1, '/users', ((6, 5),)),)),),
        ) from error
    _generated_routes: list[_Route] = [
            _Route(
                '/',
                endpoint_0,
                methods=['GET', 'HEAD'],
                error_handler=selected_error_handler,
                error_layouts={'GET': (('app/routes/layout.py', 1, 1, '/', ('routes/layout.jinja', 'app/routes/layout.jinja', 1, 1, None, None)),)},
                error_inspection={'GET': (('page', 'matched-error-page', '/', 'routes/error_page.jinja', 'app/routes/error_page.jinja:1:1', 'app/routes/route.py:9:25', 'app/routes/route.py:1:1', 'route_error_handler', 'none'), ('fragment', 'matched-error-fragment', '/', 'routes/error_fragment.jinja', 'app/routes/error_fragment.jinja:1:1', 'app/routes/route.py:10:29', 'app/routes/route.py:1:1', 'route_error_handler', 'none'), (('layout', 'matched-error-page', '/', 'routes/layout.jinja', 'app/routes/layout.jinja:1:1', 'none', 'app/routes/layout.py:1:1', 'none', 'none'),))},
                error_evidence={'GET': ('page', '/', ('GET', 'HEAD'), 'app/routes/route.py', 1, 1, 'app.routes.handlers', 'page', 'page', 'app/routes/route.py', None, None, 1, 1, '/')},
                error_templates=(('routes/error_page.jinja', 'app/routes/error_page.jinja', 1, 1, None, ('app/routes/route.py', 9, 25)), ('routes/error_fragment.jinja', 'app/routes/error_fragment.jinja', 1, 1, None, ('app/routes/route.py', 10, 29))),
            ),
            _Route(
                '/problem',
                endpoint_1,
                methods=['GET', 'HEAD'],
                error_handler=selected_error_handler,
                error_layouts={'GET': (('app/routes/layout.py', 1, 1, '/', ('routes/layout.jinja', 'app/routes/layout.jinja', 1, 1, None, None)),)},
                error_inspection={'GET': (('page', 'matched-error-page', '/problem', 'routes/error_page.jinja', 'app/routes/error_page.jinja:1:1', 'app/routes/route.py:9:25', 'app/routes/problem/route.py:1:1', 'route_error_handler', 'none'), ('fragment', 'matched-error-fragment', '/problem', 'routes/error_fragment.jinja', 'app/routes/error_fragment.jinja:1:1', 'app/routes/route.py:10:29', 'app/routes/problem/route.py:1:1', 'route_error_handler', 'none'), (('layout', 'matched-error-page', '/', 'routes/layout.jinja', 'app/routes/layout.jinja:1:1', 'none', 'app/routes/layout.py:1:1', 'none', 'none'),))},
                error_evidence={'GET': ('page', '/problem', ('GET', 'HEAD'), 'app/routes/problem/route.py', 1, 1, 'app.routes.problem.handlers', 'page', 'page', 'app/routes/problem/route.py', None, None, 1, 1, '/problem')},
                error_templates=(('routes/error_page.jinja', 'app/routes/error_page.jinja', 1, 1, None, ('app/routes/route.py', 9, 25)), ('routes/error_fragment.jinja', 'app/routes/error_fragment.jinja', 1, 1, None, ('app/routes/route.py', 10, 29))),
            ),
            _Route(
                '/settings',
                endpoint_2,
                methods=['GET', 'HEAD'],
                error_handler=selected_error_handler,
                error_layouts={'GET': (('app/routes/layout.py', 1, 1, '/', ('routes/layout.jinja', 'app/routes/layout.jinja', 1, 1, None, None)),)},
                error_inspection={'GET': (('page', 'matched-error-page', '/settings', 'routes/error_page.jinja', 'app/routes/error_page.jinja:1:1', 'app/routes/route.py:9:25', 'app/routes/settings/route.py:1:1', 'route_error_handler', 'none'), ('fragment', 'matched-error-fragment', '/settings', 'routes/error_fragment.jinja', 'app/routes/error_fragment.jinja:1:1', 'app/routes/route.py:10:29', 'app/routes/settings/route.py:1:1', 'route_error_handler', 'none'), (('layout', 'matched-error-page', '/', 'routes/layout.jinja', 'app/routes/layout.jinja:1:1', 'none', 'app/routes/layout.py:1:1', 'none', 'none'),))},
                error_evidence={'GET': ('page', '/settings', ('GET', 'HEAD'), 'app/routes/settings/route.py', 1, 1, 'app.routes.settings.handlers', 'page', 'page', 'app/routes/settings/route.py', None, None, 1, 1, '/settings')},
                error_templates=(('routes/error_page.jinja', 'app/routes/error_page.jinja', 1, 1, None, ('app/routes/route.py', 9, 25)), ('routes/error_fragment.jinja', 'app/routes/error_fragment.jinja', 1, 1, None, ('app/routes/route.py', 10, 29))),
            ),
            _generated_route_3,
            _generated_route_4,
            _generated_route_5,
            _generated_route_6,
            _generated_route_7,
            _generated_route_8,
    ]
    if selected_error_handler is None:
        return _Router(
            routes=_generated_routes,
            redirect_slashes=False,
        )
    return _ErrorRouter(
        routes=_generated_routes,
        redirect_slashes=False,
        error_handler=selected_error_handler,
    )


router: _Router = create_router()
