# Code generated by pyganini; DO NOT EDIT.
# pyright: reportPrivateUsage=false, reportUnusedClass=false
"""Generated Pyganini URL helper interface."""

from __future__ import annotations

from dataclasses import dataclass as _dataclass
from typing import overload as _overload
from urllib.parse import quote as _quote

from pyganini import Navigation as _Navigation
from pyganini._navigation import _navigation_href
from pyganini._url_binding import quote_segment as _quote_segment

__all__ = ("mount_urls", "urls")

def _normalize_base_path(base_path: object) -> str:
    if not isinstance(base_path, str):
        raise TypeError("base_path must be str")
    if base_path in {"", "/"}:
        return ""
    if all(character == "/" for character in base_path):
        raise ValueError("base_path must not contain empty path segments")
    normalized = base_path if base_path.startswith("/") else "/" + base_path
    normalized = normalized.rstrip("/")
    segments = normalized[1:].split("/")
    if any(segment == "" for segment in segments):
        raise ValueError("base_path must not contain empty path segments")
    quoted = tuple(
        _quote_segment(f"base_path segment {index}", segment)
        for index, segment in enumerate(segments, start=1)
    )
    return "/" + "/".join(quoted)

def _add_trail_key(path: str, key: str) -> str:
    return path + ("&" if "?" in path else "?") + "_pyganini_nav_trail_key=" + _quote(key, safe="")

@_dataclass(frozen=True, slots=True)
class _URLRootPath:
    _base_path: str
    _owner_key: str | None

    @property
    def path(self) -> str:
        return self._base_path + "/"

    @property
    def route_pattern(self) -> str:
        return "/"


@_dataclass(frozen=True, slots=True)
class _URLNode0:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/'

    def with_base_path(self, base_path: str) -> _URLNode0:
        """Return this surface bound to a decoded path prefix."""
        return _URLNode0(_normalize_base_path(base_path), "", self._owner_key)

    @property
    def root(self) -> _URLRootPath:
        return _URLRootPath(self._base_path, self._owner_key)

    @property
    def problem(self) -> _URLNode1:
        return _URLNode1(
            self._base_path,
            self._local_path + '/problem',
            None,
        )

    @property
    def settings(self) -> _URLNode2:
        return _URLNode2(
            self._base_path,
            self._local_path + '/settings',
            None,
        )

    @property
    def users(self) -> _URLNode5:
        return _URLNode5(
            self._base_path,
            self._local_path + '/users',
            'app/routes/users/route.py',
        )


@_dataclass(frozen=True, slots=True)
class _URLNode1:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/problem'

    @property
    def path(self) -> str:
        return self._base_path + self._local_path


@_dataclass(frozen=True, slots=True)
class _URLNode2:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/settings'

    @property
    def path(self) -> str:
        return self._base_path + self._local_path

    @property
    def users(self) -> _URLNode3:
        return _URLNode3(
            self._base_path,
            self._local_path + '/users',
            'app/routes/settings/users/route.py',
        )


@_dataclass(frozen=True, slots=True)
class _URLNode3:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/settings/users'

    @property
    def path(self) -> str:
        return self._base_path + self._local_path

    @property
    def table(self) -> _URLNode4:
        return _URLNode4(
            self._base_path,
            self._local_path + '/table',
            None,
        )


@_dataclass(frozen=True, slots=True)
class _URLNode4:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/settings/users/table'

    @property
    def path(self) -> str:
        return self._base_path + self._local_path


@_dataclass(frozen=True, slots=True)
class _URLNode5:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/users'

    @property
    def path(self) -> str:
        return self._base_path + self._local_path

    @property
    def destinations(self) -> _Destinations5:
        return _Destinations5(self._base_path)

    @property
    def create(self) -> _URLNode6:
        return _URLNode6(
            self._base_path,
            self._local_path + '/create',
            None,
        )

    @property
    def table(self) -> _URLNode7:
        return _URLNode7(
            self._base_path,
            self._local_path + '/table',
            None,
        )

    @property
    def by_id(self) -> _URLTarget8:
        return _URLTarget8(
            self._base_path,
            self._local_path,
            None,
        )


@_dataclass(frozen=True, slots=True)
class _URLNode6:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/users/create'

    @property
    def path(self) -> str:
        return self._base_path + self._local_path


@_dataclass(frozen=True, slots=True)
class _URLNode7:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/users/table'

    @property
    def path(self) -> str:
        return self._base_path + self._local_path


@_dataclass(frozen=True, slots=True)
class _URLNode8:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/users/{id}'

    @property
    def path(self) -> str:
        return self._base_path + self._local_path

    @property
    def trail_keys(self) -> _TrailKeys8:
        return _TrailKeys8()


@_dataclass(frozen=True, slots=True)
class _URLTarget0:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/'

    @property
    def problem(self) -> _URLUnboundTarget1:
        return _URLUnboundTarget1(
            self._base_path,
            self._local_path + '/problem',
            None,
        )

    @property
    def settings(self) -> _URLUnboundTarget2:
        return _URLUnboundTarget2(
            self._base_path,
            self._local_path + '/settings',
            None,
        )

    @property
    def users(self) -> _URLUnboundTarget5:
        return _URLUnboundTarget5(
            self._base_path,
            self._local_path + '/users',
            'app/routes/users/route.py',
        )


@_dataclass(frozen=True, slots=True)
class _URLTarget1:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/problem'
    pass


@_dataclass(frozen=True, slots=True)
class _URLTarget2:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/settings'

    @property
    def users(self) -> _URLUnboundTarget3:
        return _URLUnboundTarget3(
            self._base_path,
            self._local_path + '/users',
            'app/routes/settings/users/route.py',
        )


@_dataclass(frozen=True, slots=True)
class _URLTarget3:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/settings/users'

    @property
    def table(self) -> _URLUnboundTarget4:
        return _URLUnboundTarget4(
            self._base_path,
            self._local_path + '/table',
            None,
        )


@_dataclass(frozen=True, slots=True)
class _URLTarget4:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/settings/users/table'
    pass


@_dataclass(frozen=True, slots=True)
class _URLTarget5:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/users'

    @property
    def create(self) -> _URLUnboundTarget6:
        return _URLUnboundTarget6(
            self._base_path,
            self._local_path + '/create',
            None,
        )

    @property
    def table(self) -> _URLUnboundTarget7:
        return _URLUnboundTarget7(
            self._base_path,
            self._local_path + '/table',
            None,
        )

    @property
    def by_id(self) -> _URLUnboundTarget8:
        return _URLUnboundTarget8(
            self._base_path,
            self._local_path,
            None,
        )


@_dataclass(frozen=True, slots=True)
class _URLTarget6:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/users/create'
    pass


@_dataclass(frozen=True, slots=True)
class _URLTarget7:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/users/table'
    pass


@_dataclass(frozen=True, slots=True)
class _URLTarget8:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/users/{id}'

    def __call__(self, id: str) -> _URLNode8:
        encoded = _quote_segment("parameter 'id'", id)
        return _URLNode8(
            self._base_path,
            self._local_path + "/" + encoded,
            self._owner_key,
        )

    @property
    def trail_keys(self) -> _TrailKeys8:
        return _TrailKeys8()


@_dataclass(frozen=True, slots=True)
class _URLUnboundTarget0:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/'

    @property
    def problem(self) -> _URLUnboundTarget1:
        return _URLUnboundTarget1(
            self._base_path,
            self._local_path + '/problem',
            None,
        )

    @property
    def settings(self) -> _URLUnboundTarget2:
        return _URLUnboundTarget2(
            self._base_path,
            self._local_path + '/settings',
            None,
        )

    @property
    def users(self) -> _URLUnboundTarget5:
        return _URLUnboundTarget5(
            self._base_path,
            self._local_path + '/users',
            'app/routes/users/route.py',
        )


@_dataclass(frozen=True, slots=True)
class _URLUnboundTarget1:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/problem'


@_dataclass(frozen=True, slots=True)
class _URLUnboundTarget2:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/settings'

    @property
    def users(self) -> _URLUnboundTarget3:
        return _URLUnboundTarget3(
            self._base_path,
            self._local_path + '/users',
            'app/routes/settings/users/route.py',
        )


@_dataclass(frozen=True, slots=True)
class _URLUnboundTarget3:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/settings/users'

    @property
    def table(self) -> _URLUnboundTarget4:
        return _URLUnboundTarget4(
            self._base_path,
            self._local_path + '/table',
            None,
        )


@_dataclass(frozen=True, slots=True)
class _URLUnboundTarget4:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/settings/users/table'


@_dataclass(frozen=True, slots=True)
class _URLUnboundTarget5:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/users'

    @property
    def create(self) -> _URLUnboundTarget6:
        return _URLUnboundTarget6(
            self._base_path,
            self._local_path + '/create',
            None,
        )

    @property
    def table(self) -> _URLUnboundTarget7:
        return _URLUnboundTarget7(
            self._base_path,
            self._local_path + '/table',
            None,
        )

    @property
    def by_id(self) -> _URLUnboundTarget8:
        return _URLUnboundTarget8(
            self._base_path,
            self._local_path,
            None,
        )


@_dataclass(frozen=True, slots=True)
class _URLUnboundTarget6:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/users/create'


@_dataclass(frozen=True, slots=True)
class _URLUnboundTarget7:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/users/table'


@_dataclass(frozen=True, slots=True)
class _URLUnboundTarget8:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/users/{id}'

    @property
    def trail_keys(self) -> _TrailKeys8:
        return _TrailKeys8()


@_dataclass(frozen=True, slots=True)
class _Destination0:
    href: str

    def navigation_href(self, navigation: _Navigation) -> str:
        return _navigation_href(navigation, self.href)


@_dataclass(frozen=True, slots=True)
class _Destinations5:
    _base_path: str

    def contact_detail(self, id: str) -> _Destination0:
        return _Destination0(
            _add_trail_key(self._base_path + "/users" + "/" + _quote_segment("parameter id", id), 'from-contacts'),
        )


@_dataclass(frozen=True, slots=True)
class _TrailKeys8:

    from_contacts: str = 'from-contacts'


urls: _URLNode0 = _URLNode0("", "", None)


@_dataclass(frozen=True, slots=True)
class _MountBound0Node0:
    _base_path: str
    _local_path: str

    @property
    def path(self) -> str:
        return self._base_path + (self._local_path or '/')

    @property
    def table(self) -> _MountBound0Node1:
        return _MountBound0Node1(
            self._base_path,
            self._local_path + '/table',
        )


@_dataclass(frozen=True, slots=True)
class _MountBound0Node1:
    _base_path: str
    _local_path: str

    @property
    def path(self) -> str:
        return self._base_path + (self._local_path or '/')


@_dataclass(frozen=True, slots=True)
class _MountBound1Node0:
    _base_path: str
    _local_path: str

    @property
    def path(self) -> str:
        return self._base_path + (self._local_path or '/')

    @property
    def create(self) -> _MountBound1Node1:
        return _MountBound1Node1(
            self._base_path,
            self._local_path + '/create',
        )

    @property
    def table(self) -> _MountBound1Node2:
        return _MountBound1Node2(
            self._base_path,
            self._local_path + '/table',
        )

    def by_id(self, id: str) -> _MountBound1Node3:
        encoded = _quote_segment("parameter 'id'", id)
        return _MountBound1Node3(
            self._base_path,
            self._local_path + "/" + encoded,
        )


@_dataclass(frozen=True, slots=True)
class _MountBound1Node1:
    _base_path: str
    _local_path: str

    @property
    def path(self) -> str:
        return self._base_path + (self._local_path or '/')


@_dataclass(frozen=True, slots=True)
class _MountBound1Node2:
    _base_path: str
    _local_path: str

    @property
    def path(self) -> str:
        return self._base_path + (self._local_path or '/')


@_dataclass(frozen=True, slots=True)
class _MountBound1Node3:
    _base_path: str
    _local_path: str

    @property
    def path(self) -> str:
        return self._base_path + (self._local_path or '/')


@_dataclass(frozen=True, slots=True)
class _MountCatalogRoot_0:

    @_overload
    def bind(self, owner: _URLNode3) -> _MountBound0Node0:
        ...

    @_overload
    def bind(self, owner: _URLNode5) -> _MountBound1Node0:
        ...

    def bind(self, owner: object) -> object:
        owner_key = getattr(owner, '_owner_key', None)
        if owner_key == 'app/routes/settings/users/route.py':
            base_path = getattr(owner, '_base_path', None)
            local_path = getattr(owner, '_local_path', None)
            if not isinstance(base_path, str) or not isinstance(
                local_path, str
            ):
                raise ValueError(
                    'owner is not a generated live URL node for mount contact_directory'
                )
            return _MountBound0Node0(base_path, local_path)
        if owner_key == 'app/routes/users/route.py':
            base_path = getattr(owner, '_base_path', None)
            local_path = getattr(owner, '_local_path', None)
            if not isinstance(base_path, str) or not isinstance(
                local_path, str
            ):
                raise ValueError(
                    'owner is not a generated live URL node for mount contact_directory'
                )
            return _MountBound1Node0(base_path, local_path)
        raise ValueError(
            'owner is not a live owner of mount contact_directory'
        )


@_dataclass(frozen=True, slots=True)
class _MountCatalogRoot:

    @property
    def contact_directory(self) -> _MountCatalogRoot_0:
        return _MountCatalogRoot_0()


mount_urls: _MountCatalogRoot = _MountCatalogRoot()
