# Code generated by pyganini; DO NOT EDIT.
"""Generated Pyganini ASGI routing surface."""

from jinja2 import Environment as _Environment
from starlette.routing import Router as _Router
from typing import TYPE_CHECKING as _TYPE_CHECKING

from pyganini import KitRouteDef as _KitRouteDef
from pyganini import KitRouteMount as _KitRouteMount
from pyganini import RouteErrorHandler as _RouteErrorHandler
from pyganini import TemplateInspectionMode as _TemplateInspectionMode
from pyganini._dispatch import build_endpoint as _build_endpoint
from pyganini._dispatch import load_route as _load_route
from pyganini._dispatch import load_mount_owner as _load_mount_owner
from pyganini._dispatch import PathPriorityRoute as _Route
from pyganini._dispatch import RouteErrorRouter as _ErrorRouter
from pyganini._dispatch import prepare_environment as _prepare_environment
from pyganini._dispatch import prepare_route_error_handler as _prepare_route_error_handler
from pyganini._dispatch import prepare_template_inspection as _prepare_template_inspection
from pyganini._dispatch import select_creator as _select_creator
from pyganini._dispatch import select_handler as _select_handler

_template_names = ('mounts/analytics/customers/by_customer_id/report/page.jinja', 'mounts/analytics/page.jinja', 'mounts/customer_report/brief/page.jinja', 'mounts/customer_report/detailed/page.jinja', 'mounts/customer_report/layout.jinja', 'mounts/customer_report/page.jinja', 'routes/about/page.jinja', 'routes/layout.jinja', 'routes/main/hq/page.jinja', 'routes/main/hq/teams/by_team_id/customers/by_customer_id/page.jinja', 'routes/main/hq/teams/by_team_id/page.jinja', 'routes/main/page.jinja', 'routes/main/regional/offices/by_office_id/page.jinja', 'routes/main/regional/offices/by_office_id/teams/by_team_id/customers/by_customer_id/page.jinja', 'routes/main/regional/offices/by_office_id/teams/by_team_id/page.jinja', 'routes/main/regional/page.jinja', 'routes/main/reports/by_customer_id/page.jinja', 'routes/page.jinja')

_route_0 = _load_route(
    module='app.routes.about.route',
    source_path='app/routes/about/route.py',
    expected=(
        ('page', 'GET', '/', '/about', ('GET', 'HEAD'), 'app.routes.about.route', 'page', 'page', 'app/routes/about/route.py', 18, 20, 'page.jinja', 'app/routes/about/route.py', None, None, None, None),
    ),
    expected_creator=None,
    expected_template_root=None,
    expected_nav=('About', None),
    expected_destinations=(),
)

_route_1 = _load_route(
    module='app.routes.main.hq.route',
    source_path='app/routes/main/hq/route.py',
    expected=(
        ('page', 'GET', '/', '/main/hq', ('GET', 'HEAD'), 'app.routes.main.hq.route', 'page', 'page', 'app/routes/main/hq/route.py', 20, 20, 'page.jinja', 'app/routes/main/hq/route.py', None, None, None, None),
    ),
    expected_creator=None,
    expected_template_root=None,
    expected_nav=('HQ', None),
    expected_destinations=(),
)

_route_2 = _load_mount_owner(
    module='app.routes.main.hq.teams.by_team_id.analytics.route',
    source_path='app/routes/main/hq/teams/by_team_id/analytics/route.py',
    expected_creator=('app.routes.main.hq.teams.by_team_id.analytics.route', 'create_hq_analytics', 'create_hq_analytics', 'app/routes/main/hq/teams/by_team_id/analytics/route.py', 98, 12),
    expected_mount='analytics',
    expected_routes=('/', '/customers/{customer_id}/report'),
    expected_bindings=(('/', 'app/mounts/analytics/route.py', '/main/hq/teams/{team_id}/analytics'), ('/customers/{customer_id}/report', 'app/mounts/analytics/customers/by_customer_id/report/route.py', '/main/hq/teams/{team_id}/analytics/customers/{customer_id}/report')),
    expected_selections=(('/', None, (('customer-report', '/main/hq/teams/{team_id}/analytics/customers/{customer_id}/report', 'hq-analytics'),)), ('/customers/{customer_id}/report', None, ())),
)

_source_0 = _load_route(
    module='app.mounts.analytics.customers.by_customer_id.report.route',
    source_path='app/mounts/analytics/customers/by_customer_id/report/route.py',
    expected=(
        ('page', 'GET', '/', '/main/hq/teams/{team_id}/analytics/customers/{customer_id}/report', ('GET', 'HEAD'), 'app.mounts.analytics.customers.by_customer_id.report.handlers', 'page', 'page', 'app/mounts/analytics/customers/by_customer_id/report/route.py', 6, 10, 'page.jinja', 'app/routes/main/hq/teams/by_team_id/analytics/route.py', 'analytics', '/customers/{customer_id}/report', None, None),
    ),
    expected_creator=None,
    expected_template_root=None,
    expected_nav=('Report', None),
    expected_destinations=(),
    expected_kit=True,
)

_source_1 = _load_route(
    module='app.mounts.analytics.route',
    source_path='app/mounts/analytics/route.py',
    expected=(
        ('page', 'GET', '/', '/main/hq/teams/{team_id}/analytics', ('GET', 'HEAD'), 'app.mounts.analytics.handlers', 'page', 'page', 'app/mounts/analytics/route.py', 6, 10, 'page.jinja', 'app/routes/main/hq/teams/by_team_id/analytics/route.py', 'analytics', '/', None, None),
    ),
    expected_creator=None,
    expected_template_root=None,
    expected_nav=('Analytics', None),
    expected_destinations=(),
    expected_kit=True,
)

_route_3 = _load_mount_owner(
    module='app.routes.main.hq.teams.by_team_id.customers.by_customer_id.report.route',
    source_path='app/routes/main/hq/teams/by_team_id/customers/by_customer_id/report/route.py',
    expected_creator=('app.routes.main.hq.teams.by_team_id.customers.by_customer_id.report.route', 'create_hq_customer_report', 'create_hq_customer_report', 'app/routes/main/hq/teams/by_team_id/customers/by_customer_id/report/route.py', 42, 12),
    expected_mount='customer_report',
    expected_routes=None,
    expected_bindings=(('/', 'app/mounts/customer_report/route.py', '/main/hq/teams/{team_id}/customers/{customer_id}/report'), ('/brief', 'app/mounts/customer_report/brief/route.py', '/main/hq/teams/{team_id}/customers/{customer_id}/report/brief'), ('/detailed', 'app/mounts/customer_report/detailed/route.py', '/main/hq/teams/{team_id}/customers/{customer_id}/report/detailed')),
    expected_selections=(),
)

_source_2 = _load_route(
    module='app.mounts.customer_report.brief.route',
    source_path='app/mounts/customer_report/brief/route.py',
    expected=(
        ('page', 'GET', '/', '/main/hq/teams/{team_id}/customers/{customer_id}/report/brief', ('GET', 'HEAD'), 'app.mounts.customer_report.handlers', 'brief', 'brief', 'app/mounts/customer_report/brief/route.py', 6, 10, 'page.jinja', 'app/routes/main/hq/teams/by_team_id/customers/by_customer_id/report/route.py', 'customer_report', '/brief', None, None),
    ),
    expected_creator=None,
    expected_template_root=None,
    expected_nav=('Brief', None),
    expected_destinations=(),
    expected_kit=True,
)

_source_3 = _load_route(
    module='app.mounts.customer_report.detailed.route',
    source_path='app/mounts/customer_report/detailed/route.py',
    expected=(
        ('page', 'GET', '/', '/main/hq/teams/{team_id}/customers/{customer_id}/report/detailed', ('GET', 'HEAD'), 'app.mounts.customer_report.handlers', 'detailed', 'detailed', 'app/mounts/customer_report/detailed/route.py', 6, 10, 'page.jinja', 'app/routes/main/hq/teams/by_team_id/customers/by_customer_id/report/route.py', 'customer_report', '/detailed', None, None),
    ),
    expected_creator=None,
    expected_template_root=None,
    expected_nav=('Detailed', None),
    expected_destinations=(),
    expected_kit=True,
)

_source_4 = _load_route(
    module='app.mounts.customer_report.route',
    source_path='app/mounts/customer_report/route.py',
    expected=(
        ('page', 'GET', '/', '/main/hq/teams/{team_id}/customers/{customer_id}/report', ('GET', 'HEAD'), 'app.mounts.customer_report.handlers', 'page', 'page', 'app/mounts/customer_report/route.py', 6, 10, 'page.jinja', 'app/routes/main/hq/teams/by_team_id/customers/by_customer_id/report/route.py', 'customer_report', '/', None, None),
    ),
    expected_creator=None,
    expected_template_root=None,
    expected_nav=('Report', None),
    expected_destinations=(),
    expected_kit=True,
)

_route_4 = _load_route(
    module='app.routes.main.hq.teams.by_team_id.customers.by_customer_id.route',
    source_path='app/routes/main/hq/teams/by_team_id/customers/by_customer_id/route.py',
    expected=(
        ('page', 'GET', '/', '/main/hq/teams/{team_id}/customers/{customer_id}', ('GET', 'HEAD'), 'app.routes.main.hq.teams.by_team_id.customers.by_customer_id.route', 'page', 'page', 'app/routes/main/hq/teams/by_team_id/customers/by_customer_id/route.py', 46, 10, 'page.jinja', 'app/routes/main/hq/teams/by_team_id/customers/by_customer_id/route.py', None, None, None, None),
    ),
    expected_creator=None,
    expected_template_root=None,
    expected_nav=(None, 'customer'),
    expected_destinations=(('shared-report', '/main/reports/{customer_id}', 'hq-customer'),),
)

_route_5 = _load_route(
    module='app.routes.main.hq.teams.by_team_id.route',
    source_path='app/routes/main/hq/teams/by_team_id/route.py',
    expected=(
        ('page', 'GET', '/', '/main/hq/teams/{team_id}', ('GET', 'HEAD'), 'app.routes.main.hq.teams.by_team_id.route', 'page', 'page', 'app/routes/main/hq/teams/by_team_id/route.py', 31, 20, 'page.jinja', 'app/routes/main/hq/teams/by_team_id/route.py', None, None, None, None),
    ),
    expected_creator=None,
    expected_template_root=None,
    expected_nav=(None, 'team'),
    expected_destinations=(),
)

_route_6 = _load_route(
    module='app.routes.main.regional.offices.by_office_id.route',
    source_path='app/routes/main/regional/offices/by_office_id/route.py',
    expected=(
        ('page', 'GET', '/', '/main/regional/offices/{office_id}', ('GET', 'HEAD'), 'app.routes.main.regional.offices.by_office_id.route', 'page', 'page', 'app/routes/main/regional/offices/by_office_id/route.py', 30, 20, 'page.jinja', 'app/routes/main/regional/offices/by_office_id/route.py', None, None, None, None),
    ),
    expected_creator=None,
    expected_template_root=None,
    expected_nav=(None, 'office'),
    expected_destinations=(),
)

_route_7 = _load_mount_owner(
    module='app.routes.main.regional.offices.by_office_id.teams.by_team_id.analytics.route',
    source_path='app/routes/main/regional/offices/by_office_id/teams/by_team_id/analytics/route.py',
    expected_creator=('app.routes.main.regional.offices.by_office_id.teams.by_team_id.analytics.route', 'create_regional_analytics', 'create_regional_analytics', 'app/routes/main/regional/offices/by_office_id/teams/by_team_id/analytics/route.py', 112, 12),
    expected_mount='analytics',
    expected_routes=('/', '/customers/{customer_id}/report'),
    expected_bindings=(('/', 'app/mounts/analytics/route.py', '/main/regional/offices/{office_id}/teams/{team_id}/analytics'), ('/customers/{customer_id}/report', 'app/mounts/analytics/customers/by_customer_id/report/route.py', '/main/regional/offices/{office_id}/teams/{team_id}/analytics/customers/{customer_id}/report')),
    expected_selections=(('/', None, (('customer-report', '/main/regional/offices/{office_id}/teams/{team_id}/analytics/customers/{customer_id}/report', 'regional-analytics'),)), ('/customers/{customer_id}/report', None, ())),
)

_source_5 = _load_route(
    module='app.mounts.analytics.customers.by_customer_id.report.route',
    source_path='app/mounts/analytics/customers/by_customer_id/report/route.py',
    expected=(
        ('page', 'GET', '/', '/main/regional/offices/{office_id}/teams/{team_id}/analytics/customers/{customer_id}/report', ('GET', 'HEAD'), 'app.mounts.analytics.customers.by_customer_id.report.handlers', 'page', 'page', 'app/mounts/analytics/customers/by_customer_id/report/route.py', 6, 10, 'page.jinja', 'app/routes/main/regional/offices/by_office_id/teams/by_team_id/analytics/route.py', 'analytics', '/customers/{customer_id}/report', None, None),
    ),
    expected_creator=None,
    expected_template_root=None,
    expected_nav=('Report', None),
    expected_destinations=(),
    expected_kit=True,
)

_source_6 = _load_route(
    module='app.mounts.analytics.route',
    source_path='app/mounts/analytics/route.py',
    expected=(
        ('page', 'GET', '/', '/main/regional/offices/{office_id}/teams/{team_id}/analytics', ('GET', 'HEAD'), 'app.mounts.analytics.handlers', 'page', 'page', 'app/mounts/analytics/route.py', 6, 10, 'page.jinja', 'app/routes/main/regional/offices/by_office_id/teams/by_team_id/analytics/route.py', 'analytics', '/', None, None),
    ),
    expected_creator=None,
    expected_template_root=None,
    expected_nav=('Analytics', None),
    expected_destinations=(),
    expected_kit=True,
)

_route_8 = _load_mount_owner(
    module='app.routes.main.regional.offices.by_office_id.teams.by_team_id.customers.by_customer_id.report.route',
    source_path='app/routes/main/regional/offices/by_office_id/teams/by_team_id/customers/by_customer_id/report/route.py',
    expected_creator=('app.routes.main.regional.offices.by_office_id.teams.by_team_id.customers.by_customer_id.report.route', 'create_regional_customer_report', 'create_regional_customer_report', 'app/routes/main/regional/offices/by_office_id/teams/by_team_id/customers/by_customer_id/report/route.py', 54, 12),
    expected_mount='customer_report',
    expected_routes=None,
    expected_bindings=(('/', 'app/mounts/customer_report/route.py', '/main/regional/offices/{office_id}/teams/{team_id}/customers/{customer_id}/report'), ('/brief', 'app/mounts/customer_report/brief/route.py', '/main/regional/offices/{office_id}/teams/{team_id}/customers/{customer_id}/report/brief'), ('/detailed', 'app/mounts/customer_report/detailed/route.py', '/main/regional/offices/{office_id}/teams/{team_id}/customers/{customer_id}/report/detailed')),
    expected_selections=(),
)

_source_7 = _load_route(
    module='app.mounts.customer_report.brief.route',
    source_path='app/mounts/customer_report/brief/route.py',
    expected=(
        ('page', 'GET', '/', '/main/regional/offices/{office_id}/teams/{team_id}/customers/{customer_id}/report/brief', ('GET', 'HEAD'), 'app.mounts.customer_report.handlers', 'brief', 'brief', 'app/mounts/customer_report/brief/route.py', 6, 10, 'page.jinja', 'app/routes/main/regional/offices/by_office_id/teams/by_team_id/customers/by_customer_id/report/route.py', 'customer_report', '/brief', None, None),
    ),
    expected_creator=None,
    expected_template_root=None,
    expected_nav=('Brief', None),
    expected_destinations=(),
    expected_kit=True,
)

_source_8 = _load_route(
    module='app.mounts.customer_report.detailed.route',
    source_path='app/mounts/customer_report/detailed/route.py',
    expected=(
        ('page', 'GET', '/', '/main/regional/offices/{office_id}/teams/{team_id}/customers/{customer_id}/report/detailed', ('GET', 'HEAD'), 'app.mounts.customer_report.handlers', 'detailed', 'detailed', 'app/mounts/customer_report/detailed/route.py', 6, 10, 'page.jinja', 'app/routes/main/regional/offices/by_office_id/teams/by_team_id/customers/by_customer_id/report/route.py', 'customer_report', '/detailed', None, None),
    ),
    expected_creator=None,
    expected_template_root=None,
    expected_nav=('Detailed', None),
    expected_destinations=(),
    expected_kit=True,
)

_source_9 = _load_route(
    module='app.mounts.customer_report.route',
    source_path='app/mounts/customer_report/route.py',
    expected=(
        ('page', 'GET', '/', '/main/regional/offices/{office_id}/teams/{team_id}/customers/{customer_id}/report', ('GET', 'HEAD'), 'app.mounts.customer_report.handlers', 'page', 'page', 'app/mounts/customer_report/route.py', 6, 10, 'page.jinja', 'app/routes/main/regional/offices/by_office_id/teams/by_team_id/customers/by_customer_id/report/route.py', 'customer_report', '/', None, None),
    ),
    expected_creator=None,
    expected_template_root=None,
    expected_nav=('Report', None),
    expected_destinations=(),
    expected_kit=True,
)

_route_9 = _load_route(
    module='app.routes.main.regional.offices.by_office_id.teams.by_team_id.customers.by_customer_id.route',
    source_path='app/routes/main/regional/offices/by_office_id/teams/by_team_id/customers/by_customer_id/route.py',
    expected=(
        ('page', 'GET', '/', '/main/regional/offices/{office_id}/teams/{team_id}/customers/{customer_id}', ('GET', 'HEAD'), 'app.routes.main.regional.offices.by_office_id.teams.by_team_id.customers.by_customer_id.route', 'page', 'page', 'app/routes/main/regional/offices/by_office_id/teams/by_team_id/customers/by_customer_id/route.py', 52, 10, 'page.jinja', 'app/routes/main/regional/offices/by_office_id/teams/by_team_id/customers/by_customer_id/route.py', None, None, None, None),
    ),
    expected_creator=None,
    expected_template_root=None,
    expected_nav=(None, 'customer'),
    expected_destinations=(('shared-report', '/main/reports/{customer_id}', 'regional-customer'),),
)

_route_10 = _load_route(
    module='app.routes.main.regional.offices.by_office_id.teams.by_team_id.route',
    source_path='app/routes/main/regional/offices/by_office_id/teams/by_team_id/route.py',
    expected=(
        ('page', 'GET', '/', '/main/regional/offices/{office_id}/teams/{team_id}', ('GET', 'HEAD'), 'app.routes.main.regional.offices.by_office_id.teams.by_team_id.route', 'page', 'page', 'app/routes/main/regional/offices/by_office_id/teams/by_team_id/route.py', 44, 20, 'page.jinja', 'app/routes/main/regional/offices/by_office_id/teams/by_team_id/route.py', None, None, None, None),
    ),
    expected_creator=None,
    expected_template_root=None,
    expected_nav=(None, 'team'),
    expected_destinations=(),
)

_route_11 = _load_route(
    module='app.routes.main.regional.route',
    source_path='app/routes/main/regional/route.py',
    expected=(
        ('page', 'GET', '/', '/main/regional', ('GET', 'HEAD'), 'app.routes.main.regional.route', 'page', 'page', 'app/routes/main/regional/route.py', 20, 20, 'page.jinja', 'app/routes/main/regional/route.py', None, None, None, None),
    ),
    expected_creator=None,
    expected_template_root=None,
    expected_nav=('Regional', None),
    expected_destinations=(),
)

_route_12 = _load_route(
    module='app.routes.main.reports.by_customer_id.route',
    source_path='app/routes/main/reports/by_customer_id/route.py',
    expected=(
        ('page', 'GET', '/', '/main/reports/{customer_id}', ('GET', 'HEAD'), 'app.routes.main.reports.by_customer_id.route', 'page', 'page', 'app/routes/main/reports/by_customer_id/route.py', 77, 10, 'page.jinja', 'app/routes/main/reports/by_customer_id/route.py', None, None, None, None),
    ),
    expected_creator=None,
    expected_template_root=None,
    expected_nav=('Report', None),
    expected_destinations=(),
)

_route_13 = _load_route(
    module='app.routes.main.route',
    source_path='app/routes/main/route.py',
    expected=(
        ('page', 'GET', '/', '/main', ('GET', 'HEAD'), 'app.routes.main.route', 'page', 'page', 'app/routes/main/route.py', 23, 20, 'page.jinja', 'app/routes/main/route.py', None, None, None, None),
    ),
    expected_creator=None,
    expected_template_root=None,
    expected_nav=('Main', None),
    expected_destinations=(),
)

_route_14 = _load_route(
    module='app.routes.route',
    source_path='app/routes/route.py',
    expected=(
        ('page', 'GET', '/', '/', ('GET', 'HEAD'), 'app.routes.route', 'page', 'page', 'app/routes/route.py', 21, 10, 'page.jinja', 'app/routes/route.py', None, None, None, None),
    ),
    expected_creator=None,
    expected_template_root=None,
    expected_nav=('Home', None),
    expected_destinations=(),
)

if _TYPE_CHECKING:
    def _check_mounted_kit[K](
        owner: _KitRouteMount[K],
        source: _KitRouteDef[K],
    ) -> None:
        ...
    # Owner/source generic type witness.
    from app.routes.main.hq.teams.by_team_id.analytics.route import Route as _owner_route_2
    from app.mounts.analytics.customers.by_customer_id.report.route import Route as _source_route_0
    _check_mounted_kit(_owner_route_2, _source_route_0)
    from app.routes.main.hq.teams.by_team_id.analytics.route import Route as _owner_route_2
    from app.mounts.analytics.route import Route as _source_route_1
    _check_mounted_kit(_owner_route_2, _source_route_1)
    # Owner/source generic type witness.
    from app.routes.main.hq.teams.by_team_id.customers.by_customer_id.report.route import Route as _owner_route_3
    from app.mounts.customer_report.brief.route import Route as _source_route_2
    _check_mounted_kit(_owner_route_3, _source_route_2)
    from app.routes.main.hq.teams.by_team_id.customers.by_customer_id.report.route import Route as _owner_route_3
    from app.mounts.customer_report.detailed.route import Route as _source_route_3
    _check_mounted_kit(_owner_route_3, _source_route_3)
    from app.routes.main.hq.teams.by_team_id.customers.by_customer_id.report.route import Route as _owner_route_3
    from app.mounts.customer_report.route import Route as _source_route_4
    _check_mounted_kit(_owner_route_3, _source_route_4)
    # Owner/source generic type witness.
    from app.routes.main.regional.offices.by_office_id.teams.by_team_id.analytics.route import Route as _owner_route_7
    from app.mounts.analytics.customers.by_customer_id.report.route import Route as _source_route_5
    _check_mounted_kit(_owner_route_7, _source_route_5)
    from app.routes.main.regional.offices.by_office_id.teams.by_team_id.analytics.route import Route as _owner_route_7
    from app.mounts.analytics.route import Route as _source_route_6
    _check_mounted_kit(_owner_route_7, _source_route_6)
    # Owner/source generic type witness.
    from app.routes.main.regional.offices.by_office_id.teams.by_team_id.customers.by_customer_id.report.route import Route as _owner_route_8
    from app.mounts.customer_report.brief.route import Route as _source_route_7
    _check_mounted_kit(_owner_route_8, _source_route_7)
    from app.routes.main.regional.offices.by_office_id.teams.by_team_id.customers.by_customer_id.report.route import Route as _owner_route_8
    from app.mounts.customer_report.detailed.route import Route as _source_route_8
    _check_mounted_kit(_owner_route_8, _source_route_8)
    from app.routes.main.regional.offices.by_office_id.teams.by_team_id.customers.by_customer_id.report.route import Route as _owner_route_8
    from app.mounts.customer_report.route import Route as _source_route_9
    _check_mounted_kit(_owner_route_8, _source_route_9)

_handler_0 = _select_handler(
    _route_14,
    kind='page',
    method='GET',
    local_path='/',
)

_handler_1 = _select_handler(
    _route_0,
    kind='page',
    method='GET',
    local_path='/',
)

_handler_2 = _select_handler(
    _route_13,
    kind='page',
    method='GET',
    local_path='/',
)

_handler_3 = _select_handler(
    _route_1,
    kind='page',
    method='GET',
    local_path='/',
)

_handler_4 = _select_handler(
    _route_5,
    kind='page',
    method='GET',
    local_path='/',
)

_handler_5 = _select_handler(
    _source_1,
    kind='page',
    method='GET',
    local_path='/',
)

_creator_5 = _select_creator(
    _route_2,
)

_handler_6 = _select_handler(
    _source_0,
    kind='page',
    method='GET',
    local_path='/',
)

_creator_6 = _select_creator(
    _route_2,
)

_handler_7 = _select_handler(
    _route_4,
    kind='page',
    method='GET',
    local_path='/',
)

_handler_8 = _select_handler(
    _source_4,
    kind='page',
    method='GET',
    local_path='/',
)

_creator_8 = _select_creator(
    _route_3,
)

_handler_9 = _select_handler(
    _source_2,
    kind='page',
    method='GET',
    local_path='/',
)

_creator_9 = _select_creator(
    _route_3,
)

_handler_10 = _select_handler(
    _source_3,
    kind='page',
    method='GET',
    local_path='/',
)

_creator_10 = _select_creator(
    _route_3,
)

_handler_11 = _select_handler(
    _route_11,
    kind='page',
    method='GET',
    local_path='/',
)

_handler_12 = _select_handler(
    _route_6,
    kind='page',
    method='GET',
    local_path='/',
)

_handler_13 = _select_handler(
    _route_10,
    kind='page',
    method='GET',
    local_path='/',
)

_handler_14 = _select_handler(
    _source_6,
    kind='page',
    method='GET',
    local_path='/',
)

_creator_14 = _select_creator(
    _route_7,
)

_handler_15 = _select_handler(
    _source_5,
    kind='page',
    method='GET',
    local_path='/',
)

_creator_15 = _select_creator(
    _route_7,
)

_handler_16 = _select_handler(
    _route_9,
    kind='page',
    method='GET',
    local_path='/',
)

_handler_17 = _select_handler(
    _source_9,
    kind='page',
    method='GET',
    local_path='/',
)

_creator_17 = _select_creator(
    _route_8,
)

_handler_18 = _select_handler(
    _source_7,
    kind='page',
    method='GET',
    local_path='/',
)

_creator_18 = _select_creator(
    _route_8,
)

_handler_19 = _select_handler(
    _source_8,
    kind='page',
    method='GET',
    local_path='/',
)

_creator_19 = _select_creator(
    _route_8,
)

_handler_20 = _select_handler(
    _route_12,
    kind='page',
    method='GET',
    local_path='/',
)

def create_router(
    *,
    environment: _Environment | None = None,
    error_handler: _RouteErrorHandler | None = None,
    template_inspection: _TemplateInspectionMode = _TemplateInspectionMode.OFF,
) -> _Router:
    selected_template_inspection = _prepare_template_inspection(
        template_inspection,
        source_path='app/_pyganini/asgi.py',
    )
    selected_environment = _prepare_environment(
        environment,
        template_names=_template_names,
        source_path='app/_pyganini/asgi.py',
    )
    selected_error_handler = _prepare_route_error_handler(
        error_handler,
        template_inspection=selected_template_inspection,
        source_path='app/_pyganini/asgi.py',
    )
    endpoint_0 = _build_endpoint(
        handlers={
            'GET': _handler_0,
        },
        navigation={'GET': (('Home', None, '/', True),)},
        evidence={
            'GET': ('page', '/', ('GET', 'HEAD'), 'app/routes/route.py', 1, 1, 'app.routes.route', 'page', 'page', 'app/routes/route.py', None, None, 1, 1, '/'),
        },
        embedded_expectations={
            'GET': (),
        },
        rendering={
            'GET': (('routes/page.jinja', 'app/routes/page.jinja', 1, 1, None, ('app/routes/route.py', 22, 14)), (('app/routes/layout.py', 1, 1, '/', ('routes/layout.jinja', 'app/routes/layout.jinja', 1, 1, None, None)),), ('page', 'page', '/', 'routes/page.jinja', 'app/routes/page.jinja:1:1', 'app/routes/route.py:22:14', 'app/routes/route.py:1:1', 'app.routes.route:page', 'none'), (('layout', 'page', '/', 'routes/layout.jinja', 'app/routes/layout.jinja:1:1', 'none', 'app/routes/layout.py:1:1', 'none', 'none'),), ()),
        },
        parameters=(),
        environment=selected_environment,
        template_inspection=selected_template_inspection,
    )
    endpoint_1 = _build_endpoint(
        handlers={
            'GET': _handler_1,
        },
        navigation={'GET': (('Home', None, '/', False), ('About', None, '/about', True))},
        evidence={
            'GET': ('page', '/about', ('GET', 'HEAD'), 'app/routes/about/route.py', 1, 1, 'app.routes.about.route', 'page', 'page', 'app/routes/about/route.py', None, None, 1, 1, '/about'),
        },
        embedded_expectations={
            'GET': (),
        },
        rendering={
            'GET': (('routes/about/page.jinja', 'app/routes/about/page.jinja', 1, 1, None, ('app/routes/about/route.py', 18, 35)), (('app/routes/layout.py', 1, 1, '/', ('routes/layout.jinja', 'app/routes/layout.jinja', 1, 1, None, None)),), ('page', 'page', '/about', 'routes/about/page.jinja', 'app/routes/about/page.jinja:1:1', 'app/routes/about/route.py:18:35', 'app/routes/about/route.py:1:1', 'app.routes.about.route:page', 'none'), (('layout', 'page', '/', 'routes/layout.jinja', 'app/routes/layout.jinja:1:1', 'none', 'app/routes/layout.py:1:1', 'none', 'none'),), ()),
        },
        parameters=(),
        environment=selected_environment,
        template_inspection=selected_template_inspection,
    )
    endpoint_2 = _build_endpoint(
        handlers={
            'GET': _handler_2,
        },
        navigation={'GET': (('Home', None, '/', False), ('Main', None, '/main', True))},
        evidence={
            'GET': ('page', '/main', ('GET', 'HEAD'), 'app/routes/main/route.py', 1, 1, 'app.routes.main.route', 'page', 'page', 'app/routes/main/route.py', None, None, 1, 1, '/main'),
        },
        embedded_expectations={
            'GET': (),
        },
        rendering={
            'GET': (('routes/main/page.jinja', 'app/routes/main/page.jinja', 1, 1, None, ('app/routes/main/route.py', 23, 35)), (('app/routes/layout.py', 1, 1, '/', ('routes/layout.jinja', 'app/routes/layout.jinja', 1, 1, None, None)),), ('page', 'page', '/main', 'routes/main/page.jinja', 'app/routes/main/page.jinja:1:1', 'app/routes/main/route.py:23:35', 'app/routes/main/route.py:1:1', 'app.routes.main.route:page', 'none'), (('layout', 'page', '/', 'routes/layout.jinja', 'app/routes/layout.jinja:1:1', 'none', 'app/routes/layout.py:1:1', 'none', 'none'),), ()),
        },
        parameters=(),
        environment=selected_environment,
        template_inspection=selected_template_inspection,
    )
    endpoint_3 = _build_endpoint(
        handlers={
            'GET': _handler_3,
        },
        navigation={'GET': (('Home', None, '/', False), ('Main', None, '/main', False), ('HQ', None, '/main/hq', True))},
        evidence={
            'GET': ('page', '/main/hq', ('GET', 'HEAD'), 'app/routes/main/hq/route.py', 1, 1, 'app.routes.main.hq.route', 'page', 'page', 'app/routes/main/hq/route.py', None, None, 1, 1, '/main/hq'),
        },
        embedded_expectations={
            'GET': (),
        },
        rendering={
            'GET': (('routes/main/hq/page.jinja', 'app/routes/main/hq/page.jinja', 1, 1, None, ('app/routes/main/hq/route.py', 20, 35)), (('app/routes/layout.py', 1, 1, '/', ('routes/layout.jinja', 'app/routes/layout.jinja', 1, 1, None, None)),), ('page', 'page', '/main/hq', 'routes/main/hq/page.jinja', 'app/routes/main/hq/page.jinja:1:1', 'app/routes/main/hq/route.py:20:35', 'app/routes/main/hq/route.py:1:1', 'app.routes.main.hq.route:page', 'none'), (('layout', 'page', '/', 'routes/layout.jinja', 'app/routes/layout.jinja:1:1', 'none', 'app/routes/layout.py:1:1', 'none', 'none'),), ()),
        },
        parameters=(),
        environment=selected_environment,
        template_inspection=selected_template_inspection,
    )
    endpoint_4 = _build_endpoint(
        handlers={
            'GET': _handler_4,
        },
        navigation={'GET': (('Home', None, '/', False), ('Main', None, '/main', False), ('HQ', None, '/main/hq', False), (None, 'team', '/main/hq/teams/{team_id}', True))},
        evidence={
            'GET': ('page', '/main/hq/teams/{team_id}', ('GET', 'HEAD'), 'app/routes/main/hq/teams/by_team_id/route.py', 1, 1, 'app.routes.main.hq.teams.by_team_id.route', 'page', 'page', 'app/routes/main/hq/teams/by_team_id/route.py', None, None, 1, 1, '/main/hq/teams/{team_id}'),
        },
        embedded_expectations={
            'GET': (),
        },
        rendering={
            'GET': (('routes/main/hq/teams/by_team_id/page.jinja', 'app/routes/main/hq/teams/by_team_id/page.jinja', 1, 1, None, ('app/routes/main/hq/teams/by_team_id/route.py', 31, 35)), (('app/routes/layout.py', 1, 1, '/', ('routes/layout.jinja', 'app/routes/layout.jinja', 1, 1, None, None)),), ('page', 'page', '/main/hq/teams/{team_id}', 'routes/main/hq/teams/by_team_id/page.jinja', 'app/routes/main/hq/teams/by_team_id/page.jinja:1:1', 'app/routes/main/hq/teams/by_team_id/route.py:31:35', 'app/routes/main/hq/teams/by_team_id/route.py:1:1', 'app.routes.main.hq.teams.by_team_id.route:page', 'none'), (('layout', 'page', '/', 'routes/layout.jinja', 'app/routes/layout.jinja:1:1', 'none', 'app/routes/layout.py:1:1', 'none', 'none'),), ()),
        },
        parameters=('team_id',),
        environment=selected_environment,
        template_inspection=selected_template_inspection,
    )
    endpoint_5 = _build_endpoint(
        handlers={
            'GET': _handler_5,
        },
        creators={
            'GET': _creator_5,
        },
        navigation={'GET': (('Home', None, '/', False), ('Main', None, '/main', False), ('HQ', None, '/main/hq', False), (None, 'team', '/main/hq/teams/{team_id}', False), ('Analytics', None, '/main/hq/teams/{team_id}/analytics', True))},
        evidence={
            'GET': ('page', '/main/hq/teams/{team_id}/analytics', ('GET', 'HEAD'), 'app/mounts/analytics/route.py', 1, 1, 'app.mounts.analytics.handlers', 'page', 'page', 'app/routes/main/hq/teams/by_team_id/analytics/route.py', 'analytics', '/', 1, 1, '/main/hq/teams/{team_id}/analytics'),
        },
        embedded_expectations={
            'GET': (),
        },
        rendering={
            'GET': (('mounts/analytics/page.jinja', 'app/mounts/analytics/page.jinja', 1, 1, None, ('app/mounts/analytics/route.py', 7, 14)), (('app/routes/layout.py', 1, 1, '/', ('routes/layout.jinja', 'app/routes/layout.jinja', 1, 1, None, None)),), ('page', 'page', '/main/hq/teams/{team_id}/analytics', 'mounts/analytics/page.jinja', 'app/mounts/analytics/page.jinja:1:1', 'app/mounts/analytics/route.py:7:14', 'app/routes/main/hq/teams/by_team_id/analytics/route.py:1:1', 'app.mounts.analytics.handlers:page', 'analytics:/'), (('layout', 'page', '/', 'routes/layout.jinja', 'app/routes/layout.jinja:1:1', 'none', 'app/routes/layout.py:1:1', 'none', 'none'),), ()),
        },
        parameters=('team_id',),
        environment=selected_environment,
        template_inspection=selected_template_inspection,
    )
    endpoint_6 = _build_endpoint(
        handlers={
            'GET': _handler_6,
        },
        creators={
            'GET': _creator_6,
        },
        navigation={'GET': (('Home', None, '/', False), ('Main', None, '/main', False), ('HQ', None, '/main/hq', False), (None, 'team', '/main/hq/teams/{team_id}', False), ('Analytics', None, '/main/hq/teams/{team_id}/analytics', False), ('Report', None, '/main/hq/teams/{team_id}/analytics/customers/{customer_id}/report', True))},
        trail_keys={'GET': ('hq-analytics',)},
        evidence={
            'GET': ('page', '/main/hq/teams/{team_id}/analytics/customers/{customer_id}/report', ('GET', 'HEAD'), 'app/mounts/analytics/customers/by_customer_id/report/route.py', 1, 1, 'app.mounts.analytics.customers.by_customer_id.report.handlers', 'page', 'page', 'app/routes/main/hq/teams/by_team_id/analytics/route.py', 'analytics', '/customers/{customer_id}/report', 1, 1, '/main/hq/teams/{team_id}/analytics'),
        },
        embedded_expectations={
            'GET': (),
        },
        rendering={
            'GET': (('mounts/analytics/customers/by_customer_id/report/page.jinja', 'app/mounts/analytics/customers/by_customer_id/report/page.jinja', 1, 1, None, ('app/mounts/analytics/customers/by_customer_id/report/route.py', 7, 14)), (('app/routes/layout.py', 1, 1, '/', ('routes/layout.jinja', 'app/routes/layout.jinja', 1, 1, None, None)),), ('page', 'page', '/main/hq/teams/{team_id}/analytics/customers/{customer_id}/report', 'mounts/analytics/customers/by_customer_id/report/page.jinja', 'app/mounts/analytics/customers/by_customer_id/report/page.jinja:1:1', 'app/mounts/analytics/customers/by_customer_id/report/route.py:7:14', 'app/routes/main/hq/teams/by_team_id/analytics/route.py:1:1', 'app.mounts.analytics.customers.by_customer_id.report.handlers:page', 'analytics:/customers/{customer_id}/report'), (('layout', 'page', '/', 'routes/layout.jinja', 'app/routes/layout.jinja:1:1', 'none', 'app/routes/layout.py:1:1', 'none', 'none'),), ()),
        },
        parameters=('team_id', 'customer_id'),
        environment=selected_environment,
        template_inspection=selected_template_inspection,
    )
    endpoint_7 = _build_endpoint(
        handlers={
            'GET': _handler_7,
        },
        navigation={'GET': (('Home', None, '/', False), ('Main', None, '/main', False), ('HQ', None, '/main/hq', False), (None, 'team', '/main/hq/teams/{team_id}', False), (None, 'customer', '/main/hq/teams/{team_id}/customers/{customer_id}', True))},
        evidence={
            'GET': ('page', '/main/hq/teams/{team_id}/customers/{customer_id}', ('GET', 'HEAD'), 'app/routes/main/hq/teams/by_team_id/customers/by_customer_id/route.py', 1, 1, 'app.routes.main.hq.teams.by_team_id.customers.by_customer_id.route', 'page', 'page', 'app/routes/main/hq/teams/by_team_id/customers/by_customer_id/route.py', None, None, 1, 1, '/main/hq/teams/{team_id}/customers/{customer_id}'),
        },
        embedded_expectations={
            'GET': (),
        },
        rendering={
            'GET': (('routes/main/hq/teams/by_team_id/customers/by_customer_id/page.jinja', 'app/routes/main/hq/teams/by_team_id/customers/by_customer_id/page.jinja', 1, 1, None, ('app/routes/main/hq/teams/by_team_id/customers/by_customer_id/route.py', 47, 14)), (('app/routes/layout.py', 1, 1, '/', ('routes/layout.jinja', 'app/routes/layout.jinja', 1, 1, None, None)),), ('page', 'page', '/main/hq/teams/{team_id}/customers/{customer_id}', 'routes/main/hq/teams/by_team_id/customers/by_customer_id/page.jinja', 'app/routes/main/hq/teams/by_team_id/customers/by_customer_id/page.jinja:1:1', 'app/routes/main/hq/teams/by_team_id/customers/by_customer_id/route.py:47:14', 'app/routes/main/hq/teams/by_team_id/customers/by_customer_id/route.py:1:1', 'app.routes.main.hq.teams.by_team_id.customers.by_customer_id.route:page', 'none'), (('layout', 'page', '/', 'routes/layout.jinja', 'app/routes/layout.jinja:1:1', 'none', 'app/routes/layout.py:1:1', 'none', 'none'),), ()),
        },
        parameters=('team_id', 'customer_id'),
        environment=selected_environment,
        template_inspection=selected_template_inspection,
    )
    endpoint_8 = _build_endpoint(
        handlers={
            'GET': _handler_8,
        },
        creators={
            'GET': _creator_8,
        },
        navigation={'GET': (('Home', None, '/', False), ('Main', None, '/main', False), ('HQ', None, '/main/hq', False), (None, 'team', '/main/hq/teams/{team_id}', False), (None, 'customer', '/main/hq/teams/{team_id}/customers/{customer_id}', False), ('Report', None, '/main/hq/teams/{team_id}/customers/{customer_id}/report', True))},
        evidence={
            'GET': ('page', '/main/hq/teams/{team_id}/customers/{customer_id}/report', ('GET', 'HEAD'), 'app/mounts/customer_report/route.py', 1, 1, 'app.mounts.customer_report.handlers', 'page', 'page', 'app/routes/main/hq/teams/by_team_id/customers/by_customer_id/report/route.py', 'customer_report', '/', 1, 1, '/main/hq/teams/{team_id}/customers/{customer_id}/report'),
        },
        embedded_expectations={
            'GET': (),
        },
        rendering={
            'GET': (('mounts/customer_report/page.jinja', 'app/mounts/customer_report/page.jinja', 1, 1, None, ('app/mounts/customer_report/route.py', 7, 14)), (('app/routes/layout.py', 1, 1, '/', ('routes/layout.jinja', 'app/routes/layout.jinja', 1, 1, None, None)), ('app/mounts/customer_report/layout.py', 1, 1, '/', ('mounts/customer_report/layout.jinja', 'app/mounts/customer_report/layout.jinja', 1, 1, None, None))), ('page', 'page', '/main/hq/teams/{team_id}/customers/{customer_id}/report', 'mounts/customer_report/page.jinja', 'app/mounts/customer_report/page.jinja:1:1', 'app/mounts/customer_report/route.py:7:14', 'app/routes/main/hq/teams/by_team_id/customers/by_customer_id/report/route.py:1:1', 'app.mounts.customer_report.handlers:page', 'customer_report:/'), (('layout', 'page', '/', 'routes/layout.jinja', 'app/routes/layout.jinja:1:1', 'none', 'app/routes/layout.py:1:1', 'none', 'none'), ('layout', 'page', '/main/hq/teams/{team_id}/customers/{customer_id}/report', 'mounts/customer_report/layout.jinja', 'app/mounts/customer_report/layout.jinja:1:1', 'none', 'app/mounts/customer_report/layout.py:1:1', 'none', 'customer_report:/')), ()),
        },
        parameters=('team_id', 'customer_id'),
        environment=selected_environment,
        template_inspection=selected_template_inspection,
    )
    endpoint_9 = _build_endpoint(
        handlers={
            'GET': _handler_9,
        },
        creators={
            'GET': _creator_9,
        },
        navigation={'GET': (('Home', None, '/', False), ('Main', None, '/main', False), ('HQ', None, '/main/hq', False), (None, 'team', '/main/hq/teams/{team_id}', False), (None, 'customer', '/main/hq/teams/{team_id}/customers/{customer_id}', False), ('Report', None, '/main/hq/teams/{team_id}/customers/{customer_id}/report', False), ('Brief', None, '/main/hq/teams/{team_id}/customers/{customer_id}/report/brief', True))},
        evidence={
            'GET': ('page', '/main/hq/teams/{team_id}/customers/{customer_id}/report/brief', ('GET', 'HEAD'), 'app/mounts/customer_report/brief/route.py', 1, 1, 'app.mounts.customer_report.handlers', 'brief', 'brief', 'app/routes/main/hq/teams/by_team_id/customers/by_customer_id/report/route.py', 'customer_report', '/brief', 1, 1, '/main/hq/teams/{team_id}/customers/{customer_id}/report'),
        },
        embedded_expectations={
            'GET': (),
        },
        rendering={
            'GET': (('mounts/customer_report/brief/page.jinja', 'app/mounts/customer_report/brief/page.jinja', 1, 1, None, ('app/mounts/customer_report/brief/route.py', 7, 14)), (('app/routes/layout.py', 1, 1, '/', ('routes/layout.jinja', 'app/routes/layout.jinja', 1, 1, None, None)), ('app/mounts/customer_report/layout.py', 1, 1, '/', ('mounts/customer_report/layout.jinja', 'app/mounts/customer_report/layout.jinja', 1, 1, None, None))), ('page', 'page', '/main/hq/teams/{team_id}/customers/{customer_id}/report/brief', 'mounts/customer_report/brief/page.jinja', 'app/mounts/customer_report/brief/page.jinja:1:1', 'app/mounts/customer_report/brief/route.py:7:14', 'app/routes/main/hq/teams/by_team_id/customers/by_customer_id/report/route.py:1:1', 'app.mounts.customer_report.handlers:brief', 'customer_report:/brief'), (('layout', 'page', '/', 'routes/layout.jinja', 'app/routes/layout.jinja:1:1', 'none', 'app/routes/layout.py:1:1', 'none', 'none'), ('layout', 'page', '/main/hq/teams/{team_id}/customers/{customer_id}/report', 'mounts/customer_report/layout.jinja', 'app/mounts/customer_report/layout.jinja:1:1', 'none', 'app/mounts/customer_report/layout.py:1:1', 'none', 'customer_report:/brief')), ()),
        },
        parameters=('team_id', 'customer_id'),
        environment=selected_environment,
        template_inspection=selected_template_inspection,
    )
    endpoint_10 = _build_endpoint(
        handlers={
            'GET': _handler_10,
        },
        creators={
            'GET': _creator_10,
        },
        navigation={'GET': (('Home', None, '/', False), ('Main', None, '/main', False), ('HQ', None, '/main/hq', False), (None, 'team', '/main/hq/teams/{team_id}', False), (None, 'customer', '/main/hq/teams/{team_id}/customers/{customer_id}', False), ('Report', None, '/main/hq/teams/{team_id}/customers/{customer_id}/report', False), ('Detailed', None, '/main/hq/teams/{team_id}/customers/{customer_id}/report/detailed', True))},
        evidence={
            'GET': ('page', '/main/hq/teams/{team_id}/customers/{customer_id}/report/detailed', ('GET', 'HEAD'), 'app/mounts/customer_report/detailed/route.py', 1, 1, 'app.mounts.customer_report.handlers', 'detailed', 'detailed', 'app/routes/main/hq/teams/by_team_id/customers/by_customer_id/report/route.py', 'customer_report', '/detailed', 1, 1, '/main/hq/teams/{team_id}/customers/{customer_id}/report'),
        },
        embedded_expectations={
            'GET': (),
        },
        rendering={
            'GET': (('mounts/customer_report/detailed/page.jinja', 'app/mounts/customer_report/detailed/page.jinja', 1, 1, None, ('app/mounts/customer_report/detailed/route.py', 7, 14)), (('app/routes/layout.py', 1, 1, '/', ('routes/layout.jinja', 'app/routes/layout.jinja', 1, 1, None, None)), ('app/mounts/customer_report/layout.py', 1, 1, '/', ('mounts/customer_report/layout.jinja', 'app/mounts/customer_report/layout.jinja', 1, 1, None, None))), ('page', 'page', '/main/hq/teams/{team_id}/customers/{customer_id}/report/detailed', 'mounts/customer_report/detailed/page.jinja', 'app/mounts/customer_report/detailed/page.jinja:1:1', 'app/mounts/customer_report/detailed/route.py:7:14', 'app/routes/main/hq/teams/by_team_id/customers/by_customer_id/report/route.py:1:1', 'app.mounts.customer_report.handlers:detailed', 'customer_report:/detailed'), (('layout', 'page', '/', 'routes/layout.jinja', 'app/routes/layout.jinja:1:1', 'none', 'app/routes/layout.py:1:1', 'none', 'none'), ('layout', 'page', '/main/hq/teams/{team_id}/customers/{customer_id}/report', 'mounts/customer_report/layout.jinja', 'app/mounts/customer_report/layout.jinja:1:1', 'none', 'app/mounts/customer_report/layout.py:1:1', 'none', 'customer_report:/detailed')), ()),
        },
        parameters=('team_id', 'customer_id'),
        environment=selected_environment,
        template_inspection=selected_template_inspection,
    )
    endpoint_11 = _build_endpoint(
        handlers={
            'GET': _handler_11,
        },
        navigation={'GET': (('Home', None, '/', False), ('Main', None, '/main', False), ('Regional', None, '/main/regional', True))},
        evidence={
            'GET': ('page', '/main/regional', ('GET', 'HEAD'), 'app/routes/main/regional/route.py', 1, 1, 'app.routes.main.regional.route', 'page', 'page', 'app/routes/main/regional/route.py', None, None, 1, 1, '/main/regional'),
        },
        embedded_expectations={
            'GET': (),
        },
        rendering={
            'GET': (('routes/main/regional/page.jinja', 'app/routes/main/regional/page.jinja', 1, 1, None, ('app/routes/main/regional/route.py', 20, 35)), (('app/routes/layout.py', 1, 1, '/', ('routes/layout.jinja', 'app/routes/layout.jinja', 1, 1, None, None)),), ('page', 'page', '/main/regional', 'routes/main/regional/page.jinja', 'app/routes/main/regional/page.jinja:1:1', 'app/routes/main/regional/route.py:20:35', 'app/routes/main/regional/route.py:1:1', 'app.routes.main.regional.route:page', 'none'), (('layout', 'page', '/', 'routes/layout.jinja', 'app/routes/layout.jinja:1:1', 'none', 'app/routes/layout.py:1:1', 'none', 'none'),), ()),
        },
        parameters=(),
        environment=selected_environment,
        template_inspection=selected_template_inspection,
    )
    endpoint_12 = _build_endpoint(
        handlers={
            'GET': _handler_12,
        },
        navigation={'GET': (('Home', None, '/', False), ('Main', None, '/main', False), ('Regional', None, '/main/regional', False), (None, 'office', '/main/regional/offices/{office_id}', True))},
        evidence={
            'GET': ('page', '/main/regional/offices/{office_id}', ('GET', 'HEAD'), 'app/routes/main/regional/offices/by_office_id/route.py', 1, 1, 'app.routes.main.regional.offices.by_office_id.route', 'page', 'page', 'app/routes/main/regional/offices/by_office_id/route.py', None, None, 1, 1, '/main/regional/offices/{office_id}'),
        },
        embedded_expectations={
            'GET': (),
        },
        rendering={
            'GET': (('routes/main/regional/offices/by_office_id/page.jinja', 'app/routes/main/regional/offices/by_office_id/page.jinja', 1, 1, None, ('app/routes/main/regional/offices/by_office_id/route.py', 30, 35)), (('app/routes/layout.py', 1, 1, '/', ('routes/layout.jinja', 'app/routes/layout.jinja', 1, 1, None, None)),), ('page', 'page', '/main/regional/offices/{office_id}', 'routes/main/regional/offices/by_office_id/page.jinja', 'app/routes/main/regional/offices/by_office_id/page.jinja:1:1', 'app/routes/main/regional/offices/by_office_id/route.py:30:35', 'app/routes/main/regional/offices/by_office_id/route.py:1:1', 'app.routes.main.regional.offices.by_office_id.route:page', 'none'), (('layout', 'page', '/', 'routes/layout.jinja', 'app/routes/layout.jinja:1:1', 'none', 'app/routes/layout.py:1:1', 'none', 'none'),), ()),
        },
        parameters=('office_id',),
        environment=selected_environment,
        template_inspection=selected_template_inspection,
    )
    endpoint_13 = _build_endpoint(
        handlers={
            'GET': _handler_13,
        },
        navigation={'GET': (('Home', None, '/', False), ('Main', None, '/main', False), ('Regional', None, '/main/regional', False), (None, 'office', '/main/regional/offices/{office_id}', False), (None, 'team', '/main/regional/offices/{office_id}/teams/{team_id}', True))},
        evidence={
            'GET': ('page', '/main/regional/offices/{office_id}/teams/{team_id}', ('GET', 'HEAD'), 'app/routes/main/regional/offices/by_office_id/teams/by_team_id/route.py', 1, 1, 'app.routes.main.regional.offices.by_office_id.teams.by_team_id.route', 'page', 'page', 'app/routes/main/regional/offices/by_office_id/teams/by_team_id/route.py', None, None, 1, 1, '/main/regional/offices/{office_id}/teams/{team_id}'),
        },
        embedded_expectations={
            'GET': (),
        },
        rendering={
            'GET': (('routes/main/regional/offices/by_office_id/teams/by_team_id/page.jinja', 'app/routes/main/regional/offices/by_office_id/teams/by_team_id/page.jinja', 1, 1, None, ('app/routes/main/regional/offices/by_office_id/teams/by_team_id/route.py', 44, 35)), (('app/routes/layout.py', 1, 1, '/', ('routes/layout.jinja', 'app/routes/layout.jinja', 1, 1, None, None)),), ('page', 'page', '/main/regional/offices/{office_id}/teams/{team_id}', 'routes/main/regional/offices/by_office_id/teams/by_team_id/page.jinja', 'app/routes/main/regional/offices/by_office_id/teams/by_team_id/page.jinja:1:1', 'app/routes/main/regional/offices/by_office_id/teams/by_team_id/route.py:44:35', 'app/routes/main/regional/offices/by_office_id/teams/by_team_id/route.py:1:1', 'app.routes.main.regional.offices.by_office_id.teams.by_team_id.route:page', 'none'), (('layout', 'page', '/', 'routes/layout.jinja', 'app/routes/layout.jinja:1:1', 'none', 'app/routes/layout.py:1:1', 'none', 'none'),), ()),
        },
        parameters=('office_id', 'team_id'),
        environment=selected_environment,
        template_inspection=selected_template_inspection,
    )
    endpoint_14 = _build_endpoint(
        handlers={
            'GET': _handler_14,
        },
        creators={
            'GET': _creator_14,
        },
        navigation={'GET': (('Home', None, '/', False), ('Main', None, '/main', False), ('Regional', None, '/main/regional', False), (None, 'office', '/main/regional/offices/{office_id}', False), (None, 'team', '/main/regional/offices/{office_id}/teams/{team_id}', False), ('Analytics', None, '/main/regional/offices/{office_id}/teams/{team_id}/analytics', True))},
        evidence={
            'GET': ('page', '/main/regional/offices/{office_id}/teams/{team_id}/analytics', ('GET', 'HEAD'), 'app/mounts/analytics/route.py', 1, 1, 'app.mounts.analytics.handlers', 'page', 'page', 'app/routes/main/regional/offices/by_office_id/teams/by_team_id/analytics/route.py', 'analytics', '/', 1, 1, '/main/regional/offices/{office_id}/teams/{team_id}/analytics'),
        },
        embedded_expectations={
            'GET': (),
        },
        rendering={
            'GET': (('mounts/analytics/page.jinja', 'app/mounts/analytics/page.jinja', 1, 1, None, ('app/mounts/analytics/route.py', 7, 14)), (('app/routes/layout.py', 1, 1, '/', ('routes/layout.jinja', 'app/routes/layout.jinja', 1, 1, None, None)),), ('page', 'page', '/main/regional/offices/{office_id}/teams/{team_id}/analytics', 'mounts/analytics/page.jinja', 'app/mounts/analytics/page.jinja:1:1', 'app/mounts/analytics/route.py:7:14', 'app/routes/main/regional/offices/by_office_id/teams/by_team_id/analytics/route.py:1:1', 'app.mounts.analytics.handlers:page', 'analytics:/'), (('layout', 'page', '/', 'routes/layout.jinja', 'app/routes/layout.jinja:1:1', 'none', 'app/routes/layout.py:1:1', 'none', 'none'),), ()),
        },
        parameters=('office_id', 'team_id'),
        environment=selected_environment,
        template_inspection=selected_template_inspection,
    )
    endpoint_15 = _build_endpoint(
        handlers={
            'GET': _handler_15,
        },
        creators={
            'GET': _creator_15,
        },
        navigation={'GET': (('Home', None, '/', False), ('Main', None, '/main', False), ('Regional', None, '/main/regional', False), (None, 'office', '/main/regional/offices/{office_id}', False), (None, 'team', '/main/regional/offices/{office_id}/teams/{team_id}', False), ('Analytics', None, '/main/regional/offices/{office_id}/teams/{team_id}/analytics', False), ('Report', None, '/main/regional/offices/{office_id}/teams/{team_id}/analytics/customers/{customer_id}/report', True))},
        trail_keys={'GET': ('regional-analytics',)},
        evidence={
            'GET': ('page', '/main/regional/offices/{office_id}/teams/{team_id}/analytics/customers/{customer_id}/report', ('GET', 'HEAD'), 'app/mounts/analytics/customers/by_customer_id/report/route.py', 1, 1, 'app.mounts.analytics.customers.by_customer_id.report.handlers', 'page', 'page', 'app/routes/main/regional/offices/by_office_id/teams/by_team_id/analytics/route.py', 'analytics', '/customers/{customer_id}/report', 1, 1, '/main/regional/offices/{office_id}/teams/{team_id}/analytics'),
        },
        embedded_expectations={
            'GET': (),
        },
        rendering={
            'GET': (('mounts/analytics/customers/by_customer_id/report/page.jinja', 'app/mounts/analytics/customers/by_customer_id/report/page.jinja', 1, 1, None, ('app/mounts/analytics/customers/by_customer_id/report/route.py', 7, 14)), (('app/routes/layout.py', 1, 1, '/', ('routes/layout.jinja', 'app/routes/layout.jinja', 1, 1, None, None)),), ('page', 'page', '/main/regional/offices/{office_id}/teams/{team_id}/analytics/customers/{customer_id}/report', 'mounts/analytics/customers/by_customer_id/report/page.jinja', 'app/mounts/analytics/customers/by_customer_id/report/page.jinja:1:1', 'app/mounts/analytics/customers/by_customer_id/report/route.py:7:14', 'app/routes/main/regional/offices/by_office_id/teams/by_team_id/analytics/route.py:1:1', 'app.mounts.analytics.customers.by_customer_id.report.handlers:page', 'analytics:/customers/{customer_id}/report'), (('layout', 'page', '/', 'routes/layout.jinja', 'app/routes/layout.jinja:1:1', 'none', 'app/routes/layout.py:1:1', 'none', 'none'),), ()),
        },
        parameters=('office_id', 'team_id', 'customer_id'),
        environment=selected_environment,
        template_inspection=selected_template_inspection,
    )
    endpoint_16 = _build_endpoint(
        handlers={
            'GET': _handler_16,
        },
        navigation={'GET': (('Home', None, '/', False), ('Main', None, '/main', False), ('Regional', None, '/main/regional', False), (None, 'office', '/main/regional/offices/{office_id}', False), (None, 'team', '/main/regional/offices/{office_id}/teams/{team_id}', False), (None, 'customer', '/main/regional/offices/{office_id}/teams/{team_id}/customers/{customer_id}', True))},
        evidence={
            'GET': ('page', '/main/regional/offices/{office_id}/teams/{team_id}/customers/{customer_id}', ('GET', 'HEAD'), 'app/routes/main/regional/offices/by_office_id/teams/by_team_id/customers/by_customer_id/route.py', 1, 1, 'app.routes.main.regional.offices.by_office_id.teams.by_team_id.customers.by_customer_id.route', 'page', 'page', 'app/routes/main/regional/offices/by_office_id/teams/by_team_id/customers/by_customer_id/route.py', None, None, 1, 1, '/main/regional/offices/{office_id}/teams/{team_id}/customers/{customer_id}'),
        },
        embedded_expectations={
            'GET': (),
        },
        rendering={
            'GET': (('routes/main/regional/offices/by_office_id/teams/by_team_id/customers/by_customer_id/page.jinja', 'app/routes/main/regional/offices/by_office_id/teams/by_team_id/customers/by_customer_id/page.jinja', 1, 1, None, ('app/routes/main/regional/offices/by_office_id/teams/by_team_id/customers/by_customer_id/route.py', 53, 14)), (('app/routes/layout.py', 1, 1, '/', ('routes/layout.jinja', 'app/routes/layout.jinja', 1, 1, None, None)),), ('page', 'page', '/main/regional/offices/{office_id}/teams/{team_id}/customers/{customer_id}', 'routes/main/regional/offices/by_office_id/teams/by_team_id/customers/by_customer_id/page.jinja', 'app/routes/main/regional/offices/by_office_id/teams/by_team_id/customers/by_customer_id/page.jinja:1:1', 'app/routes/main/regional/offices/by_office_id/teams/by_team_id/customers/by_customer_id/route.py:53:14', 'app/routes/main/regional/offices/by_office_id/teams/by_team_id/customers/by_customer_id/route.py:1:1', 'app.routes.main.regional.offices.by_office_id.teams.by_team_id.customers.by_customer_id.route:page', 'none'), (('layout', 'page', '/', 'routes/layout.jinja', 'app/routes/layout.jinja:1:1', 'none', 'app/routes/layout.py:1:1', 'none', 'none'),), ()),
        },
        parameters=('office_id', 'team_id', 'customer_id'),
        environment=selected_environment,
        template_inspection=selected_template_inspection,
    )
    endpoint_17 = _build_endpoint(
        handlers={
            'GET': _handler_17,
        },
        creators={
            'GET': _creator_17,
        },
        navigation={'GET': (('Home', None, '/', False), ('Main', None, '/main', False), ('Regional', None, '/main/regional', False), (None, 'office', '/main/regional/offices/{office_id}', False), (None, 'team', '/main/regional/offices/{office_id}/teams/{team_id}', False), (None, 'customer', '/main/regional/offices/{office_id}/teams/{team_id}/customers/{customer_id}', False), ('Report', None, '/main/regional/offices/{office_id}/teams/{team_id}/customers/{customer_id}/report', True))},
        evidence={
            'GET': ('page', '/main/regional/offices/{office_id}/teams/{team_id}/customers/{customer_id}/report', ('GET', 'HEAD'), 'app/mounts/customer_report/route.py', 1, 1, 'app.mounts.customer_report.handlers', 'page', 'page', 'app/routes/main/regional/offices/by_office_id/teams/by_team_id/customers/by_customer_id/report/route.py', 'customer_report', '/', 1, 1, '/main/regional/offices/{office_id}/teams/{team_id}/customers/{customer_id}/report'),
        },
        embedded_expectations={
            'GET': (),
        },
        rendering={
            'GET': (('mounts/customer_report/page.jinja', 'app/mounts/customer_report/page.jinja', 1, 1, None, ('app/mounts/customer_report/route.py', 7, 14)), (('app/routes/layout.py', 1, 1, '/', ('routes/layout.jinja', 'app/routes/layout.jinja', 1, 1, None, None)), ('app/mounts/customer_report/layout.py', 1, 1, '/', ('mounts/customer_report/layout.jinja', 'app/mounts/customer_report/layout.jinja', 1, 1, None, None))), ('page', 'page', '/main/regional/offices/{office_id}/teams/{team_id}/customers/{customer_id}/report', 'mounts/customer_report/page.jinja', 'app/mounts/customer_report/page.jinja:1:1', 'app/mounts/customer_report/route.py:7:14', 'app/routes/main/regional/offices/by_office_id/teams/by_team_id/customers/by_customer_id/report/route.py:1:1', 'app.mounts.customer_report.handlers:page', 'customer_report:/'), (('layout', 'page', '/', 'routes/layout.jinja', 'app/routes/layout.jinja:1:1', 'none', 'app/routes/layout.py:1:1', 'none', 'none'), ('layout', 'page', '/main/regional/offices/{office_id}/teams/{team_id}/customers/{customer_id}/report', 'mounts/customer_report/layout.jinja', 'app/mounts/customer_report/layout.jinja:1:1', 'none', 'app/mounts/customer_report/layout.py:1:1', 'none', 'customer_report:/')), ()),
        },
        parameters=('office_id', 'team_id', 'customer_id'),
        environment=selected_environment,
        template_inspection=selected_template_inspection,
    )
    endpoint_18 = _build_endpoint(
        handlers={
            'GET': _handler_18,
        },
        creators={
            'GET': _creator_18,
        },
        navigation={'GET': (('Home', None, '/', False), ('Main', None, '/main', False), ('Regional', None, '/main/regional', False), (None, 'office', '/main/regional/offices/{office_id}', False), (None, 'team', '/main/regional/offices/{office_id}/teams/{team_id}', False), (None, 'customer', '/main/regional/offices/{office_id}/teams/{team_id}/customers/{customer_id}', False), ('Report', None, '/main/regional/offices/{office_id}/teams/{team_id}/customers/{customer_id}/report', False), ('Brief', None, '/main/regional/offices/{office_id}/teams/{team_id}/customers/{customer_id}/report/brief', True))},
        evidence={
            'GET': ('page', '/main/regional/offices/{office_id}/teams/{team_id}/customers/{customer_id}/report/brief', ('GET', 'HEAD'), 'app/mounts/customer_report/brief/route.py', 1, 1, 'app.mounts.customer_report.handlers', 'brief', 'brief', 'app/routes/main/regional/offices/by_office_id/teams/by_team_id/customers/by_customer_id/report/route.py', 'customer_report', '/brief', 1, 1, '/main/regional/offices/{office_id}/teams/{team_id}/customers/{customer_id}/report'),
        },
        embedded_expectations={
            'GET': (),
        },
        rendering={
            'GET': (('mounts/customer_report/brief/page.jinja', 'app/mounts/customer_report/brief/page.jinja', 1, 1, None, ('app/mounts/customer_report/brief/route.py', 7, 14)), (('app/routes/layout.py', 1, 1, '/', ('routes/layout.jinja', 'app/routes/layout.jinja', 1, 1, None, None)), ('app/mounts/customer_report/layout.py', 1, 1, '/', ('mounts/customer_report/layout.jinja', 'app/mounts/customer_report/layout.jinja', 1, 1, None, None))), ('page', 'page', '/main/regional/offices/{office_id}/teams/{team_id}/customers/{customer_id}/report/brief', 'mounts/customer_report/brief/page.jinja', 'app/mounts/customer_report/brief/page.jinja:1:1', 'app/mounts/customer_report/brief/route.py:7:14', 'app/routes/main/regional/offices/by_office_id/teams/by_team_id/customers/by_customer_id/report/route.py:1:1', 'app.mounts.customer_report.handlers:brief', 'customer_report:/brief'), (('layout', 'page', '/', 'routes/layout.jinja', 'app/routes/layout.jinja:1:1', 'none', 'app/routes/layout.py:1:1', 'none', 'none'), ('layout', 'page', '/main/regional/offices/{office_id}/teams/{team_id}/customers/{customer_id}/report', 'mounts/customer_report/layout.jinja', 'app/mounts/customer_report/layout.jinja:1:1', 'none', 'app/mounts/customer_report/layout.py:1:1', 'none', 'customer_report:/brief')), ()),
        },
        parameters=('office_id', 'team_id', 'customer_id'),
        environment=selected_environment,
        template_inspection=selected_template_inspection,
    )
    endpoint_19 = _build_endpoint(
        handlers={
            'GET': _handler_19,
        },
        creators={
            'GET': _creator_19,
        },
        navigation={'GET': (('Home', None, '/', False), ('Main', None, '/main', False), ('Regional', None, '/main/regional', False), (None, 'office', '/main/regional/offices/{office_id}', False), (None, 'team', '/main/regional/offices/{office_id}/teams/{team_id}', False), (None, 'customer', '/main/regional/offices/{office_id}/teams/{team_id}/customers/{customer_id}', False), ('Report', None, '/main/regional/offices/{office_id}/teams/{team_id}/customers/{customer_id}/report', False), ('Detailed', None, '/main/regional/offices/{office_id}/teams/{team_id}/customers/{customer_id}/report/detailed', True))},
        evidence={
            'GET': ('page', '/main/regional/offices/{office_id}/teams/{team_id}/customers/{customer_id}/report/detailed', ('GET', 'HEAD'), 'app/mounts/customer_report/detailed/route.py', 1, 1, 'app.mounts.customer_report.handlers', 'detailed', 'detailed', 'app/routes/main/regional/offices/by_office_id/teams/by_team_id/customers/by_customer_id/report/route.py', 'customer_report', '/detailed', 1, 1, '/main/regional/offices/{office_id}/teams/{team_id}/customers/{customer_id}/report'),
        },
        embedded_expectations={
            'GET': (),
        },
        rendering={
            'GET': (('mounts/customer_report/detailed/page.jinja', 'app/mounts/customer_report/detailed/page.jinja', 1, 1, None, ('app/mounts/customer_report/detailed/route.py', 7, 14)), (('app/routes/layout.py', 1, 1, '/', ('routes/layout.jinja', 'app/routes/layout.jinja', 1, 1, None, None)), ('app/mounts/customer_report/layout.py', 1, 1, '/', ('mounts/customer_report/layout.jinja', 'app/mounts/customer_report/layout.jinja', 1, 1, None, None))), ('page', 'page', '/main/regional/offices/{office_id}/teams/{team_id}/customers/{customer_id}/report/detailed', 'mounts/customer_report/detailed/page.jinja', 'app/mounts/customer_report/detailed/page.jinja:1:1', 'app/mounts/customer_report/detailed/route.py:7:14', 'app/routes/main/regional/offices/by_office_id/teams/by_team_id/customers/by_customer_id/report/route.py:1:1', 'app.mounts.customer_report.handlers:detailed', 'customer_report:/detailed'), (('layout', 'page', '/', 'routes/layout.jinja', 'app/routes/layout.jinja:1:1', 'none', 'app/routes/layout.py:1:1', 'none', 'none'), ('layout', 'page', '/main/regional/offices/{office_id}/teams/{team_id}/customers/{customer_id}/report', 'mounts/customer_report/layout.jinja', 'app/mounts/customer_report/layout.jinja:1:1', 'none', 'app/mounts/customer_report/layout.py:1:1', 'none', 'customer_report:/detailed')), ()),
        },
        parameters=('office_id', 'team_id', 'customer_id'),
        environment=selected_environment,
        template_inspection=selected_template_inspection,
    )
    endpoint_20 = _build_endpoint(
        handlers={
            'GET': _handler_20,
        },
        navigation={'GET': (('Home', None, '/', False), ('Main', None, '/main', False), ('Report', None, '/main/reports/{customer_id}', True))},
        trail_keys={'GET': ('hq-customer', 'regional-customer')},
        evidence={
            'GET': ('page', '/main/reports/{customer_id}', ('GET', 'HEAD'), 'app/routes/main/reports/by_customer_id/route.py', 1, 1, 'app.routes.main.reports.by_customer_id.route', 'page', 'page', 'app/routes/main/reports/by_customer_id/route.py', None, None, 1, 1, '/main/reports/{customer_id}'),
        },
        embedded_expectations={
            'GET': (),
        },
        rendering={
            'GET': (('routes/main/reports/by_customer_id/page.jinja', 'app/routes/main/reports/by_customer_id/page.jinja', 1, 1, None, ('app/routes/main/reports/by_customer_id/route.py', 78, 14)), (('app/routes/layout.py', 1, 1, '/', ('routes/layout.jinja', 'app/routes/layout.jinja', 1, 1, None, None)),), ('page', 'page', '/main/reports/{customer_id}', 'routes/main/reports/by_customer_id/page.jinja', 'app/routes/main/reports/by_customer_id/page.jinja:1:1', 'app/routes/main/reports/by_customer_id/route.py:78:14', 'app/routes/main/reports/by_customer_id/route.py:1:1', 'app.routes.main.reports.by_customer_id.route:page', 'none'), (('layout', 'page', '/', 'routes/layout.jinja', 'app/routes/layout.jinja:1:1', 'none', 'app/routes/layout.py:1:1', 'none', 'none'),), ()),
        },
        parameters=('customer_id',),
        environment=selected_environment,
        template_inspection=selected_template_inspection,
    )
    _generated_routes: list[_Route] = [
            _Route(
                '/',
                endpoint_0,
                methods=['GET', 'HEAD'],
                error_handler=selected_error_handler,
                error_evidence={'GET': ('page', '/', ('GET', 'HEAD'), 'app/routes/route.py', 1, 1, 'app.routes.route', 'page', 'page', 'app/routes/route.py', None, None, 1, 1, '/')},
                error_templates=(None, None),
            ),
            _Route(
                '/about',
                endpoint_1,
                methods=['GET', 'HEAD'],
                error_handler=selected_error_handler,
                error_evidence={'GET': ('page', '/about', ('GET', 'HEAD'), 'app/routes/about/route.py', 1, 1, 'app.routes.about.route', 'page', 'page', 'app/routes/about/route.py', None, None, 1, 1, '/about')},
                error_templates=(None, None),
            ),
            _Route(
                '/main',
                endpoint_2,
                methods=['GET', 'HEAD'],
                error_handler=selected_error_handler,
                error_evidence={'GET': ('page', '/main', ('GET', 'HEAD'), 'app/routes/main/route.py', 1, 1, 'app.routes.main.route', 'page', 'page', 'app/routes/main/route.py', None, None, 1, 1, '/main')},
                error_templates=(None, None),
            ),
            _Route(
                '/main/hq',
                endpoint_3,
                methods=['GET', 'HEAD'],
                error_handler=selected_error_handler,
                error_evidence={'GET': ('page', '/main/hq', ('GET', 'HEAD'), 'app/routes/main/hq/route.py', 1, 1, 'app.routes.main.hq.route', 'page', 'page', 'app/routes/main/hq/route.py', None, None, 1, 1, '/main/hq')},
                error_templates=(None, None),
            ),
            _Route(
                '/main/hq/teams/{team_id}',
                endpoint_4,
                methods=['GET', 'HEAD'],
                error_handler=selected_error_handler,
                error_evidence={'GET': ('page', '/main/hq/teams/{team_id}', ('GET', 'HEAD'), 'app/routes/main/hq/teams/by_team_id/route.py', 1, 1, 'app.routes.main.hq.teams.by_team_id.route', 'page', 'page', 'app/routes/main/hq/teams/by_team_id/route.py', None, None, 1, 1, '/main/hq/teams/{team_id}')},
                error_templates=(None, None),
            ),
            _Route(
                '/main/hq/teams/{team_id}/analytics',
                endpoint_5,
                methods=['GET', 'HEAD'],
                error_handler=selected_error_handler,
                error_evidence={'GET': ('page', '/main/hq/teams/{team_id}/analytics', ('GET', 'HEAD'), 'app/mounts/analytics/route.py', 1, 1, 'app.mounts.analytics.handlers', 'page', 'page', 'app/routes/main/hq/teams/by_team_id/analytics/route.py', 'analytics', '/', 1, 1, '/main/hq/teams/{team_id}/analytics')},
                error_templates=(None, None),
            ),
            _Route(
                '/main/hq/teams/{team_id}/analytics/customers/{customer_id}/report',
                endpoint_6,
                methods=['GET', 'HEAD'],
                error_handler=selected_error_handler,
                error_evidence={'GET': ('page', '/main/hq/teams/{team_id}/analytics/customers/{customer_id}/report', ('GET', 'HEAD'), 'app/mounts/analytics/customers/by_customer_id/report/route.py', 1, 1, 'app.mounts.analytics.customers.by_customer_id.report.handlers', 'page', 'page', 'app/routes/main/hq/teams/by_team_id/analytics/route.py', 'analytics', '/customers/{customer_id}/report', 1, 1, '/main/hq/teams/{team_id}/analytics')},
                error_templates=(None, None),
            ),
            _Route(
                '/main/hq/teams/{team_id}/customers/{customer_id}',
                endpoint_7,
                methods=['GET', 'HEAD'],
                error_handler=selected_error_handler,
                error_evidence={'GET': ('page', '/main/hq/teams/{team_id}/customers/{customer_id}', ('GET', 'HEAD'), 'app/routes/main/hq/teams/by_team_id/customers/by_customer_id/route.py', 1, 1, 'app.routes.main.hq.teams.by_team_id.customers.by_customer_id.route', 'page', 'page', 'app/routes/main/hq/teams/by_team_id/customers/by_customer_id/route.py', None, None, 1, 1, '/main/hq/teams/{team_id}/customers/{customer_id}')},
                error_templates=(None, None),
            ),
            _Route(
                '/main/hq/teams/{team_id}/customers/{customer_id}/report',
                endpoint_8,
                methods=['GET', 'HEAD'],
                error_handler=selected_error_handler,
                error_evidence={'GET': ('page', '/main/hq/teams/{team_id}/customers/{customer_id}/report', ('GET', 'HEAD'), 'app/mounts/customer_report/route.py', 1, 1, 'app.mounts.customer_report.handlers', 'page', 'page', 'app/routes/main/hq/teams/by_team_id/customers/by_customer_id/report/route.py', 'customer_report', '/', 1, 1, '/main/hq/teams/{team_id}/customers/{customer_id}/report')},
                error_templates=(None, None),
            ),
            _Route(
                '/main/hq/teams/{team_id}/customers/{customer_id}/report/brief',
                endpoint_9,
                methods=['GET', 'HEAD'],
                error_handler=selected_error_handler,
                error_evidence={'GET': ('page', '/main/hq/teams/{team_id}/customers/{customer_id}/report/brief', ('GET', 'HEAD'), 'app/mounts/customer_report/brief/route.py', 1, 1, 'app.mounts.customer_report.handlers', 'brief', 'brief', 'app/routes/main/hq/teams/by_team_id/customers/by_customer_id/report/route.py', 'customer_report', '/brief', 1, 1, '/main/hq/teams/{team_id}/customers/{customer_id}/report')},
                error_templates=(None, None),
            ),
            _Route(
                '/main/hq/teams/{team_id}/customers/{customer_id}/report/detailed',
                endpoint_10,
                methods=['GET', 'HEAD'],
                error_handler=selected_error_handler,
                error_evidence={'GET': ('page', '/main/hq/teams/{team_id}/customers/{customer_id}/report/detailed', ('GET', 'HEAD'), 'app/mounts/customer_report/detailed/route.py', 1, 1, 'app.mounts.customer_report.handlers', 'detailed', 'detailed', 'app/routes/main/hq/teams/by_team_id/customers/by_customer_id/report/route.py', 'customer_report', '/detailed', 1, 1, '/main/hq/teams/{team_id}/customers/{customer_id}/report')},
                error_templates=(None, None),
            ),
            _Route(
                '/main/regional',
                endpoint_11,
                methods=['GET', 'HEAD'],
                error_handler=selected_error_handler,
                error_evidence={'GET': ('page', '/main/regional', ('GET', 'HEAD'), 'app/routes/main/regional/route.py', 1, 1, 'app.routes.main.regional.route', 'page', 'page', 'app/routes/main/regional/route.py', None, None, 1, 1, '/main/regional')},
                error_templates=(None, None),
            ),
            _Route(
                '/main/regional/offices/{office_id}',
                endpoint_12,
                methods=['GET', 'HEAD'],
                error_handler=selected_error_handler,
                error_evidence={'GET': ('page', '/main/regional/offices/{office_id}', ('GET', 'HEAD'), 'app/routes/main/regional/offices/by_office_id/route.py', 1, 1, 'app.routes.main.regional.offices.by_office_id.route', 'page', 'page', 'app/routes/main/regional/offices/by_office_id/route.py', None, None, 1, 1, '/main/regional/offices/{office_id}')},
                error_templates=(None, None),
            ),
            _Route(
                '/main/regional/offices/{office_id}/teams/{team_id}',
                endpoint_13,
                methods=['GET', 'HEAD'],
                error_handler=selected_error_handler,
                error_evidence={'GET': ('page', '/main/regional/offices/{office_id}/teams/{team_id}', ('GET', 'HEAD'), 'app/routes/main/regional/offices/by_office_id/teams/by_team_id/route.py', 1, 1, 'app.routes.main.regional.offices.by_office_id.teams.by_team_id.route', 'page', 'page', 'app/routes/main/regional/offices/by_office_id/teams/by_team_id/route.py', None, None, 1, 1, '/main/regional/offices/{office_id}/teams/{team_id}')},
                error_templates=(None, None),
            ),
            _Route(
                '/main/regional/offices/{office_id}/teams/{team_id}/analytics',
                endpoint_14,
                methods=['GET', 'HEAD'],
                error_handler=selected_error_handler,
                error_evidence={'GET': ('page', '/main/regional/offices/{office_id}/teams/{team_id}/analytics', ('GET', 'HEAD'), 'app/mounts/analytics/route.py', 1, 1, 'app.mounts.analytics.handlers', 'page', 'page', 'app/routes/main/regional/offices/by_office_id/teams/by_team_id/analytics/route.py', 'analytics', '/', 1, 1, '/main/regional/offices/{office_id}/teams/{team_id}/analytics')},
                error_templates=(None, None),
            ),
            _Route(
                '/main/regional/offices/{office_id}/teams/{team_id}/analytics/customers/{customer_id}/report',
                endpoint_15,
                methods=['GET', 'HEAD'],
                error_handler=selected_error_handler,
                error_evidence={'GET': ('page', '/main/regional/offices/{office_id}/teams/{team_id}/analytics/customers/{customer_id}/report', ('GET', 'HEAD'), 'app/mounts/analytics/customers/by_customer_id/report/route.py', 1, 1, 'app.mounts.analytics.customers.by_customer_id.report.handlers', 'page', 'page', 'app/routes/main/regional/offices/by_office_id/teams/by_team_id/analytics/route.py', 'analytics', '/customers/{customer_id}/report', 1, 1, '/main/regional/offices/{office_id}/teams/{team_id}/analytics')},
                error_templates=(None, None),
            ),
            _Route(
                '/main/regional/offices/{office_id}/teams/{team_id}/customers/{customer_id}',
                endpoint_16,
                methods=['GET', 'HEAD'],
                error_handler=selected_error_handler,
                error_evidence={'GET': ('page', '/main/regional/offices/{office_id}/teams/{team_id}/customers/{customer_id}', ('GET', 'HEAD'), 'app/routes/main/regional/offices/by_office_id/teams/by_team_id/customers/by_customer_id/route.py', 1, 1, 'app.routes.main.regional.offices.by_office_id.teams.by_team_id.customers.by_customer_id.route', 'page', 'page', 'app/routes/main/regional/offices/by_office_id/teams/by_team_id/customers/by_customer_id/route.py', None, None, 1, 1, '/main/regional/offices/{office_id}/teams/{team_id}/customers/{customer_id}')},
                error_templates=(None, None),
            ),
            _Route(
                '/main/regional/offices/{office_id}/teams/{team_id}/customers/{customer_id}/report',
                endpoint_17,
                methods=['GET', 'HEAD'],
                error_handler=selected_error_handler,
                error_evidence={'GET': ('page', '/main/regional/offices/{office_id}/teams/{team_id}/customers/{customer_id}/report', ('GET', 'HEAD'), 'app/mounts/customer_report/route.py', 1, 1, 'app.mounts.customer_report.handlers', 'page', 'page', 'app/routes/main/regional/offices/by_office_id/teams/by_team_id/customers/by_customer_id/report/route.py', 'customer_report', '/', 1, 1, '/main/regional/offices/{office_id}/teams/{team_id}/customers/{customer_id}/report')},
                error_templates=(None, None),
            ),
            _Route(
                '/main/regional/offices/{office_id}/teams/{team_id}/customers/{customer_id}/report/brief',
                endpoint_18,
                methods=['GET', 'HEAD'],
                error_handler=selected_error_handler,
                error_evidence={'GET': ('page', '/main/regional/offices/{office_id}/teams/{team_id}/customers/{customer_id}/report/brief', ('GET', 'HEAD'), 'app/mounts/customer_report/brief/route.py', 1, 1, 'app.mounts.customer_report.handlers', 'brief', 'brief', 'app/routes/main/regional/offices/by_office_id/teams/by_team_id/customers/by_customer_id/report/route.py', 'customer_report', '/brief', 1, 1, '/main/regional/offices/{office_id}/teams/{team_id}/customers/{customer_id}/report')},
                error_templates=(None, None),
            ),
            _Route(
                '/main/regional/offices/{office_id}/teams/{team_id}/customers/{customer_id}/report/detailed',
                endpoint_19,
                methods=['GET', 'HEAD'],
                error_handler=selected_error_handler,
                error_evidence={'GET': ('page', '/main/regional/offices/{office_id}/teams/{team_id}/customers/{customer_id}/report/detailed', ('GET', 'HEAD'), 'app/mounts/customer_report/detailed/route.py', 1, 1, 'app.mounts.customer_report.handlers', 'detailed', 'detailed', 'app/routes/main/regional/offices/by_office_id/teams/by_team_id/customers/by_customer_id/report/route.py', 'customer_report', '/detailed', 1, 1, '/main/regional/offices/{office_id}/teams/{team_id}/customers/{customer_id}/report')},
                error_templates=(None, None),
            ),
            _Route(
                '/main/reports/{customer_id}',
                endpoint_20,
                methods=['GET', 'HEAD'],
                error_handler=selected_error_handler,
                error_evidence={'GET': ('page', '/main/reports/{customer_id}', ('GET', 'HEAD'), 'app/routes/main/reports/by_customer_id/route.py', 1, 1, 'app.routes.main.reports.by_customer_id.route', 'page', 'page', 'app/routes/main/reports/by_customer_id/route.py', None, None, 1, 1, '/main/reports/{customer_id}')},
                error_templates=(None, None),
            ),
    ]
    if selected_error_handler is None:
        return _Router(
            routes=_generated_routes,
            redirect_slashes=False,
        )
    return _ErrorRouter(
        routes=_generated_routes,
        redirect_slashes=False,
        error_handler=selected_error_handler,
    )


router: _Router = create_router()
