# Code generated by pyganini; DO NOT EDIT.
# pyright: reportPrivateUsage=false, reportUnusedClass=false
"""Generated Pyganini URL helper interface."""

from __future__ import annotations

from dataclasses import dataclass as _dataclass
from typing import overload as _overload
from urllib.parse import quote as _quote

from pyganini import Navigation as _Navigation
from pyganini._navigation import _navigation_href
from pyganini._url_binding import quote_segment as _quote_segment

__all__ = ("mount_urls", "urls")

def _normalize_base_path(base_path: object) -> str:
    if not isinstance(base_path, str):
        raise TypeError("base_path must be str")
    if base_path in {"", "/"}:
        return ""
    if all(character == "/" for character in base_path):
        raise ValueError("base_path must not contain empty path segments")
    normalized = base_path if base_path.startswith("/") else "/" + base_path
    normalized = normalized.rstrip("/")
    segments = normalized[1:].split("/")
    if any(segment == "" for segment in segments):
        raise ValueError("base_path must not contain empty path segments")
    quoted = tuple(
        _quote_segment(f"base_path segment {index}", segment)
        for index, segment in enumerate(segments, start=1)
    )
    return "/" + "/".join(quoted)

def _add_trail_key(path: str, key: str) -> str:
    return path + ("&" if "?" in path else "?") + "_pyganini_nav_trail_key=" + _quote(key, safe="")

@_dataclass(frozen=True, slots=True)
class _URLRootPath:
    _base_path: str
    _owner_key: str | None

    @property
    def path(self) -> str:
        return self._base_path + "/"

    @property
    def route_pattern(self) -> str:
        return "/"


@_dataclass(frozen=True, slots=True)
class _URLNode0:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/'

    def with_base_path(self, base_path: str) -> _URLNode0:
        """Return this surface bound to a decoded path prefix."""
        return _URLNode0(_normalize_base_path(base_path), "", self._owner_key)

    @property
    def root(self) -> _URLRootPath:
        return _URLRootPath(self._base_path, self._owner_key)

    @property
    def about(self) -> _URLNode1:
        return _URLNode1(
            self._base_path,
            self._local_path + '/about',
            None,
        )

    @property
    def main(self) -> _URLNode2:
        return _URLNode2(
            self._base_path,
            self._local_path + '/main',
            None,
        )


@_dataclass(frozen=True, slots=True)
class _URLNode1:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/about'

    @property
    def path(self) -> str:
        return self._base_path + self._local_path


@_dataclass(frozen=True, slots=True)
class _URLNode2:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/main'

    @property
    def path(self) -> str:
        return self._base_path + self._local_path

    @property
    def hq(self) -> _URLNode3:
        return _URLNode3(
            self._base_path,
            self._local_path + '/hq',
            None,
        )

    @property
    def regional(self) -> _URLNode15:
        return _URLNode15(
            self._base_path,
            self._local_path + '/regional',
            None,
        )

    @property
    def reports(self) -> _URLNode29:
        return _URLNode29(
            self._base_path,
            self._local_path + '/reports',
            None,
        )


@_dataclass(frozen=True, slots=True)
class _URLNode3:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/main/hq'

    @property
    def path(self) -> str:
        return self._base_path + self._local_path

    @property
    def teams(self) -> _URLNode4:
        return _URLNode4(
            self._base_path,
            self._local_path + '/teams',
            None,
        )


@_dataclass(frozen=True, slots=True)
class _URLNode4:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/main/hq/teams'

    @property
    def by_team_id(self) -> _URLTarget5:
        return _URLTarget5(
            self._base_path,
            self._local_path,
            None,
        )


@_dataclass(frozen=True, slots=True)
class _URLNode5:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/main/hq/teams/{team_id}'

    @property
    def path(self) -> str:
        return self._base_path + self._local_path

    @property
    def analytics(self) -> _URLNode6:
        return _URLNode6(
            self._base_path,
            self._local_path + '/analytics',
            'app/routes/main/hq/teams/by_team_id/analytics/route.py',
        )

    @property
    def customers(self) -> _URLNode10:
        return _URLNode10(
            self._base_path,
            self._local_path + '/customers',
            None,
        )


@_dataclass(frozen=True, slots=True)
class _URLNode6:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/main/hq/teams/{team_id}/analytics'

    @property
    def path(self) -> str:
        return self._base_path + self._local_path

    @property
    def destinations(self) -> _Destinations6:
        return _Destinations6(self._base_path)

    @property
    def customers(self) -> _URLNode7:
        return _URLNode7(
            self._base_path,
            self._local_path + '/customers',
            None,
        )


@_dataclass(frozen=True, slots=True)
class _URLNode7:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/main/hq/teams/{team_id}/analytics/customers'

    @property
    def by_customer_id(self) -> _URLTarget8:
        return _URLTarget8(
            self._base_path,
            self._local_path,
            None,
        )


@_dataclass(frozen=True, slots=True)
class _URLNode8:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/main/hq/teams/{team_id}/analytics/customers/{customer_id}'

    @property
    def report(self) -> _URLNode9:
        return _URLNode9(
            self._base_path,
            self._local_path + '/report',
            None,
        )


@_dataclass(frozen=True, slots=True)
class _URLNode9:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/main/hq/teams/{team_id}/analytics/customers/{customer_id}/report'

    @property
    def path(self) -> str:
        return self._base_path + self._local_path

    @property
    def trail_keys(self) -> _TrailKeys9:
        return _TrailKeys9()


@_dataclass(frozen=True, slots=True)
class _URLNode10:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/main/hq/teams/{team_id}/customers'

    @property
    def by_customer_id(self) -> _URLTarget11:
        return _URLTarget11(
            self._base_path,
            self._local_path,
            None,
        )


@_dataclass(frozen=True, slots=True)
class _URLNode11:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/main/hq/teams/{team_id}/customers/{customer_id}'

    @property
    def path(self) -> str:
        return self._base_path + self._local_path

    @property
    def destinations(self) -> _Destinations11:
        return _Destinations11(self._base_path)

    @property
    def report(self) -> _URLNode12:
        return _URLNode12(
            self._base_path,
            self._local_path + '/report',
            'app/routes/main/hq/teams/by_team_id/customers/by_customer_id/report/route.py',
        )


@_dataclass(frozen=True, slots=True)
class _URLNode12:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/main/hq/teams/{team_id}/customers/{customer_id}/report'

    @property
    def path(self) -> str:
        return self._base_path + self._local_path

    @property
    def brief(self) -> _URLNode13:
        return _URLNode13(
            self._base_path,
            self._local_path + '/brief',
            None,
        )

    @property
    def detailed(self) -> _URLNode14:
        return _URLNode14(
            self._base_path,
            self._local_path + '/detailed',
            None,
        )


@_dataclass(frozen=True, slots=True)
class _URLNode13:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/main/hq/teams/{team_id}/customers/{customer_id}/report/brief'

    @property
    def path(self) -> str:
        return self._base_path + self._local_path


@_dataclass(frozen=True, slots=True)
class _URLNode14:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/main/hq/teams/{team_id}/customers/{customer_id}/report/detailed'

    @property
    def path(self) -> str:
        return self._base_path + self._local_path


@_dataclass(frozen=True, slots=True)
class _URLNode15:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/main/regional'

    @property
    def path(self) -> str:
        return self._base_path + self._local_path

    @property
    def offices(self) -> _URLNode16:
        return _URLNode16(
            self._base_path,
            self._local_path + '/offices',
            None,
        )


@_dataclass(frozen=True, slots=True)
class _URLNode16:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/main/regional/offices'

    @property
    def by_office_id(self) -> _URLTarget17:
        return _URLTarget17(
            self._base_path,
            self._local_path,
            None,
        )


@_dataclass(frozen=True, slots=True)
class _URLNode17:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/main/regional/offices/{office_id}'

    @property
    def path(self) -> str:
        return self._base_path + self._local_path

    @property
    def teams(self) -> _URLNode18:
        return _URLNode18(
            self._base_path,
            self._local_path + '/teams',
            None,
        )


@_dataclass(frozen=True, slots=True)
class _URLNode18:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/main/regional/offices/{office_id}/teams'

    @property
    def by_team_id(self) -> _URLTarget19:
        return _URLTarget19(
            self._base_path,
            self._local_path,
            None,
        )


@_dataclass(frozen=True, slots=True)
class _URLNode19:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/main/regional/offices/{office_id}/teams/{team_id}'

    @property
    def path(self) -> str:
        return self._base_path + self._local_path

    @property
    def analytics(self) -> _URLNode20:
        return _URLNode20(
            self._base_path,
            self._local_path + '/analytics',
            'app/routes/main/regional/offices/by_office_id/teams/by_team_id/analytics/route.py',
        )

    @property
    def customers(self) -> _URLNode24:
        return _URLNode24(
            self._base_path,
            self._local_path + '/customers',
            None,
        )


@_dataclass(frozen=True, slots=True)
class _URLNode20:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/main/regional/offices/{office_id}/teams/{team_id}/analytics'

    @property
    def path(self) -> str:
        return self._base_path + self._local_path

    @property
    def destinations(self) -> _Destinations20:
        return _Destinations20(self._base_path)

    @property
    def customers(self) -> _URLNode21:
        return _URLNode21(
            self._base_path,
            self._local_path + '/customers',
            None,
        )


@_dataclass(frozen=True, slots=True)
class _URLNode21:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/main/regional/offices/{office_id}/teams/{team_id}/analytics/customers'

    @property
    def by_customer_id(self) -> _URLTarget22:
        return _URLTarget22(
            self._base_path,
            self._local_path,
            None,
        )


@_dataclass(frozen=True, slots=True)
class _URLNode22:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/main/regional/offices/{office_id}/teams/{team_id}/analytics/customers/{customer_id}'

    @property
    def report(self) -> _URLNode23:
        return _URLNode23(
            self._base_path,
            self._local_path + '/report',
            None,
        )


@_dataclass(frozen=True, slots=True)
class _URLNode23:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/main/regional/offices/{office_id}/teams/{team_id}/analytics/customers/{customer_id}/report'

    @property
    def path(self) -> str:
        return self._base_path + self._local_path

    @property
    def trail_keys(self) -> _TrailKeys23:
        return _TrailKeys23()


@_dataclass(frozen=True, slots=True)
class _URLNode24:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/main/regional/offices/{office_id}/teams/{team_id}/customers'

    @property
    def by_customer_id(self) -> _URLTarget25:
        return _URLTarget25(
            self._base_path,
            self._local_path,
            None,
        )


@_dataclass(frozen=True, slots=True)
class _URLNode25:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/main/regional/offices/{office_id}/teams/{team_id}/customers/{customer_id}'

    @property
    def path(self) -> str:
        return self._base_path + self._local_path

    @property
    def destinations(self) -> _Destinations25:
        return _Destinations25(self._base_path)

    @property
    def report(self) -> _URLNode26:
        return _URLNode26(
            self._base_path,
            self._local_path + '/report',
            'app/routes/main/regional/offices/by_office_id/teams/by_team_id/customers/by_customer_id/report/route.py',
        )


@_dataclass(frozen=True, slots=True)
class _URLNode26:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/main/regional/offices/{office_id}/teams/{team_id}/customers/{customer_id}/report'

    @property
    def path(self) -> str:
        return self._base_path + self._local_path

    @property
    def brief(self) -> _URLNode27:
        return _URLNode27(
            self._base_path,
            self._local_path + '/brief',
            None,
        )

    @property
    def detailed(self) -> _URLNode28:
        return _URLNode28(
            self._base_path,
            self._local_path + '/detailed',
            None,
        )


@_dataclass(frozen=True, slots=True)
class _URLNode27:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/main/regional/offices/{office_id}/teams/{team_id}/customers/{customer_id}/report/brief'

    @property
    def path(self) -> str:
        return self._base_path + self._local_path


@_dataclass(frozen=True, slots=True)
class _URLNode28:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/main/regional/offices/{office_id}/teams/{team_id}/customers/{customer_id}/report/detailed'

    @property
    def path(self) -> str:
        return self._base_path + self._local_path


@_dataclass(frozen=True, slots=True)
class _URLNode29:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/main/reports'

    @property
    def by_customer_id(self) -> _URLTarget30:
        return _URLTarget30(
            self._base_path,
            self._local_path,
            None,
        )


@_dataclass(frozen=True, slots=True)
class _URLNode30:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/main/reports/{customer_id}'

    @property
    def path(self) -> str:
        return self._base_path + self._local_path

    @property
    def trail_keys(self) -> _TrailKeys30:
        return _TrailKeys30()


@_dataclass(frozen=True, slots=True)
class _URLTarget0:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/'

    @property
    def about(self) -> _URLUnboundTarget1:
        return _URLUnboundTarget1(
            self._base_path,
            self._local_path + '/about',
            None,
        )

    @property
    def main(self) -> _URLUnboundTarget2:
        return _URLUnboundTarget2(
            self._base_path,
            self._local_path + '/main',
            None,
        )


@_dataclass(frozen=True, slots=True)
class _URLTarget1:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/about'
    pass


@_dataclass(frozen=True, slots=True)
class _URLTarget2:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/main'

    @property
    def hq(self) -> _URLUnboundTarget3:
        return _URLUnboundTarget3(
            self._base_path,
            self._local_path + '/hq',
            None,
        )

    @property
    def regional(self) -> _URLUnboundTarget15:
        return _URLUnboundTarget15(
            self._base_path,
            self._local_path + '/regional',
            None,
        )

    @property
    def reports(self) -> _URLUnboundTarget29:
        return _URLUnboundTarget29(
            self._base_path,
            self._local_path + '/reports',
            None,
        )


@_dataclass(frozen=True, slots=True)
class _URLTarget3:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/main/hq'

    @property
    def teams(self) -> _URLUnboundTarget4:
        return _URLUnboundTarget4(
            self._base_path,
            self._local_path + '/teams',
            None,
        )


@_dataclass(frozen=True, slots=True)
class _URLTarget4:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/main/hq/teams'

    @property
    def by_team_id(self) -> _URLUnboundTarget5:
        return _URLUnboundTarget5(
            self._base_path,
            self._local_path,
            None,
        )


@_dataclass(frozen=True, slots=True)
class _URLTarget5:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/main/hq/teams/{team_id}'

    def __call__(self, team_id: str) -> _URLNode5:
        encoded = _quote_segment("parameter 'team_id'", team_id)
        return _URLNode5(
            self._base_path,
            self._local_path + "/" + encoded,
            self._owner_key,
        )

    @property
    def analytics(self) -> _URLUnboundTarget6:
        return _URLUnboundTarget6(
            self._base_path,
            self._local_path + '/analytics',
            'app/routes/main/hq/teams/by_team_id/analytics/route.py',
        )

    @property
    def customers(self) -> _URLUnboundTarget10:
        return _URLUnboundTarget10(
            self._base_path,
            self._local_path + '/customers',
            None,
        )


@_dataclass(frozen=True, slots=True)
class _URLTarget6:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/main/hq/teams/{team_id}/analytics'

    @property
    def customers(self) -> _URLUnboundTarget7:
        return _URLUnboundTarget7(
            self._base_path,
            self._local_path + '/customers',
            None,
        )


@_dataclass(frozen=True, slots=True)
class _URLTarget7:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/main/hq/teams/{team_id}/analytics/customers'

    @property
    def by_customer_id(self) -> _URLUnboundTarget8:
        return _URLUnboundTarget8(
            self._base_path,
            self._local_path,
            None,
        )


@_dataclass(frozen=True, slots=True)
class _URLTarget8:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/main/hq/teams/{team_id}/analytics/customers/{customer_id}'

    def __call__(self, customer_id: str) -> _URLNode8:
        encoded = _quote_segment("parameter 'customer_id'", customer_id)
        return _URLNode8(
            self._base_path,
            self._local_path + "/" + encoded,
            self._owner_key,
        )

    @property
    def report(self) -> _URLUnboundTarget9:
        return _URLUnboundTarget9(
            self._base_path,
            self._local_path + '/report',
            None,
        )


@_dataclass(frozen=True, slots=True)
class _URLTarget9:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/main/hq/teams/{team_id}/analytics/customers/{customer_id}/report'

    @property
    def trail_keys(self) -> _TrailKeys9:
        return _TrailKeys9()
    pass


@_dataclass(frozen=True, slots=True)
class _URLTarget10:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/main/hq/teams/{team_id}/customers'

    @property
    def by_customer_id(self) -> _URLUnboundTarget11:
        return _URLUnboundTarget11(
            self._base_path,
            self._local_path,
            None,
        )


@_dataclass(frozen=True, slots=True)
class _URLTarget11:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/main/hq/teams/{team_id}/customers/{customer_id}'

    def __call__(self, customer_id: str) -> _URLNode11:
        encoded = _quote_segment("parameter 'customer_id'", customer_id)
        return _URLNode11(
            self._base_path,
            self._local_path + "/" + encoded,
            self._owner_key,
        )

    @property
    def report(self) -> _URLUnboundTarget12:
        return _URLUnboundTarget12(
            self._base_path,
            self._local_path + '/report',
            'app/routes/main/hq/teams/by_team_id/customers/by_customer_id/report/route.py',
        )


@_dataclass(frozen=True, slots=True)
class _URLTarget12:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/main/hq/teams/{team_id}/customers/{customer_id}/report'

    @property
    def brief(self) -> _URLUnboundTarget13:
        return _URLUnboundTarget13(
            self._base_path,
            self._local_path + '/brief',
            None,
        )

    @property
    def detailed(self) -> _URLUnboundTarget14:
        return _URLUnboundTarget14(
            self._base_path,
            self._local_path + '/detailed',
            None,
        )


@_dataclass(frozen=True, slots=True)
class _URLTarget13:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/main/hq/teams/{team_id}/customers/{customer_id}/report/brief'
    pass


@_dataclass(frozen=True, slots=True)
class _URLTarget14:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/main/hq/teams/{team_id}/customers/{customer_id}/report/detailed'
    pass


@_dataclass(frozen=True, slots=True)
class _URLTarget15:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/main/regional'

    @property
    def offices(self) -> _URLUnboundTarget16:
        return _URLUnboundTarget16(
            self._base_path,
            self._local_path + '/offices',
            None,
        )


@_dataclass(frozen=True, slots=True)
class _URLTarget16:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/main/regional/offices'

    @property
    def by_office_id(self) -> _URLUnboundTarget17:
        return _URLUnboundTarget17(
            self._base_path,
            self._local_path,
            None,
        )


@_dataclass(frozen=True, slots=True)
class _URLTarget17:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/main/regional/offices/{office_id}'

    def __call__(self, office_id: str) -> _URLNode17:
        encoded = _quote_segment("parameter 'office_id'", office_id)
        return _URLNode17(
            self._base_path,
            self._local_path + "/" + encoded,
            self._owner_key,
        )

    @property
    def teams(self) -> _URLUnboundTarget18:
        return _URLUnboundTarget18(
            self._base_path,
            self._local_path + '/teams',
            None,
        )


@_dataclass(frozen=True, slots=True)
class _URLTarget18:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/main/regional/offices/{office_id}/teams'

    @property
    def by_team_id(self) -> _URLUnboundTarget19:
        return _URLUnboundTarget19(
            self._base_path,
            self._local_path,
            None,
        )


@_dataclass(frozen=True, slots=True)
class _URLTarget19:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/main/regional/offices/{office_id}/teams/{team_id}'

    def __call__(self, team_id: str) -> _URLNode19:
        encoded = _quote_segment("parameter 'team_id'", team_id)
        return _URLNode19(
            self._base_path,
            self._local_path + "/" + encoded,
            self._owner_key,
        )

    @property
    def analytics(self) -> _URLUnboundTarget20:
        return _URLUnboundTarget20(
            self._base_path,
            self._local_path + '/analytics',
            'app/routes/main/regional/offices/by_office_id/teams/by_team_id/analytics/route.py',
        )

    @property
    def customers(self) -> _URLUnboundTarget24:
        return _URLUnboundTarget24(
            self._base_path,
            self._local_path + '/customers',
            None,
        )


@_dataclass(frozen=True, slots=True)
class _URLTarget20:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/main/regional/offices/{office_id}/teams/{team_id}/analytics'

    @property
    def customers(self) -> _URLUnboundTarget21:
        return _URLUnboundTarget21(
            self._base_path,
            self._local_path + '/customers',
            None,
        )


@_dataclass(frozen=True, slots=True)
class _URLTarget21:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/main/regional/offices/{office_id}/teams/{team_id}/analytics/customers'

    @property
    def by_customer_id(self) -> _URLUnboundTarget22:
        return _URLUnboundTarget22(
            self._base_path,
            self._local_path,
            None,
        )


@_dataclass(frozen=True, slots=True)
class _URLTarget22:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/main/regional/offices/{office_id}/teams/{team_id}/analytics/customers/{customer_id}'

    def __call__(self, customer_id: str) -> _URLNode22:
        encoded = _quote_segment("parameter 'customer_id'", customer_id)
        return _URLNode22(
            self._base_path,
            self._local_path + "/" + encoded,
            self._owner_key,
        )

    @property
    def report(self) -> _URLUnboundTarget23:
        return _URLUnboundTarget23(
            self._base_path,
            self._local_path + '/report',
            None,
        )


@_dataclass(frozen=True, slots=True)
class _URLTarget23:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/main/regional/offices/{office_id}/teams/{team_id}/analytics/customers/{customer_id}/report'

    @property
    def trail_keys(self) -> _TrailKeys23:
        return _TrailKeys23()
    pass


@_dataclass(frozen=True, slots=True)
class _URLTarget24:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/main/regional/offices/{office_id}/teams/{team_id}/customers'

    @property
    def by_customer_id(self) -> _URLUnboundTarget25:
        return _URLUnboundTarget25(
            self._base_path,
            self._local_path,
            None,
        )


@_dataclass(frozen=True, slots=True)
class _URLTarget25:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/main/regional/offices/{office_id}/teams/{team_id}/customers/{customer_id}'

    def __call__(self, customer_id: str) -> _URLNode25:
        encoded = _quote_segment("parameter 'customer_id'", customer_id)
        return _URLNode25(
            self._base_path,
            self._local_path + "/" + encoded,
            self._owner_key,
        )

    @property
    def report(self) -> _URLUnboundTarget26:
        return _URLUnboundTarget26(
            self._base_path,
            self._local_path + '/report',
            'app/routes/main/regional/offices/by_office_id/teams/by_team_id/customers/by_customer_id/report/route.py',
        )


@_dataclass(frozen=True, slots=True)
class _URLTarget26:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/main/regional/offices/{office_id}/teams/{team_id}/customers/{customer_id}/report'

    @property
    def brief(self) -> _URLUnboundTarget27:
        return _URLUnboundTarget27(
            self._base_path,
            self._local_path + '/brief',
            None,
        )

    @property
    def detailed(self) -> _URLUnboundTarget28:
        return _URLUnboundTarget28(
            self._base_path,
            self._local_path + '/detailed',
            None,
        )


@_dataclass(frozen=True, slots=True)
class _URLTarget27:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/main/regional/offices/{office_id}/teams/{team_id}/customers/{customer_id}/report/brief'
    pass


@_dataclass(frozen=True, slots=True)
class _URLTarget28:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/main/regional/offices/{office_id}/teams/{team_id}/customers/{customer_id}/report/detailed'
    pass


@_dataclass(frozen=True, slots=True)
class _URLTarget29:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/main/reports'

    @property
    def by_customer_id(self) -> _URLUnboundTarget30:
        return _URLUnboundTarget30(
            self._base_path,
            self._local_path,
            None,
        )


@_dataclass(frozen=True, slots=True)
class _URLTarget30:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/main/reports/{customer_id}'

    def __call__(self, customer_id: str) -> _URLNode30:
        encoded = _quote_segment("parameter 'customer_id'", customer_id)
        return _URLNode30(
            self._base_path,
            self._local_path + "/" + encoded,
            self._owner_key,
        )

    @property
    def trail_keys(self) -> _TrailKeys30:
        return _TrailKeys30()


@_dataclass(frozen=True, slots=True)
class _URLUnboundTarget0:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/'

    @property
    def about(self) -> _URLUnboundTarget1:
        return _URLUnboundTarget1(
            self._base_path,
            self._local_path + '/about',
            None,
        )

    @property
    def main(self) -> _URLUnboundTarget2:
        return _URLUnboundTarget2(
            self._base_path,
            self._local_path + '/main',
            None,
        )


@_dataclass(frozen=True, slots=True)
class _URLUnboundTarget1:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/about'


@_dataclass(frozen=True, slots=True)
class _URLUnboundTarget2:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/main'

    @property
    def hq(self) -> _URLUnboundTarget3:
        return _URLUnboundTarget3(
            self._base_path,
            self._local_path + '/hq',
            None,
        )

    @property
    def regional(self) -> _URLUnboundTarget15:
        return _URLUnboundTarget15(
            self._base_path,
            self._local_path + '/regional',
            None,
        )

    @property
    def reports(self) -> _URLUnboundTarget29:
        return _URLUnboundTarget29(
            self._base_path,
            self._local_path + '/reports',
            None,
        )


@_dataclass(frozen=True, slots=True)
class _URLUnboundTarget3:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/main/hq'

    @property
    def teams(self) -> _URLUnboundTarget4:
        return _URLUnboundTarget4(
            self._base_path,
            self._local_path + '/teams',
            None,
        )


@_dataclass(frozen=True, slots=True)
class _URLUnboundTarget4:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/main/hq/teams'

    @property
    def by_team_id(self) -> _URLUnboundTarget5:
        return _URLUnboundTarget5(
            self._base_path,
            self._local_path,
            None,
        )


@_dataclass(frozen=True, slots=True)
class _URLUnboundTarget5:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/main/hq/teams/{team_id}'

    @property
    def analytics(self) -> _URLUnboundTarget6:
        return _URLUnboundTarget6(
            self._base_path,
            self._local_path + '/analytics',
            'app/routes/main/hq/teams/by_team_id/analytics/route.py',
        )

    @property
    def customers(self) -> _URLUnboundTarget10:
        return _URLUnboundTarget10(
            self._base_path,
            self._local_path + '/customers',
            None,
        )


@_dataclass(frozen=True, slots=True)
class _URLUnboundTarget6:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/main/hq/teams/{team_id}/analytics'

    @property
    def customers(self) -> _URLUnboundTarget7:
        return _URLUnboundTarget7(
            self._base_path,
            self._local_path + '/customers',
            None,
        )


@_dataclass(frozen=True, slots=True)
class _URLUnboundTarget7:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/main/hq/teams/{team_id}/analytics/customers'

    @property
    def by_customer_id(self) -> _URLUnboundTarget8:
        return _URLUnboundTarget8(
            self._base_path,
            self._local_path,
            None,
        )


@_dataclass(frozen=True, slots=True)
class _URLUnboundTarget8:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/main/hq/teams/{team_id}/analytics/customers/{customer_id}'

    @property
    def report(self) -> _URLUnboundTarget9:
        return _URLUnboundTarget9(
            self._base_path,
            self._local_path + '/report',
            None,
        )


@_dataclass(frozen=True, slots=True)
class _URLUnboundTarget9:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/main/hq/teams/{team_id}/analytics/customers/{customer_id}/report'

    @property
    def trail_keys(self) -> _TrailKeys9:
        return _TrailKeys9()


@_dataclass(frozen=True, slots=True)
class _URLUnboundTarget10:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/main/hq/teams/{team_id}/customers'

    @property
    def by_customer_id(self) -> _URLUnboundTarget11:
        return _URLUnboundTarget11(
            self._base_path,
            self._local_path,
            None,
        )


@_dataclass(frozen=True, slots=True)
class _URLUnboundTarget11:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/main/hq/teams/{team_id}/customers/{customer_id}'

    @property
    def report(self) -> _URLUnboundTarget12:
        return _URLUnboundTarget12(
            self._base_path,
            self._local_path + '/report',
            'app/routes/main/hq/teams/by_team_id/customers/by_customer_id/report/route.py',
        )


@_dataclass(frozen=True, slots=True)
class _URLUnboundTarget12:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/main/hq/teams/{team_id}/customers/{customer_id}/report'

    @property
    def brief(self) -> _URLUnboundTarget13:
        return _URLUnboundTarget13(
            self._base_path,
            self._local_path + '/brief',
            None,
        )

    @property
    def detailed(self) -> _URLUnboundTarget14:
        return _URLUnboundTarget14(
            self._base_path,
            self._local_path + '/detailed',
            None,
        )


@_dataclass(frozen=True, slots=True)
class _URLUnboundTarget13:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/main/hq/teams/{team_id}/customers/{customer_id}/report/brief'


@_dataclass(frozen=True, slots=True)
class _URLUnboundTarget14:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/main/hq/teams/{team_id}/customers/{customer_id}/report/detailed'


@_dataclass(frozen=True, slots=True)
class _URLUnboundTarget15:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/main/regional'

    @property
    def offices(self) -> _URLUnboundTarget16:
        return _URLUnboundTarget16(
            self._base_path,
            self._local_path + '/offices',
            None,
        )


@_dataclass(frozen=True, slots=True)
class _URLUnboundTarget16:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/main/regional/offices'

    @property
    def by_office_id(self) -> _URLUnboundTarget17:
        return _URLUnboundTarget17(
            self._base_path,
            self._local_path,
            None,
        )


@_dataclass(frozen=True, slots=True)
class _URLUnboundTarget17:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/main/regional/offices/{office_id}'

    @property
    def teams(self) -> _URLUnboundTarget18:
        return _URLUnboundTarget18(
            self._base_path,
            self._local_path + '/teams',
            None,
        )


@_dataclass(frozen=True, slots=True)
class _URLUnboundTarget18:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/main/regional/offices/{office_id}/teams'

    @property
    def by_team_id(self) -> _URLUnboundTarget19:
        return _URLUnboundTarget19(
            self._base_path,
            self._local_path,
            None,
        )


@_dataclass(frozen=True, slots=True)
class _URLUnboundTarget19:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/main/regional/offices/{office_id}/teams/{team_id}'

    @property
    def analytics(self) -> _URLUnboundTarget20:
        return _URLUnboundTarget20(
            self._base_path,
            self._local_path + '/analytics',
            'app/routes/main/regional/offices/by_office_id/teams/by_team_id/analytics/route.py',
        )

    @property
    def customers(self) -> _URLUnboundTarget24:
        return _URLUnboundTarget24(
            self._base_path,
            self._local_path + '/customers',
            None,
        )


@_dataclass(frozen=True, slots=True)
class _URLUnboundTarget20:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/main/regional/offices/{office_id}/teams/{team_id}/analytics'

    @property
    def customers(self) -> _URLUnboundTarget21:
        return _URLUnboundTarget21(
            self._base_path,
            self._local_path + '/customers',
            None,
        )


@_dataclass(frozen=True, slots=True)
class _URLUnboundTarget21:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/main/regional/offices/{office_id}/teams/{team_id}/analytics/customers'

    @property
    def by_customer_id(self) -> _URLUnboundTarget22:
        return _URLUnboundTarget22(
            self._base_path,
            self._local_path,
            None,
        )


@_dataclass(frozen=True, slots=True)
class _URLUnboundTarget22:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/main/regional/offices/{office_id}/teams/{team_id}/analytics/customers/{customer_id}'

    @property
    def report(self) -> _URLUnboundTarget23:
        return _URLUnboundTarget23(
            self._base_path,
            self._local_path + '/report',
            None,
        )


@_dataclass(frozen=True, slots=True)
class _URLUnboundTarget23:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/main/regional/offices/{office_id}/teams/{team_id}/analytics/customers/{customer_id}/report'

    @property
    def trail_keys(self) -> _TrailKeys23:
        return _TrailKeys23()


@_dataclass(frozen=True, slots=True)
class _URLUnboundTarget24:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/main/regional/offices/{office_id}/teams/{team_id}/customers'

    @property
    def by_customer_id(self) -> _URLUnboundTarget25:
        return _URLUnboundTarget25(
            self._base_path,
            self._local_path,
            None,
        )


@_dataclass(frozen=True, slots=True)
class _URLUnboundTarget25:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/main/regional/offices/{office_id}/teams/{team_id}/customers/{customer_id}'

    @property
    def report(self) -> _URLUnboundTarget26:
        return _URLUnboundTarget26(
            self._base_path,
            self._local_path + '/report',
            'app/routes/main/regional/offices/by_office_id/teams/by_team_id/customers/by_customer_id/report/route.py',
        )


@_dataclass(frozen=True, slots=True)
class _URLUnboundTarget26:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/main/regional/offices/{office_id}/teams/{team_id}/customers/{customer_id}/report'

    @property
    def brief(self) -> _URLUnboundTarget27:
        return _URLUnboundTarget27(
            self._base_path,
            self._local_path + '/brief',
            None,
        )

    @property
    def detailed(self) -> _URLUnboundTarget28:
        return _URLUnboundTarget28(
            self._base_path,
            self._local_path + '/detailed',
            None,
        )


@_dataclass(frozen=True, slots=True)
class _URLUnboundTarget27:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/main/regional/offices/{office_id}/teams/{team_id}/customers/{customer_id}/report/brief'


@_dataclass(frozen=True, slots=True)
class _URLUnboundTarget28:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/main/regional/offices/{office_id}/teams/{team_id}/customers/{customer_id}/report/detailed'


@_dataclass(frozen=True, slots=True)
class _URLUnboundTarget29:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/main/reports'

    @property
    def by_customer_id(self) -> _URLUnboundTarget30:
        return _URLUnboundTarget30(
            self._base_path,
            self._local_path,
            None,
        )


@_dataclass(frozen=True, slots=True)
class _URLUnboundTarget30:
    _base_path: str
    _local_path: str
    _owner_key: str | None

    @property
    def route_pattern(self) -> str:
        return '/main/reports/{customer_id}'

    @property
    def trail_keys(self) -> _TrailKeys30:
        return _TrailKeys30()


@_dataclass(frozen=True, slots=True)
class _Destination0:
    href: str

    def navigation_href(self, navigation: _Navigation) -> str:
        return _navigation_href(navigation, self.href)


@_dataclass(frozen=True, slots=True)
class _Destination1:
    href: str

    def navigation_href(self, navigation: _Navigation) -> str:
        return _navigation_href(navigation, self.href)


@_dataclass(frozen=True, slots=True)
class _Destination2:
    href: str

    def navigation_href(self, navigation: _Navigation) -> str:
        return _navigation_href(navigation, self.href)


@_dataclass(frozen=True, slots=True)
class _Destination3:
    href: str

    def navigation_href(self, navigation: _Navigation) -> str:
        return _navigation_href(navigation, self.href)


@_dataclass(frozen=True, slots=True)
class _Destinations6:
    _base_path: str

    def customer_report(self, team_id: str, customer_id: str) -> _Destination0:
        return _Destination0(
            _add_trail_key(self._base_path + "/main" + "/hq" + "/teams" + "/" + _quote_segment("parameter team_id", team_id) + "/analytics" + "/customers" + "/" + _quote_segment("parameter customer_id", customer_id) + "/report", 'hq-analytics'),
        )


@_dataclass(frozen=True, slots=True)
class _Destinations11:
    _base_path: str

    def shared_report(self, customer_id: str) -> _Destination1:
        return _Destination1(
            _add_trail_key(self._base_path + "/main" + "/reports" + "/" + _quote_segment("parameter customer_id", customer_id), 'hq-customer'),
        )


@_dataclass(frozen=True, slots=True)
class _Destinations20:
    _base_path: str

    def customer_report(self, office_id: str, team_id: str, customer_id: str) -> _Destination2:
        return _Destination2(
            _add_trail_key(self._base_path + "/main" + "/regional" + "/offices" + "/" + _quote_segment("parameter office_id", office_id) + "/teams" + "/" + _quote_segment("parameter team_id", team_id) + "/analytics" + "/customers" + "/" + _quote_segment("parameter customer_id", customer_id) + "/report", 'regional-analytics'),
        )


@_dataclass(frozen=True, slots=True)
class _Destinations25:
    _base_path: str

    def shared_report(self, customer_id: str) -> _Destination3:
        return _Destination3(
            _add_trail_key(self._base_path + "/main" + "/reports" + "/" + _quote_segment("parameter customer_id", customer_id), 'regional-customer'),
        )


@_dataclass(frozen=True, slots=True)
class _TrailKeys9:

    hq_analytics: str = 'hq-analytics'


@_dataclass(frozen=True, slots=True)
class _TrailKeys23:

    regional_analytics: str = 'regional-analytics'


@_dataclass(frozen=True, slots=True)
class _TrailKeys30:

    hq_customer: str = 'hq-customer'

    regional_customer: str = 'regional-customer'


urls: _URLNode0 = _URLNode0("", "", None)


@_dataclass(frozen=True, slots=True)
class _MountBound0Node0:
    _base_path: str
    _local_path: str

    @property
    def path(self) -> str:
        return self._base_path + (self._local_path or '/')

    @property
    def customers(self) -> _MountBound0Node1:
        return _MountBound0Node1(
            self._base_path,
            self._local_path + '/customers',
        )


@_dataclass(frozen=True, slots=True)
class _MountBound0Node1:
    _base_path: str
    _local_path: str

    def by_customer_id(self, customer_id: str) -> _MountBound0Node2:
        encoded = _quote_segment("parameter 'customer_id'", customer_id)
        return _MountBound0Node2(
            self._base_path,
            self._local_path + "/" + encoded,
        )


@_dataclass(frozen=True, slots=True)
class _MountBound0Node2:
    _base_path: str
    _local_path: str

    @property
    def report(self) -> _MountBound0Node3:
        return _MountBound0Node3(
            self._base_path,
            self._local_path + '/report',
        )


@_dataclass(frozen=True, slots=True)
class _MountBound0Node3:
    _base_path: str
    _local_path: str

    @property
    def path(self) -> str:
        return self._base_path + (self._local_path or '/')


@_dataclass(frozen=True, slots=True)
class _MountBound1Node0:
    _base_path: str
    _local_path: str

    @property
    def path(self) -> str:
        return self._base_path + (self._local_path or '/')

    @property
    def customers(self) -> _MountBound1Node1:
        return _MountBound1Node1(
            self._base_path,
            self._local_path + '/customers',
        )


@_dataclass(frozen=True, slots=True)
class _MountBound1Node1:
    _base_path: str
    _local_path: str

    def by_customer_id(self, customer_id: str) -> _MountBound1Node2:
        encoded = _quote_segment("parameter 'customer_id'", customer_id)
        return _MountBound1Node2(
            self._base_path,
            self._local_path + "/" + encoded,
        )


@_dataclass(frozen=True, slots=True)
class _MountBound1Node2:
    _base_path: str
    _local_path: str

    @property
    def report(self) -> _MountBound1Node3:
        return _MountBound1Node3(
            self._base_path,
            self._local_path + '/report',
        )


@_dataclass(frozen=True, slots=True)
class _MountBound1Node3:
    _base_path: str
    _local_path: str

    @property
    def path(self) -> str:
        return self._base_path + (self._local_path or '/')


@_dataclass(frozen=True, slots=True)
class _MountBound2Node0:
    _base_path: str
    _local_path: str

    @property
    def path(self) -> str:
        return self._base_path + (self._local_path or '/')

    @property
    def brief(self) -> _MountBound2Node1:
        return _MountBound2Node1(
            self._base_path,
            self._local_path + '/brief',
        )

    @property
    def detailed(self) -> _MountBound2Node2:
        return _MountBound2Node2(
            self._base_path,
            self._local_path + '/detailed',
        )


@_dataclass(frozen=True, slots=True)
class _MountBound2Node1:
    _base_path: str
    _local_path: str

    @property
    def path(self) -> str:
        return self._base_path + (self._local_path or '/')


@_dataclass(frozen=True, slots=True)
class _MountBound2Node2:
    _base_path: str
    _local_path: str

    @property
    def path(self) -> str:
        return self._base_path + (self._local_path or '/')


@_dataclass(frozen=True, slots=True)
class _MountBound3Node0:
    _base_path: str
    _local_path: str

    @property
    def path(self) -> str:
        return self._base_path + (self._local_path or '/')

    @property
    def brief(self) -> _MountBound3Node1:
        return _MountBound3Node1(
            self._base_path,
            self._local_path + '/brief',
        )

    @property
    def detailed(self) -> _MountBound3Node2:
        return _MountBound3Node2(
            self._base_path,
            self._local_path + '/detailed',
        )


@_dataclass(frozen=True, slots=True)
class _MountBound3Node1:
    _base_path: str
    _local_path: str

    @property
    def path(self) -> str:
        return self._base_path + (self._local_path or '/')


@_dataclass(frozen=True, slots=True)
class _MountBound3Node2:
    _base_path: str
    _local_path: str

    @property
    def path(self) -> str:
        return self._base_path + (self._local_path or '/')


@_dataclass(frozen=True, slots=True)
class _MountCatalogRoot_0:

    @_overload
    def bind(self, owner: _URLNode6) -> _MountBound0Node0:
        ...

    @_overload
    def bind(self, owner: _URLNode20) -> _MountBound1Node0:
        ...

    def bind(self, owner: object) -> object:
        owner_key = getattr(owner, '_owner_key', None)
        if owner_key == 'app/routes/main/hq/teams/by_team_id/analytics/route.py':
            base_path = getattr(owner, '_base_path', None)
            local_path = getattr(owner, '_local_path', None)
            if not isinstance(base_path, str) or not isinstance(
                local_path, str
            ):
                raise ValueError(
                    'owner is not a generated live URL node for mount analytics'
                )
            return _MountBound0Node0(base_path, local_path)
        if owner_key == 'app/routes/main/regional/offices/by_office_id/teams/by_team_id/analytics/route.py':
            base_path = getattr(owner, '_base_path', None)
            local_path = getattr(owner, '_local_path', None)
            if not isinstance(base_path, str) or not isinstance(
                local_path, str
            ):
                raise ValueError(
                    'owner is not a generated live URL node for mount analytics'
                )
            return _MountBound1Node0(base_path, local_path)
        raise ValueError(
            'owner is not a live owner of mount analytics'
        )


@_dataclass(frozen=True, slots=True)
class _MountCatalogRoot_1:

    @_overload
    def bind(self, owner: _URLNode12) -> _MountBound2Node0:
        ...

    @_overload
    def bind(self, owner: _URLNode26) -> _MountBound3Node0:
        ...

    def bind(self, owner: object) -> object:
        owner_key = getattr(owner, '_owner_key', None)
        if owner_key == 'app/routes/main/hq/teams/by_team_id/customers/by_customer_id/report/route.py':
            base_path = getattr(owner, '_base_path', None)
            local_path = getattr(owner, '_local_path', None)
            if not isinstance(base_path, str) or not isinstance(
                local_path, str
            ):
                raise ValueError(
                    'owner is not a generated live URL node for mount customer_report'
                )
            return _MountBound2Node0(base_path, local_path)
        if owner_key == 'app/routes/main/regional/offices/by_office_id/teams/by_team_id/customers/by_customer_id/report/route.py':
            base_path = getattr(owner, '_base_path', None)
            local_path = getattr(owner, '_local_path', None)
            if not isinstance(base_path, str) or not isinstance(
                local_path, str
            ):
                raise ValueError(
                    'owner is not a generated live URL node for mount customer_report'
                )
            return _MountBound3Node0(base_path, local_path)
        raise ValueError(
            'owner is not a live owner of mount customer_report'
        )


@_dataclass(frozen=True, slots=True)
class _MountCatalogRoot:

    @property
    def analytics(self) -> _MountCatalogRoot_0:
        return _MountCatalogRoot_0()

    @property
    def customer_report(self) -> _MountCatalogRoot_1:
        return _MountCatalogRoot_1()


mount_urls: _MountCatalogRoot = _MountCatalogRoot()
