# Code generated by pyganini; DO NOT EDIT.
"""Generated Pyganini ASGI routing surface."""

from jinja2 import Environment as _Environment
from starlette.routing import Router as _Router

from pyganini import RouteErrorHandler as _RouteErrorHandler
from pyganini import TemplateInspectionMode as _TemplateInspectionMode
from pyganini._dispatch import build_endpoint as _build_endpoint
from pyganini._dispatch import load_route as _load_route
from pyganini._dispatch import PathPriorityRoute as _Route
from pyganini._dispatch import RouteErrorRouter as _ErrorRouter
from pyganini._dispatch import prepare_environment as _prepare_environment
from pyganini._dispatch import prepare_route_error_handler as _prepare_route_error_handler
from pyganini._dispatch import prepare_template_inspection as _prepare_template_inspection
from pyganini._dispatch import select_handler as _select_handler

_template_names = ('routes/about/page.jinja', 'routes/layout.jinja', 'routes/page.jinja')

_route_0 = _load_route(
    module='app.routes.about.route',
    source_path='app/routes/about/route.py',
    expected=(
        ('page', 'GET', '/', '/about', ('GET', 'HEAD'), 'app.routes.about.handlers', 'page', 'page', 'app/routes/about/route.py', 7, 20, 'page.jinja', 'app/routes/about/route.py', None, None, None, None),
    ),
    expected_creator=None,
    expected_template_root=None,
)

_route_1 = _load_route(
    module='app.routes.route',
    source_path='app/routes/route.py',
    expected=(
        ('page', 'GET', '/', '/', ('GET', 'HEAD'), 'app.routes.handlers', 'page', 'page', 'app/routes/route.py', 9, 10, 'page.jinja', 'app/routes/route.py', None, None, None, None),
        ('action', 'POST', '/save', '/save', ('POST',), 'app.routes.handlers', 'save', 'save', 'app/routes/route.py', 12, 9, None, 'app/routes/route.py', None, None, ('body', (4096,)), ('app/routes/route.py', 16, 26)),
    ),
    expected_creator=None,
    expected_template_root=None,
)

_handler_0 = _select_handler(
    _route_1,
    kind='page',
    method='GET',
    local_path='/',
)

_handler_1 = _select_handler(
    _route_1,
    kind='action',
    method='POST',
    local_path='/save',
)

_handler_2 = _select_handler(
    _route_0,
    kind='page',
    method='GET',
    local_path='/',
)

def create_router(
    *,
    environment: _Environment | None = None,
    error_handler: _RouteErrorHandler | None = None,
    template_inspection: _TemplateInspectionMode = _TemplateInspectionMode.OFF,
) -> _Router:
    selected_template_inspection = _prepare_template_inspection(
        template_inspection,
        source_path='app/_pyganini/asgi.py',
    )
    selected_environment = _prepare_environment(
        environment,
        template_names=_template_names,
        source_path='app/_pyganini/asgi.py',
    )
    selected_error_handler = _prepare_route_error_handler(
        error_handler,
        template_inspection=selected_template_inspection,
        source_path='app/_pyganini/asgi.py',
    )
    endpoint_0 = _build_endpoint(
        handlers={
            'GET': _handler_0,
        },
        evidence={
            'GET': ('page', '/', ('GET', 'HEAD'), 'app/routes/route.py', 1, 1, 'app.routes.handlers', 'page', 'page', 'app/routes/route.py', None, None, 1, 1, '/'),
        },
        embedded_expectations={
            'GET': (),
        },
        rendering={
            'GET': (('routes/page.jinja', 'app/routes/page.jinja', 1, 1, None, ('app/routes/route.py', 10, 14)), (('app/routes/layout.py', 1, 1, '/', ('routes/layout.jinja', 'app/routes/layout.jinja', 1, 1, None, None)),), ('page', 'page', '/', 'routes/page.jinja', 'app/routes/page.jinja:1:1', 'app/routes/route.py:10:14', 'app/routes/route.py:1:1', 'app.routes.handlers:page', 'none'), (('layout', 'page', '/', 'routes/layout.jinja', 'app/routes/layout.jinja:1:1', 'none', 'app/routes/layout.py:1:1', 'none', 'none'),), ()),
        },
        parameters=(),
        environment=selected_environment,
        template_inspection=selected_template_inspection,
    )
    endpoint_1 = _build_endpoint(
        handlers={
            'POST': _handler_1,
        },
        request_data={
            'POST': ('body', (4096,)),
        },
        evidence={
            'POST': ('action', '/save', ('POST',), 'app/routes/route.py', 1, 1, 'app.routes.handlers', 'save', 'save', 'app/routes/route.py', None, None, 1, 1, '/'),
        },
        embedded_expectations={
            'POST': (),
        },
        rendering={
            'POST': (None, (('app/routes/layout.py', 1, 1, '/', ('routes/layout.jinja', 'app/routes/layout.jinja', 1, 1, None, None)),), None, (('layout', 'action-page', '/', 'routes/layout.jinja', 'app/routes/layout.jinja:1:1', 'none', 'app/routes/layout.py:1:1', 'none', 'none'),), ()),
        },
        parameters=(),
        environment=selected_environment,
        template_inspection=selected_template_inspection,
    )
    endpoint_2 = _build_endpoint(
        handlers={
            'GET': _handler_2,
        },
        evidence={
            'GET': ('page', '/about', ('GET', 'HEAD'), 'app/routes/about/route.py', 1, 1, 'app.routes.about.handlers', 'page', 'page', 'app/routes/about/route.py', None, None, 1, 1, '/about'),
        },
        embedded_expectations={
            'GET': (),
        },
        rendering={
            'GET': (('routes/about/page.jinja', 'app/routes/about/page.jinja', 1, 1, None, ('app/routes/about/route.py', 7, 35)), (('app/routes/layout.py', 1, 1, '/', ('routes/layout.jinja', 'app/routes/layout.jinja', 1, 1, None, None)),), ('page', 'page', '/about', 'routes/about/page.jinja', 'app/routes/about/page.jinja:1:1', 'app/routes/about/route.py:7:35', 'app/routes/about/route.py:1:1', 'app.routes.about.handlers:page', 'none'), (('layout', 'page', '/', 'routes/layout.jinja', 'app/routes/layout.jinja:1:1', 'none', 'app/routes/layout.py:1:1', 'none', 'none'),), ()),
        },
        parameters=(),
        environment=selected_environment,
        template_inspection=selected_template_inspection,
    )
    _generated_routes: list[_Route] = [
            _Route(
                '/',
                endpoint_0,
                methods=['GET', 'HEAD'],
                error_handler=selected_error_handler,
                error_evidence={'GET': ('page', '/', ('GET', 'HEAD'), 'app/routes/route.py', 1, 1, 'app.routes.handlers', 'page', 'page', 'app/routes/route.py', None, None, 1, 1, '/')},
                error_templates=(None, None),
            ),
            _Route(
                '/save',
                endpoint_1,
                methods=['POST'],
                error_handler=selected_error_handler,
                error_evidence={'POST': ('action', '/save', ('POST',), 'app/routes/route.py', 1, 1, 'app.routes.handlers', 'save', 'save', 'app/routes/route.py', None, None, 1, 1, '/')},
                error_templates=(None, None),
            ),
            _Route(
                '/about',
                endpoint_2,
                methods=['GET', 'HEAD'],
                error_handler=selected_error_handler,
                error_evidence={'GET': ('page', '/about', ('GET', 'HEAD'), 'app/routes/about/route.py', 1, 1, 'app.routes.about.handlers', 'page', 'page', 'app/routes/about/route.py', None, None, 1, 1, '/about')},
                error_templates=(None, None),
            ),
    ]
    if selected_error_handler is None:
        return _Router(
            routes=_generated_routes,
            redirect_slashes=False,
        )
    return _ErrorRouter(
        routes=_generated_routes,
        redirect_slashes=False,
        error_handler=selected_error_handler,
    )


router: _Router = create_router()
