"""Public declarations for Pyganini route source."""

from pyganini import browser, csrf, hx, sse
from pyganini._declarations import (
    ActionDef,
    FragmentRouteDef,
    KitActionDef,
    KitFragmentRouteDef,
    KitRouteDef,
    KitRouteMount,
    MountRoute,
    RouteDef,
    RouteMeta,
    action,
    fragment_route,
    kit_action,
    kit_fragment_route,
    mount_route,
    route,
    route_kit,
    route_mount,
)
from pyganini._dispatch import RouteErrorHandler
from pyganini._navigation import (
    Destination,
    Navigation,
    NavigationBack,
    NavigationCurrent,
    NavTrail,
    NavTrailStep,
    RequestNav,
    RouteNav,
    RouteTarget,
    current_nav_step,
    nav,
    nav_step,
    to,
)
from pyganini._render import (
    FragmentResponse,
    FragmentRouteResponse,
    Page,
    PageMetadata,
    PageRouteResponse,
    RouteResponse,
    TemplateInspectionMode,
    create_environment,
)

__all__ = [
    "ActionDef",
    "Destination",
    "FragmentResponse",
    "FragmentRouteDef",
    "FragmentRouteResponse",
    "KitActionDef",
    "KitFragmentRouteDef",
    "KitRouteDef",
    "KitRouteMount",
    "MountRoute",
    "NavTrail",
    "NavTrailStep",
    "Navigation",
    "NavigationBack",
    "NavigationCurrent",
    "Page",
    "PageMetadata",
    "PageRouteResponse",
    "RequestNav",
    "RouteDef",
    "RouteErrorHandler",
    "RouteMeta",
    "RouteNav",
    "RouteResponse",
    "RouteTarget",
    "TemplateInspectionMode",
    "action",
    "browser",
    "create_environment",
    "csrf",
    "current_nav_step",
    "fragment_route",
    "hx",
    "kit_action",
    "kit_fragment_route",
    "mount_route",
    "nav",
    "nav_step",
    "route",
    "route_kit",
    "route_mount",
    "sse",
    "to",
]
