"""Project final browser-ready assets into deterministic managed output."""

from __future__ import annotations

import hashlib
import json
import os
import re
import stat
from collections.abc import Sequence
from contextlib import suppress
from dataclasses import dataclass
from pathlib import Path, PurePosixPath, PureWindowsPath
from typing import Any, Literal, cast

from pyganini._filesystem import (
    AnchoredFilesystem,
    EntryKind,
    FilesystemEntry,
    FilesystemOperationError,
    StagedFile,
    open_anchored_filesystem,
)
from pyganini._paths import ProjectPaths
from pyganini._url_binding import quote_segment

_ASSETS = PurePosixPath("assets")
_BUILD = _ASSETS / "build"
_DIST = _ASSETS / "dist"
_STATE_DIRECTORY = _ASSETS / ".pyganini"
_STATE = _STATE_DIRECTORY / "assets.json"
_GENERATED = _ASSETS / "pyganini_assets_gen.py"
_INIT = PurePosixPath("__init__.py")
_BUILD_REL = PurePosixPath("build")
_DIST_REL = PurePosixPath("dist")
_STATE_DIRECTORY_REL = PurePosixPath(".pyganini")
_STATE_REL = _STATE_DIRECTORY_REL / "assets.json"
_GENERATED_REL = PurePosixPath("pyganini_assets_gen.py")
_STATE_SCHEMA = "pyganini.assets-state.v1"
_LIST_SCHEMA = "pyganini.assets.v1"
_GENERATED_COMMENT = "# Code generated by pyganini; DO NOT EDIT.\n"
_WINDOWS_RESERVED = {
    "aux",
    "clock$",
    "con",
    "nul",
    "prn",
    *(f"com{number}" for number in range(1, 10)),
    *(f"lpt{number}" for number in range(1, 10)),
}
_HASH = re.compile(r"^[0-9a-f]{8}$")

Operation = Literal["dist", "check", "list", "clean"]


class AssetError(RuntimeError):
    """A localized asset validation, comparison, or write failure."""

    def __init__(
        self,
        code: str,
        phase: str,
        path: str,
        message: str,
        *,
        details: Sequence[str] = (),
    ) -> None:
        super().__init__(message)
        self.code = code
        self.phase = phase
        self.path = path
        self.message = message
        self.details = tuple(details)


@dataclass(frozen=True, slots=True)
class AssetDifference:
    """One reachable managed-asset state difference."""

    code: str
    phase: str
    path: PurePosixPath
    message: str


@dataclass(frozen=True, slots=True)
class AssetResult:
    """Counts and paths completed by a managed asset write."""

    written: tuple[PurePosixPath, ...]
    unchanged: tuple[PurePosixPath, ...]
    removed: tuple[PurePosixPath, ...]


@dataclass(frozen=True, slots=True)
class _AssetPaths:
    root: Path
    assets: Path
    build: Path
    dist: Path
    state_directory: Path
    state: Path
    generated: Path


@dataclass(frozen=True, slots=True)
class _ProjectedAsset:
    logical: str
    source: Path
    dist: PurePosixPath
    url: str
    hash: str
    size: int
    content: bytes


@dataclass(frozen=True, slots=True)
class _StateRow:
    logical: str
    dist: PurePosixPath
    hash: str


@dataclass(slots=True)
class _AssetLease:
    filesystem: AnchoredFilesystem | None
    build_filesystem: AnchoredFilesystem | None

    def require(self) -> AnchoredFilesystem:
        if self.filesystem is None:
            raise AssetError(
                "PYGANINI022",
                "asset-write",
                _display(_ASSETS),
                "prepared asset operation is already closed",
            )
        return self.filesystem

    def close(self) -> None:
        failure: OSError | None = None
        build_filesystem = self.build_filesystem
        if build_filesystem is not None:
            self.build_filesystem = None
            try:
                build_filesystem.close()
            except OSError as error:
                failure = error
        filesystem = self.filesystem
        if filesystem is not None:
            self.filesystem = None
            try:
                filesystem.close()
            except OSError as error:
                if failure is None:
                    failure = error
        if failure is not None:
            raise failure

    def verify_build(self) -> None:
        filesystem = self.build_filesystem
        if filesystem is None:
            return
        _verify_anchor(filesystem, _BUILD, "asset build directory")


@dataclass(frozen=True, slots=True)
class AssetPlan:
    """Validated input and rendered products for one asset operation."""

    paths: _AssetPaths
    assets: tuple[_ProjectedAsset, ...]
    previous: tuple[_StateRow, ...] | None
    generated_content: bytes
    state_content: bytes
    lease: _AssetLease


@dataclass(frozen=True, slots=True)
class _StagedAsset:
    relative: PurePosixPath
    staged: StagedFile
    expected: os.stat_result | None


@dataclass
class _MutationJournal:
    completed: list[str]

    def __init__(self) -> None:
        self.completed = []

    def record(self, message: str) -> None:
        self.completed.append(message)

    def failure(self, *, path: str, message: str) -> AssetError:
        if self.completed:
            details = tuple(
                f"completed mutation: {item}" for item in sorted(self.completed)
            )
            return AssetError(
                "PYGANINI022",
                "asset-write",
                path,
                f"{message}; rerun pyganini assets dist followed by "
                "pyganini assets check",
                details=details,
            )
        return AssetError("PYGANINI022", "asset-write", path, message)


def _display(relative: PurePosixPath) -> str:
    return relative.as_posix()


def _asset_relative(relative: PurePosixPath) -> PurePosixPath:
    return relative.relative_to(_ASSETS)


def _open_filesystem(paths: _AssetPaths) -> AnchoredFilesystem:
    project_filesystem: AnchoredFilesystem | None = None
    try:
        project_filesystem = open_anchored_filesystem(paths.root)
        info = project_filesystem.entry_kind(_ASSETS)
        if info is None:
            raise AssetError(
                "PYGANINI020",
                "asset-filesystem",
                _display(_ASSETS),
                "asset directory is missing",
            )
        if _entry_kind(info) is not EntryKind.DIRECTORY:
            raise AssetError(
                "PYGANINI020",
                "asset-filesystem",
                _display(_ASSETS),
                "asset directory must not be a symlink and must be real",
            )
        filesystem = project_filesystem.subdirectory(
            _ASSETS,
            expected=info,
            own_parent=True,
        )
        project_filesystem = None
        return filesystem
    except AssetError:
        raise
    except (FilesystemOperationError, OSError) as error:
        raise AssetError(
            "PYGANINI020",
            "asset-filesystem",
            _display(_ASSETS),
            f"cannot anchor asset directory: {error}",
        ) from error
    finally:
        if project_filesystem is not None:
            with suppress(OSError):
                project_filesystem.close()


def _verify_anchor(
    filesystem: AnchoredFilesystem,
    relative: PurePosixPath,
    description: str,
) -> None:
    try:
        filesystem.verify_root()
    except (FilesystemOperationError, OSError) as error:
        raise AssetError(
            "PYGANINI020",
            "asset-filesystem",
            _display(relative),
            f"{description} changed during operation: {error}",
        ) from error


def _fixed_paths(project: ProjectPaths) -> _AssetPaths:
    assets = project.root / "assets"
    return _AssetPaths(
        root=project.root,
        assets=assets,
        build=assets / "build",
        dist=assets / "dist",
        state_directory=assets / ".pyganini",
        state=assets / ".pyganini" / "assets.json",
        generated=assets / "pyganini_assets_gen.py",
    )


def _entry(
    filesystem: AnchoredFilesystem, relative: PurePosixPath
) -> os.stat_result | None:
    try:
        return filesystem.entry_kind(_asset_relative(relative))
    except FilesystemOperationError as error:
        raise AssetError(
            "PYGANINI020",
            "asset-filesystem",
            _display(relative),
            f"cannot inspect asset path or managed asset parent: {error}",
        ) from error
    except OSError as error:
        raise AssetError(
            "PYGANINI020",
            "asset-filesystem",
            _display(relative),
            f"cannot inspect asset path or managed asset parent: {error}",
        ) from error


def _entry_kind(info: os.stat_result) -> EntryKind:
    if getattr(info, "st_file_attributes", 0) & 0x00000400:
        return EntryKind.SYMLINK
    if stat.S_ISLNK(info.st_mode):
        return EntryKind.SYMLINK
    if stat.S_ISREG(info.st_mode):
        return EntryKind.REGULAR
    if stat.S_ISDIR(info.st_mode):
        return EntryKind.DIRECTORY
    return EntryKind.OTHER


def _require_kind(
    info: os.stat_result | None,
    *,
    relative: PurePosixPath,
    expected: EntryKind,
    missing: str,
    description: str,
) -> os.stat_result:
    if info is None:
        raise AssetError("PYGANINI020", "asset-filesystem", _display(relative), missing)
    kind = _entry_kind(info)
    if kind is not expected:
        raise AssetError(
            "PYGANINI020", "asset-filesystem", _display(relative), description
        )
    return info


def _validate_input_boundaries(filesystem: AnchoredFilesystem) -> os.stat_result:
    _require_kind(
        _entry(filesystem, _ASSETS / _INIT),
        relative=_ASSETS / _INIT,
        expected=EntryKind.REGULAR,
        missing="assets/__init__.py is required for enabled assets",
        description="asset package marker must not be a symlink and must be regular",
    )
    return _require_kind(
        _entry(filesystem, _BUILD),
        relative=_BUILD,
        expected=EntryKind.DIRECTORY,
        missing="assets/build is required for managed assets",
        description="asset build directory must not be a symlink and must be real",
    )


def _validate_managed_boundaries(filesystem: AnchoredFilesystem) -> None:
    for relative, description in (
        (_DIST, "asset dist directory must not be a symlink and must be real"),
        (
            _STATE_DIRECTORY,
            "asset state directory must not be a symlink and must be real",
        ),
    ):
        info = _entry(filesystem, relative)
        if info is not None and _entry_kind(info) is not EntryKind.DIRECTORY:
            raise AssetError(
                "PYGANINI020", "asset-filesystem", _display(relative), description
            )
    for relative in (_GENERATED, _STATE):
        info = _entry(filesystem, relative)
        if info is not None and _entry_kind(info) is not EntryKind.REGULAR:
            raise AssetError(
                "PYGANINI020",
                "asset-filesystem",
                _display(relative),
                "managed asset file must be a regular, non-symlinked file",
            )


def _validate_boundaries(
    filesystem: AnchoredFilesystem, *, include_managed: bool
) -> None:
    _validate_input_boundaries(filesystem)
    if include_managed:
        _validate_managed_boundaries(filesystem)


def _component_issue(part: str) -> str | None:
    if not part:
        return "path components must not be empty"
    if part in {".", ".."}:
        return "path components must not be '.' or '..'"
    if not part.isascii():
        return "path components must contain only ASCII characters"
    if any(ord(character) < 32 or ord(character) == 127 for character in part):
        return "path components must not contain ASCII control characters"
    if part.endswith((" ", ".")):
        return "path components must not end with a space or dot"
    if ":" in part:
        return "path components must not contain a Windows drive separator"
    if any(character in '<>"|?*' for character in part):
        return "path component contains a character forbidden on Windows"
    if part.split(".", 1)[0].casefold() in _WINDOWS_RESERVED:
        return "path component is reserved on Windows"
    return None


def _validate_logical(logical: str, relative: PurePosixPath) -> PurePosixPath:
    windows = PureWindowsPath(logical)
    parts = logical.split("/")
    issue = "path must be a normalized relative POSIX path"
    for part in parts:
        part_issue = _component_issue(part)
        if part_issue is not None:
            issue = part_issue
            break
    if (
        not logical
        or logical.startswith("/")
        or "\\" in logical
        or windows.is_absolute()
        or bool(windows.drive)
        or issue != "path must be a normalized relative POSIX path"
    ):
        raise AssetError("PYGANINI020", "asset-filesystem", _display(relative), issue)
    return PurePosixPath(*parts)


def _read_regular(
    filesystem: AnchoredFilesystem,
    relative: PurePosixPath,
    *,
    expected: os.stat_result | None = None,
    filesystem_relative: PurePosixPath | None = None,
) -> bytes:
    try:
        anchored = (
            _asset_relative(relative)
            if filesystem_relative is None
            else filesystem_relative
        )
        return filesystem.read_regular(anchored, expected=expected)
    except FilesystemOperationError as error:
        raise AssetError(
            "PYGANINI020",
            "asset-filesystem",
            _display(relative),
            f"cannot read asset file: {error}",
        ) from error
    except OSError as error:
        raise AssetError(
            "PYGANINI020",
            "asset-filesystem",
            _display(relative),
            f"cannot read asset file: {error}",
        ) from error


def _fingerprinted_name(name: str, digest: str) -> str:
    suffix = PurePosixPath(name).suffix
    if suffix:
        return f"{name[: -len(suffix)]}.{digest}{suffix}"
    return f"{name}.{digest}"


def _asset_url(dist: PurePosixPath) -> str:
    parts = dist.relative_to(_DIST).parts
    quoted = tuple(quote_segment("asset path segment", part) for part in parts)
    return "/assets/" + "/".join(quoted)


def _scan_build(
    paths: _AssetPaths, filesystem: AnchoredFilesystem
) -> tuple[_ProjectedAsset, ...]:
    found: list[_ProjectedAsset] = []
    try:
        entries = filesystem.entries(skip_transient=False)
    except FilesystemOperationError as error:
        raise AssetError(
            "PYGANINI020",
            "asset-filesystem",
            _display(_BUILD),
            f"cannot scan asset inputs: {error}",
        ) from error
    except OSError as error:
        raise AssetError(
            "PYGANINI020",
            "asset-filesystem",
            _display(_BUILD),
            f"cannot scan asset inputs: {error}",
        ) from error

    for entry in entries:
        relative = entry.relative_path
        logical = relative.as_posix()
        source_relative = _BUILD / relative
        _validate_logical(logical, source_relative)
        if entry.kind is EntryKind.SYMLINK:
            raise AssetError(
                "PYGANINI020",
                "asset-filesystem",
                _display(source_relative),
                "asset inputs must not be symlinks",
            )
        if entry.kind is EntryKind.DIRECTORY:
            continue
        if entry.kind is not EntryKind.REGULAR:
            raise AssetError(
                "PYGANINI020",
                "asset-filesystem",
                _display(source_relative),
                "asset inputs must be regular files or directories",
            )
        content = _read_regular(
            filesystem,
            source_relative,
            expected=entry.info,
            filesystem_relative=relative,
        )
        digest = hashlib.sha256(content).hexdigest()[:8]
        dist = _DIST / relative.parent / _fingerprinted_name(relative.name, digest)
        found.append(
            _ProjectedAsset(
                logical=logical,
                source=paths.root / source_relative,
                dist=dist,
                url=_asset_url(dist),
                hash=digest,
                size=len(content),
                content=content,
            )
        )
    found.sort(key=lambda item: item.logical)
    logical_seen: dict[str, str] = {}
    dist_seen: dict[str, str] = {}
    for asset in found:
        logical_key = asset.logical.casefold()
        previous_logical = logical_seen.get(logical_key)
        if previous_logical is not None:
            raise AssetError(
                "PYGANINI020",
                "asset-filesystem",
                _display(_BUILD / asset.logical),
                f"logical asset name collides with {previous_logical}",
            )
        logical_seen[logical_key] = asset.logical
        dist_key = asset.dist.as_posix().casefold()
        previous_dist = dist_seen.get(dist_key)
        if previous_dist is not None:
            raise AssetError(
                "PYGANINI020",
                "asset-filesystem",
                _display(asset.dist),
                f"dist path collides with {previous_dist}",
            )
        dist_seen[dist_key] = asset.dist.as_posix()
    _verify_anchor(filesystem, _BUILD, "asset build directory")
    return tuple(found)


def _json_object(pairs: list[tuple[str, Any]]) -> dict[str, Any]:
    result: dict[str, Any] = {}
    for key, value in pairs:
        if key in result:
            raise ValueError(f"duplicate JSON key {key!r}")
        result[key] = value
    return result


def _state_dist(raw: str, relative: PurePosixPath) -> PurePosixPath:
    windows = PureWindowsPath(raw)
    path = PurePosixPath(raw)
    if (
        not raw
        or raw != path.as_posix()
        or path.is_absolute()
        or windows.is_absolute()
        or bool(windows.drive)
        or path == _DIST
        or not path.is_relative_to(_DIST)
        or any(_component_issue(part) is not None for part in path.parts)
    ):
        raise AssetError(
            "PYGANINI020",
            "asset-filesystem",
            _display(relative),
            "managed dist path must be normalized and contained by assets/dist",
        )
    return path


def _load_state(
    filesystem: AnchoredFilesystem, *, required: bool
) -> tuple[_StateRow, ...] | None:
    info = _entry(filesystem, _STATE)
    if info is None:
        if required:
            raise AssetError(
                "PYGANINI020",
                "asset-filesystem",
                _display(_STATE),
                "managed asset state is missing; run pyganini assets dist",
            )
        return None
    if _entry_kind(info) is not EntryKind.REGULAR:
        raise AssetError(
            "PYGANINI020",
            "asset-filesystem",
            _display(_STATE),
            "managed asset state must be a regular, non-symlinked file",
        )
    raw = _read_regular(filesystem, _STATE, expected=info)
    try:
        value = json.loads(raw.decode("utf-8"), object_pairs_hook=_json_object)
    except (UnicodeDecodeError, json.JSONDecodeError, ValueError) as error:
        raise AssetError(
            "PYGANINI020",
            "asset-filesystem",
            _display(_STATE),
            f"managed asset state is invalid: {error}",
        ) from error
    if not isinstance(value, dict):
        raise AssetError(
            "PYGANINI020",
            "asset-filesystem",
            _display(_STATE),
            "managed asset state must contain schema then managed",
        )
    state = cast(dict[str, object], value)
    if tuple(state) != ("schema", "managed"):
        raise AssetError(
            "PYGANINI020",
            "asset-filesystem",
            _display(_STATE),
            "managed asset state must contain schema then managed",
        )
    if state.get("schema") != _STATE_SCHEMA:
        raise AssetError(
            "PYGANINI020",
            "asset-filesystem",
            _display(_STATE),
            "managed asset state has an unsupported schema",
        )
    managed_value = state.get("managed")
    managed = managed_value
    if not isinstance(managed, list):
        raise AssetError(
            "PYGANINI020",
            "asset-filesystem",
            _display(_STATE),
            "managed asset state rows must be a list",
        )
    rows: list[_StateRow] = []
    logical_seen: set[str] = set()
    dist_seen: set[str] = set()
    for index, item in enumerate(cast(list[object], managed)):
        row_path = _STATE / f"managed[{index}]"
        if not isinstance(item, dict):
            raise AssetError(
                "PYGANINI020",
                "asset-filesystem",
                _display(row_path),
                "managed asset state row must contain logical, dist, and hash",
            )
        row = cast(dict[str, object], item)
        if tuple(row) != ("logical", "dist", "hash"):
            raise AssetError(
                "PYGANINI020",
                "asset-filesystem",
                _display(row_path),
                "managed asset state row must contain logical, dist, and hash",
            )
        logical = row.get("logical")
        dist = row.get("dist")
        digest = row.get("hash")
        if not isinstance(logical, str) or not isinstance(dist, str):
            raise AssetError(
                "PYGANINI020",
                "asset-filesystem",
                _display(row_path),
                "managed asset state logical and dist values must be strings",
            )
        _validate_logical(logical, row_path)
        parsed_dist = _state_dist(dist, row_path)
        if not isinstance(digest, str) or _HASH.fullmatch(digest) is None:
            raise AssetError(
                "PYGANINI020",
                "asset-filesystem",
                _display(row_path),
                (
                    "managed asset state hash must be eight lowercase "
                    "hexadecimal characters"
                ),
            )
        logical_key = logical.casefold()
        dist_key = parsed_dist.as_posix().casefold()
        if logical_key in logical_seen or dist_key in dist_seen:
            raise AssetError(
                "PYGANINI020",
                "asset-filesystem",
                _display(row_path),
                "managed asset state contains duplicate logical or dist rows",
            )
        logical_seen.add(logical_key)
        dist_seen.add(dist_key)
        rows.append(_StateRow(logical, parsed_dist, digest))
    rows.sort(key=lambda row: row.logical)
    return tuple(rows)


def _render_generated(assets: Sequence[_ProjectedAsset]) -> bytes:
    lines = [
        _GENERATED_COMMENT.rstrip("\n"),
        '"""Generated Pyganini asset interface."""',
        "",
        "from __future__ import annotations",
        "",
        "from dataclasses import dataclass as _dataclass",
        "",
        "from pyganini._url_binding import quote_segment as _quote_segment",
        "",
        '__all__ = ("Asset", "lookup", "manifest", "path")',
        "",
        "",
        "@_dataclass(frozen=True, slots=True)",
        "class Asset:",
        '    """One fingerprinted browser-ready asset."""',
        "",
        "    name: str",
        "    path: str",
        "    hash: str",
        "    size: int",
        "",
        "",
        "_MANIFEST: dict[str, Asset] = {",
    ]
    for asset in assets:
        lines.extend(
            [
                f"    {json.dumps(asset.logical, ensure_ascii=True)}: Asset(",
                f"        name={json.dumps(asset.logical, ensure_ascii=True)},",
                f"        path={json.dumps(asset.url, ensure_ascii=True)},",
                f"        hash={json.dumps(asset.hash, ensure_ascii=True)},",
                f"        size={asset.size},",
                "    ),",
            ]
        )
    lines.extend(
        [
            "}",
            "",
            "",
            "def _normalize_base_path(base_path: object) -> str:",
            "    if not isinstance(base_path, str):",
            '        raise TypeError("base_path must be str")',
            '    if base_path in {"", "/"}:',
            '        return ""',
            '    if all(character == "/" for character in base_path):',
            (
                "        raise ValueError("
                '"base_path must not contain empty path segments")'
            ),
            (
                '    normalized = base_path if base_path.startswith("/") '
                'else "/" + base_path'
            ),
            '    normalized = normalized.rstrip("/")',
            '    segments = normalized[1:].split("/")',
            '    if any(segment == "" for segment in segments):',
            (
                "        raise ValueError("
                '"base_path must not contain empty path segments")'
            ),
            "    quoted = tuple(",
            '        _quote_segment(f"base_path segment {index}", segment)',
            "        for index, segment in enumerate(segments, start=1)",
            "    )",
            '    return "/" + "/".join(quoted)',
            "",
            "",
            "def _validate_name(name: object) -> str:",
            "    if not isinstance(name, str):",
            '        raise TypeError("name must be str")',
            "    return name",
            "",
            "",
            'def path(name: str, *, base_path: str = "") -> str:',
            '    """Return the mounted URL for one logical asset name."""',
            "    logical = _validate_name(name)",
            "    prefix = _normalize_base_path(base_path)",
            "    asset = _MANIFEST.get(logical)",
            "    if asset is None:",
            '        raise KeyError(f"unknown asset: {logical}")',
            "    return prefix + asset.path",
            "",
            "",
            'def lookup(name: str, *, base_path: str = "") -> str | None:',
            '    """Return a mounted asset URL or None for an unknown name."""',
            "    logical = _validate_name(name)",
            "    prefix = _normalize_base_path(base_path)",
            "    asset = _MANIFEST.get(logical)",
            "    if asset is None:",
            "        return None",
            "    return prefix + asset.path",
            "",
            "",
            "def manifest() -> dict[str, Asset]:",
            '    """Return an isolated logical-name asset manifest copy."""',
            "    return dict(_MANIFEST)",
        ]
    )
    return ("\n".join(lines) + "\n").encode("ascii")


def _render_state(assets: Sequence[_ProjectedAsset]) -> bytes:
    payload = {
        "schema": _STATE_SCHEMA,
        "managed": [
            {
                "logical": asset.logical,
                "dist": asset.dist.as_posix(),
                "hash": asset.hash,
            }
            for asset in assets
        ],
    }
    return (
        json.dumps(payload, ensure_ascii=True, indent=2, separators=(",", ": ")) + "\n"
    ).encode("ascii")


def prepare_assets(project: ProjectPaths, operation: Operation) -> AssetPlan:
    """Validate asset boundaries and render a complete in-memory projection."""
    paths = _fixed_paths(project)
    filesystem = _open_filesystem(paths)
    return _prepare_assets(paths, operation, filesystem)


def prepare_enabled_assets(
    project: ProjectPaths, operation: Literal["dist", "check"]
) -> AssetPlan | None:
    """Prepare enabled or inconsistent managed assets through one held root."""
    paths = _fixed_paths(project)
    try:
        filesystem = _open_filesystem(paths)
    except AssetError as error:
        if error.message == "asset directory is missing":
            return None
        raise
    try:
        indicators = any(
            filesystem.entry_kind(relative) is not None
            for relative in (_BUILD_REL, _DIST_REL, _STATE_REL, _GENERATED_REL)
        )
    except BaseException:
        with suppress(OSError):
            filesystem.close()
        raise
    if not indicators:
        filesystem.close()
        return None
    return _prepare_assets(paths, operation, filesystem)


def _prepare_assets(
    paths: _AssetPaths,
    operation: Operation,
    filesystem: AnchoredFilesystem,
) -> AssetPlan:
    build_filesystem: AnchoredFilesystem | None = None
    try:
        _verify_anchor(filesystem, _ASSETS, "asset directory")
        build_info = _validate_input_boundaries(filesystem)
        if operation != "list":
            _validate_managed_boundaries(filesystem)
        try:
            build_filesystem = filesystem.subdirectory(
                _BUILD_REL,
                expected=build_info,
            )
        except (FilesystemOperationError, OSError) as error:
            raise AssetError(
                "PYGANINI020",
                "asset-filesystem",
                _display(_BUILD),
                f"asset build directory changed during operation: {error}",
            ) from error
        assets = _scan_build(paths, build_filesystem)
        previous: tuple[_StateRow, ...] | None
        if operation == "list":
            previous = None
        else:
            previous = _load_state(filesystem, required=operation == "clean")
        plan = AssetPlan(
            paths=paths,
            assets=assets,
            previous=previous,
            generated_content=_render_generated(assets),
            state_content=_render_state(assets),
            lease=_AssetLease(
                None if operation == "list" else filesystem,
                None if operation == "list" else build_filesystem,
            ),
        )
        _verify_anchor(filesystem, _ASSETS, "asset directory")
    except BaseException:
        if build_filesystem is not None:
            with suppress(OSError):
                build_filesystem.close()
        with suppress(OSError):
            filesystem.close()
        raise
    if operation == "list":
        try:
            build_filesystem.close()
            build_filesystem = None
            filesystem.close()
        except OSError as error:
            raise AssetError(
                "PYGANINI020",
                "asset-filesystem",
                _display(_ASSETS),
                f"cannot close anchored asset directory: {error}",
            ) from error
    return plan


def _existing_content(
    filesystem: AnchoredFilesystem, relative: PurePosixPath
) -> tuple[bytes | None, os.stat_result | None]:
    info = _entry(filesystem, relative)
    if info is None:
        return None, None
    if _entry_kind(info) is not EntryKind.REGULAR:
        raise AssetError(
            "PYGANINI020",
            "asset-filesystem",
            _display(relative),
            "managed asset output must be a regular, non-symlinked file",
        )
    return _read_regular(filesystem, relative, expected=info), info


def _expected_files(plan: AssetPlan) -> tuple[tuple[PurePosixPath, bytes], ...]:
    values = [(asset.dist, asset.content) for asset in plan.assets]
    values.append((_GENERATED, plan.generated_content))
    return tuple(sorted(values, key=lambda item: item[0].as_posix()))


def _observe_files(
    filesystem: AnchoredFilesystem,
    expected: Sequence[tuple[PurePosixPath, bytes]],
) -> dict[PurePosixPath, tuple[bytes | None, os.stat_result | None]]:
    return {
        relative: _existing_content(filesystem, relative) for relative, _ in expected
    }


def _verify_unchanged_file(
    filesystem: AnchoredFilesystem,
    relative: PurePosixPath,
    content: bytes,
    info: os.stat_result | None,
) -> None:
    if info is None:
        if _entry(filesystem, relative) is not None:
            raise AssetError(
                "PYGANINI020",
                "asset-filesystem",
                _display(relative),
                "managed asset output changed after ownership validation",
            )
        return
    current = _read_regular(filesystem, relative, expected=info)
    if current != content:
        raise AssetError(
            "PYGANINI020",
            "asset-filesystem",
            _display(relative),
            "managed asset output changed after ownership validation",
        )


def _difference(path: PurePosixPath, message: str) -> AssetDifference:
    return AssetDifference("PYGANINI021", "asset-state", path, message)


def check_assets(project: ProjectPaths) -> tuple[AssetDifference, ...]:
    """Compare managed assets without writing or touching application files."""
    return check_prepared_assets(prepare_assets(project, "check"))


def check_prepared_assets(plan: AssetPlan) -> tuple[AssetDifference, ...]:
    """Compare one held, previously prepared asset projection without writes."""
    filesystem = plan.lease.require()
    try:
        _verify_anchor(filesystem, _ASSETS, "asset directory")
        plan.lease.verify_build()
        _validate_boundaries(filesystem, include_managed=True)
        conflicts = _unowned_current_outputs(plan, filesystem)
        if conflicts:
            return tuple(
                AssetDifference(
                    "PYGANINI020",
                    "asset-filesystem",
                    path,
                    "expected asset output is occupied by an unrecorded file",
                )
                for path in conflicts
            )
        differences: list[AssetDifference] = []
        if _entry(filesystem, _DIST) is None:
            differences.append(
                _difference(
                    _DIST, "asset dist directory is missing; run pyganini assets dist"
                )
            )
        for relative, content in _expected_files(plan):
            current_content, _ = _existing_content(filesystem, relative)
            if current_content is None:
                differences.append(
                    _difference(
                        relative,
                        "expected asset output is missing; run pyganini assets dist",
                    )
                )
            elif current_content != content:
                differences.append(
                    _difference(
                        relative, "asset output is stale; run pyganini assets dist"
                    )
                )
        if plan.previous is None:
            differences.append(
                _difference(
                    _STATE, "managed asset state is missing; run pyganini assets dist"
                )
            )
        else:
            current_state, _ = _existing_content(filesystem, _STATE)
            if current_state != plan.state_content:
                differences.append(
                    _difference(
                        _STATE, "managed asset state is stale; run pyganini assets dist"
                    )
                )
            current_by_logical = {asset.logical: asset for asset in plan.assets}
            expected_dist = {asset.dist for asset in plan.assets}
            for row in plan.previous:
                current = current_by_logical.get(row.logical)
                if (
                    current is None or current.dist != row.dist
                ) and row.dist not in expected_dist:
                    differences.append(
                        _difference(
                            row.dist,
                            "obsolete managed asset remains; run pyganini assets dist",
                        )
                    )
        unique = {(item.path, item.message): item for item in differences}
        return tuple(sorted(unique.values(), key=lambda item: item.path.as_posix()))
    finally:
        plan.lease.close()


def close_asset_plan(plan: AssetPlan | None) -> None:
    """Close a prepared plan that was not consumed by comparison or mutation."""
    if plan is not None:
        plan.lease.close()


def _ensure_directory(
    filesystem: AnchoredFilesystem,
    relative: PurePosixPath,
    journal: _MutationJournal,
) -> None:
    info = _entry(filesystem, relative)
    if info is not None:
        if _entry_kind(info) is not EntryKind.DIRECTORY:
            raise AssetError(
                "PYGANINI020",
                "asset-filesystem",
                _display(relative),
                "managed asset parent must be a real directory",
            )
        return
    try:
        created = filesystem.ensure_parents(
            _asset_relative(relative / ".pyganini-directory")
        )
    except FilesystemOperationError as error:
        for created_relative in error.mutations:
            journal.record(f"created {_display(_ASSETS / created_relative)}")
        raise AssetError(
            "PYGANINI022",
            "asset-write",
            _display(relative),
            f"could not create managed asset directory: {error}",
        ) from error
    except OSError as error:
        raise AssetError(
            "PYGANINI022",
            "asset-write",
            _display(relative),
            f"could not create managed asset directory: {error}",
        ) from error
    for created_relative in created:
        journal.record(f"created {_display(_ASSETS / created_relative)}")


def _stage(
    filesystem: AnchoredFilesystem, relative: PurePosixPath, content: bytes
) -> StagedFile:
    try:
        return filesystem.stage(_asset_relative(relative), content)
    except FilesystemOperationError as error:
        raise AssetError(
            "PYGANINI022",
            "asset-write",
            _display(relative),
            f"could not stage managed asset output: {error}",
        ) from error
    except OSError as error:
        raise AssetError(
            "PYGANINI022",
            "asset-write",
            _display(relative),
            f"could not stage managed asset output: {error}",
        ) from error


def _replace(
    filesystem: AnchoredFilesystem,
    relative: PurePosixPath,
    staged: StagedFile,
    expected: os.stat_result | None,
    journal: _MutationJournal,
) -> None:
    try:
        filesystem.replace_no_clobber(staged, expected=expected)
        journal.record(f"replaced {_display(relative)}")
    except FileExistsError as error:
        raise journal.failure(
            path=_display(relative),
            message=(
                "could not replace managed asset output because destination "
                "ownership changed"
            ),
        ) from error
    except FilesystemOperationError as error:
        for mutation in error.mutations:
            journal.record(f"replaced {_display(_ASSETS / mutation)}")
        raise journal.failure(
            path=_display(relative),
            message=f"could not replace managed asset output: {error}",
        ) from error
    except OSError as error:
        raise journal.failure(
            path=_display(relative),
            message=f"could not replace managed asset output: {error}",
        ) from error


def _discard(
    filesystem: AnchoredFilesystem, staged: Sequence[_StagedAsset]
) -> tuple[str, ...]:
    failures: list[str] = []
    for item in staged:
        try:
            filesystem.discard(item.staged)
        except OSError as error:
            failures.append(
                f"could not remove staging file {_display(item.relative)}: {error}"
            )
    return tuple(failures)


def _stale_rows(plan: AssetPlan) -> tuple[_StateRow, ...]:
    if plan.previous is None:
        return ()
    current = {asset.dist for asset in plan.assets}
    return tuple(row for row in plan.previous if row.dist not in current)


def _validate_stale_targets(
    plan: AssetPlan, filesystem: AnchoredFilesystem
) -> dict[PurePosixPath, os.stat_result | None]:
    targets: dict[PurePosixPath, os.stat_result | None] = {}
    for row in _stale_rows(plan):
        info = _entry(filesystem, row.dist)
        if info is not None and _entry_kind(info) is not EntryKind.REGULAR:
            raise AssetError(
                "PYGANINI020",
                "asset-filesystem",
                _display(row.dist),
                "stale managed asset must remain a regular file before deletion",
            )
        targets[row.dist] = info
    return targets


def _unowned_current_outputs(
    plan: AssetPlan, filesystem: AnchoredFilesystem
) -> tuple[PurePosixPath, ...]:
    owned = {row.dist for row in plan.previous or ()}
    conflicts: list[PurePosixPath] = []
    for asset in plan.assets:
        info = _entry(filesystem, asset.dist)
        if info is not None and asset.dist not in owned:
            if _entry_kind(info) is not EntryKind.REGULAR:
                raise AssetError(
                    "PYGANINI020",
                    "asset-filesystem",
                    _display(asset.dist),
                    "managed asset output must be a regular, non-symlinked file",
                )
            current = _read_regular(filesystem, asset.dist, expected=info)
            if current != asset.content:
                conflicts.append(asset.dist)
    return tuple(sorted(conflicts, key=lambda path: path.as_posix()))


def _remove_stale(
    plan: AssetPlan,
    filesystem: AnchoredFilesystem,
    journal: _MutationJournal,
    targets: dict[PurePosixPath, os.stat_result | None],
) -> tuple[PurePosixPath, ...]:
    removed: list[PurePosixPath] = []
    for row in _stale_rows(plan):
        info = targets[row.dist]
        if info is None:
            continue
        try:
            filesystem.remove(
                FilesystemEntry(_asset_relative(row.dist), EntryKind.REGULAR, info),
                expected=info,
            )
        except OSError as error:
            raise journal.failure(
                path=_display(row.dist),
                message=f"could not remove stale managed asset: {error}",
            ) from error
        journal.record(f"removed {_display(row.dist)}")
        removed.append(row.dist)
        parent = row.dist.parent
        while parent != _DIST and parent != PurePosixPath("."):
            info = _entry(filesystem, parent)
            if info is None or _entry_kind(info) is not EntryKind.DIRECTORY:
                break
            try:
                filesystem.remove(
                    FilesystemEntry(_asset_relative(parent), EntryKind.DIRECTORY, info),
                    expected=info,
                )
            except OSError:
                break
            journal.record(f"removed empty {_display(parent)}")
            parent = parent.parent
    return tuple(removed)


def _verify_write_anchors(
    plan: AssetPlan,
    filesystem: AnchoredFilesystem,
    journal: _MutationJournal,
) -> None:
    try:
        _verify_anchor(filesystem, _ASSETS, "asset directory")
        plan.lease.verify_build()
    except AssetError as error:
        if journal.completed:
            raise journal.failure(path=error.path, message=error.message) from error
        raise


def _write_assets(plan: AssetPlan, *, clean: bool) -> AssetResult:
    if clean and plan.previous is None:
        raise AssetError(
            "PYGANINI020",
            "asset-filesystem",
            _display(_STATE),
            "managed asset state is missing; run pyganini assets dist",
        )
    filesystem = plan.lease.require()
    journal = _MutationJournal()
    written: list[PurePosixPath] = []
    unchanged: list[PurePosixPath] = []
    staged: list[_StagedAsset] = []
    try:
        _verify_write_anchors(plan, filesystem, journal)
        _validate_boundaries(filesystem, include_managed=True)
        stale_targets = _validate_stale_targets(plan, filesystem)
        expected = (
            [(_STATE, plan.state_content)]
            if clean
            else [*_expected_files(plan), (_STATE, plan.state_content)]
        )
        observed = _observe_files(filesystem, expected)
        if not clean:
            conflicts = _unowned_current_outputs(plan, filesystem)
            if conflicts:
                raise AssetError(
                    "PYGANINI020",
                    "asset-filesystem",
                    _display(conflicts[0]),
                    "expected asset output is occupied by an unrecorded file",
                    details=tuple(
                        f"unrecorded output: {_display(path)}" for path in conflicts[1:]
                    ),
                )
        if clean:
            current_state, state_info = observed[_STATE]
            if current_state == plan.state_content:
                _verify_unchanged_file(
                    filesystem,
                    _STATE,
                    plan.state_content,
                    state_info,
                )
                unchanged.append(_STATE)
            else:
                staged.append(
                    _StagedAsset(
                        _STATE,
                        _stage(filesystem, _STATE, plan.state_content),
                        state_info,
                    )
                )
        else:
            _ensure_directory(filesystem, _DIST, journal)
            _ensure_directory(filesystem, _STATE_DIRECTORY, journal)
            for relative, content in expected:
                if relative != _GENERATED and relative != _STATE:
                    _ensure_directory(filesystem, relative.parent, journal)
                current, info = observed[relative]
                if current == content:
                    _verify_unchanged_file(filesystem, relative, content, info)
                    unchanged.append(relative)
                else:
                    staged.append(
                        _StagedAsset(
                            relative,
                            _stage(filesystem, relative, content),
                            info,
                        )
                    )

        if not clean:
            current_outputs = [item for item in staged if item.relative != _STATE]
            state_outputs = [item for item in staged if item.relative == _STATE]
            for item in current_outputs:
                _replace(filesystem, item.relative, item.staged, item.expected, journal)
                written.append(item.relative)
            removed = _remove_stale(plan, filesystem, journal, stale_targets)
            for relative, content in _expected_files(plan):
                current, _ = _existing_content(filesystem, relative)
                if current != content:
                    raise journal.failure(
                        path=_display(relative),
                        message=(
                            "managed asset output changed before state replacement"
                        ),
                    )
            _verify_write_anchors(plan, filesystem, journal)
            for item in state_outputs:
                _replace(filesystem, item.relative, item.staged, item.expected, journal)
                written.append(item.relative)
        else:
            removed = _remove_stale(plan, filesystem, journal, stale_targets)
            _verify_write_anchors(plan, filesystem, journal)
            for item in staged:
                _replace(filesystem, item.relative, item.staged, item.expected, journal)
                written.append(item.relative)
    except AssetError as error:
        cleanup = _discard(filesystem, staged)
        try:
            plan.lease.close()
        except OSError as close_error:
            cleanup = (*cleanup, f"could not close asset directory: {close_error}")
        if cleanup:
            raise AssetError(
                error.code,
                error.phase,
                error.path,
                error.message,
                details=(*error.details, *cleanup),
            ) from error
        raise
    except Exception as error:
        cleanup = _discard(filesystem, staged)
        try:
            plan.lease.close()
        except OSError as close_error:
            cleanup = (*cleanup, f"could not close asset directory: {close_error}")
        failure = journal.failure(
            path=_display(_ASSETS),
            message=f"unexpected asset write failure: {error}",
        )
        if cleanup:
            failure = AssetError(
                failure.code,
                failure.phase,
                failure.path,
                failure.message,
                details=(*failure.details, *cleanup),
            )
        raise failure from error
    try:
        plan.lease.close()
    except OSError as error:
        raise AssetError(
            "PYGANINI022",
            "asset-write",
            _display(_ASSETS),
            f"could not close anchored asset directory: {error}",
            details=tuple(journal.completed),
        ) from error
    return AssetResult(tuple(written), tuple(unchanged), removed)


def write_assets(plan: AssetPlan) -> AssetResult:
    """Write the complete current projection and clean stale owned files."""
    return _write_assets(plan, clean=False)


def clean_assets(plan: AssetPlan) -> AssetResult:
    """Remove stale state-owned files and update state without rebuilding output."""
    return _write_assets(plan, clean=True)


def render_asset_list(plan: AssetPlan, *, json_output: bool) -> str:
    """Render a complete deterministic in-memory asset listing."""
    if json_output:
        payload = {
            "schema": _LIST_SCHEMA,
            "assets": [
                {
                    "name": asset.logical,
                    "path": asset.url,
                    "source": (_BUILD / asset.logical).as_posix(),
                    "dist": asset.dist.as_posix(),
                    "hash": asset.hash,
                    "size": asset.size,
                }
                for asset in plan.assets
            ],
        }
        return json.dumps(payload, ensure_ascii=True, indent=2) + "\n"
    headers = ("Logical asset", "URL path", "Size")
    rows = [(asset.logical, asset.url, str(asset.size)) for asset in plan.assets]
    widths = tuple(
        max([len(headers[index]), *(len(row[index]) for row in rows)], default=0)
        for index in range(3)
    )
    lines = [
        f"{headers[0]:<{widths[0]}}  {headers[1]:<{widths[1]}}  {headers[2]}",
        *(f"{row[0]:<{widths[0]}}  {row[1]:<{widths[1]}}  {row[2]}" for row in rows),
    ]
    return "\n".join(lines) + "\n"
