"""Validate, compare, and atomically replace generated application files."""

from __future__ import annotations

import os
from collections.abc import Sequence
from dataclasses import dataclass, field
from pathlib import PurePosixPath, PureWindowsPath
from typing import cast

from pyganini._filesystem import (
    EntryKind,
    FilesystemEntry,
    FilesystemOperationError,
    GeneratedFilesystem,
    StagedFile,
    open_generated_filesystem,
)
from pyganini._paths import ProjectPaths

_GENERATED_ROOT = PurePosixPath("app/_pyganini")
_MARKER = PurePosixPath("app/_pyganini/.pyganini-root")
_MARKER_INSIDE = PurePosixPath(".pyganini-root")
_MARKER_CONTENT = b"pyganini-generated-directory-v1\n"
_GENERATED_COMMENT = b"# Code generated by pyganini; DO NOT EDIT.\n"
_BOOTSTRAP = _GENERATED_COMMENT + b'"""Generated Pyganini application package."""\n'
_WINDOWS_RESERVED = {
    "aux",
    "clock$",
    "con",
    "nul",
    "prn",
    *(f"com{number}" for number in range(1, 10)),
    *(f"lpt{number}" for number in range(1, 10)),
}


class GenerationError(RuntimeError):
    """A localized generation, ownership, or partial-mutation failure."""

    def __init__(
        self,
        code: str,
        phase: str,
        path: str,
        message: str,
        *,
        details: Sequence[str] = (),
    ) -> None:
        super().__init__(message)
        self.code = code
        self.phase = phase
        self.path = path
        self.message = message
        self.details = tuple(details)


@dataclass(frozen=True)
class GeneratedArtifact:
    relative_path: PurePosixPath
    content: bytes


@dataclass(frozen=True)
class GenerationResult:
    written: tuple[PurePosixPath, ...]
    unchanged: tuple[PurePosixPath, ...]
    removed: tuple[PurePosixPath, ...]


@dataclass(frozen=True)
class Difference:
    code: str
    phase: str
    path: PurePosixPath
    message: str


@dataclass
class _MutationJournal:
    completed: list[str] = field(default_factory=lambda: list[str]())

    def record(self, message: str) -> None:
        self.completed.append(message)

    def failure(
        self,
        *,
        path: str,
        message: str,
        details: Sequence[str] = (),
    ) -> GenerationError:
        if self.completed:
            mutations = tuple(
                f"completed mutation: {item}" for item in sorted(self.completed)
            )
            return GenerationError(
                "PYGANINI008",
                "partial-generation",
                path,
                f"{message}; rerun pyganini generate followed by pyganini check",
                details=(*mutations, *sorted(details)),
            )
        return GenerationError(
            "PYGANINI007", "generation-plan", path, message, details=sorted(details)
        )


def bootstrap_plan() -> tuple[GeneratedArtifact, ...]:
    """Return the route-neutral generated package plan."""
    return (
        GeneratedArtifact(
            relative_path=PurePosixPath("app/_pyganini/__init__.py"),
            content=_BOOTSTRAP,
        ),
    )


def _case_insensitive(paths: ProjectPaths) -> bool:
    alternate = paths.root / "APP"
    try:
        return alternate.exists() and os.path.samefile(paths.app, alternate)
    except OSError:
        return False


def _plan_error(issues: Sequence[tuple[str, str]]) -> GenerationError:
    ordered = sorted(set(issues), key=lambda item: (item[0], item[1]))
    first_path, first_message = ordered[0]
    details = tuple(f"{path}: {message}" for path, message in ordered[1:])
    return GenerationError(
        "PYGANINI007",
        "generation-plan",
        first_path,
        first_message,
        details=details,
    )


def _portable_component_issue(part: str) -> str | None:
    if "\\" in part:
        return "path components must not contain backslashes"
    if not part.isascii():
        return "path components must contain only ASCII characters"
    if any(ord(character) < 32 for character in part):
        return "path components must not contain control characters"
    if part.endswith((" ", ".")):
        return "path components must not end with a space or dot"
    if ":" in part:
        return "path components must not contain a Windows drive separator"
    if any(character in '<>"|?*' for character in part):
        return "path component contains a character forbidden on Windows"
    device = part.split(".", 1)[0].casefold()
    if device in _WINDOWS_RESERVED:
        return "path component is reserved on Windows"
    return None


def _validate_plan(
    paths: ProjectPaths, plan: Sequence[GeneratedArtifact]
) -> tuple[GeneratedArtifact, ...]:
    issues: list[tuple[str, str]] = []
    validated: list[GeneratedArtifact] = []
    insensitive = _case_insensitive(paths)

    for artifact in plan:
        relative = artifact.relative_path
        display = relative.as_posix()
        parts = relative.parts
        windows = PureWindowsPath(display)
        if (
            relative.is_absolute()
            or windows.is_absolute()
            or bool(windows.drive)
            or not parts
            or display in {"", "."}
            or any(part in {"", ".", ".."} for part in parts)
        ):
            issues.append(
                (display or "pyganini", "path must be normalized and relative")
            )
            continue
        for part in parts:
            issue = _portable_component_issue(part)
            if issue is not None:
                issues.append((display, issue))
        if not relative.is_relative_to(_GENERATED_ROOT) or relative == _GENERATED_ROOT:
            issues.append((display, "destination must be below app/_pyganini"))
        if relative == _MARKER:
            issues.append((display, "destination is reserved for the ownership marker"))
        if not isinstance(cast(object, artifact.content), bytes):
            issues.append((display, "content must be bytes"))
        elif relative.suffix == ".py" and not artifact.content.startswith(
            _GENERATED_COMMENT
        ):
            issues.append(
                (display, "generated Python must start with the Pyganini marker")
            )
        validated.append(artifact)

    ordered = sorted(validated, key=lambda item: item.relative_path.as_posix())
    for index, artifact in enumerate(ordered):
        left = artifact.relative_path
        left_parts = tuple(
            part.casefold() if insensitive else part for part in left.parts
        )
        for other in ordered[index + 1 :]:
            right = other.relative_path
            right_parts = tuple(
                part.casefold() if insensitive else part for part in right.parts
            )
            if left_parts == right_parts:
                issues.append(
                    (right.as_posix(), f"path collides with {left.as_posix()}")
                )
            elif right_parts[: len(left_parts)] == left_parts:
                issues.append(
                    (
                        right.as_posix(),
                        f"parent conflicts with file {left.as_posix()}",
                    )
                )
            elif left_parts[: len(right_parts)] == right_parts:
                issues.append(
                    (
                        left.as_posix(),
                        f"parent conflicts with file {right.as_posix()}",
                    )
                )

    if issues:
        raise _plan_error(issues)
    return tuple(ordered)


def _inside(relative: PurePosixPath) -> PurePosixPath:
    return relative.relative_to(_GENERATED_ROOT)


def _outside(relative: PurePosixPath) -> PurePosixPath:
    return _GENERATED_ROOT / relative


def _ownership_error(path: PurePosixPath, message: str) -> GenerationError:
    return GenerationError(
        "PYGANINI006", "generated-ownership", path.as_posix(), message
    )


def _entries(filesystem: GeneratedFilesystem) -> dict[PurePosixPath, FilesystemEntry]:
    try:
        return {entry.relative_path: entry for entry in filesystem.entries()}
    except OSError as error:
        raise _ownership_error(
            _GENERATED_ROOT, f"cannot inspect generated content: {error}"
        ) from error


def _marker_status(
    filesystem: GeneratedFilesystem,
    entries: dict[PurePosixPath, FilesystemEntry],
) -> str:
    marker = entries.get(_MARKER_INSIDE)
    if marker is None:
        return "missing"
    if marker.kind is not EntryKind.REGULAR:
        return "corrupt"
    try:
        return (
            "valid"
            if filesystem.read_regular(_MARKER_INSIDE) == _MARKER_CONTENT
            else "corrupt"
        )
    except OSError as error:
        raise _ownership_error(
            _MARKER, f"cannot read ownership marker: {error}"
        ) from error


def _ownership(
    filesystem: GeneratedFilesystem,
) -> tuple[str, dict[PurePosixPath, FilesystemEntry]]:
    try:
        root_kind = filesystem.root_kind()
    except OSError as error:
        raise _ownership_error(
            _GENERATED_ROOT, f"cannot inspect generated directory: {error}"
        ) from error
    if root_kind is None:
        return "absent", {}
    if root_kind is not EntryKind.DIRECTORY:
        raise _ownership_error(
            _GENERATED_ROOT, "generated path must be an owned directory"
        )
    entries = _entries(filesystem)
    marker = _marker_status(filesystem, entries)
    if marker == "valid":
        return "marked", entries
    if marker == "missing" and not entries:
        return "empty", entries
    message = (
        "generated directory is non-empty without the ownership marker"
        if marker == "missing"
        else "ownership marker has unexpected content or type"
    )
    raise _ownership_error(_MARKER, message)


def _expected_map(
    plan: Sequence[GeneratedArtifact], *, include_marker: bool
) -> dict[PurePosixPath, bytes]:
    expected = {_inside(artifact.relative_path): artifact.content for artifact in plan}
    if include_marker:
        expected[_MARKER_INSIDE] = _MARKER_CONTENT
    return expected


def _expected_parents(
    expected: Sequence[PurePosixPath] | set[PurePosixPath],
) -> set[PurePosixPath]:
    return {
        parent
        for relative in expected
        for parent in relative.parents
        if parent != PurePosixPath(".")
    }


def _differences(
    filesystem: GeneratedFilesystem,
    entries: dict[PurePosixPath, FilesystemEntry],
    expected: dict[PurePosixPath, bytes],
) -> tuple[Difference, ...]:
    differences: list[Difference] = []
    expected_parents = _expected_parents(set(expected))
    for relative, content in sorted(expected.items(), key=lambda item: str(item[0])):
        display = _outside(relative)
        entry = entries.get(relative)
        if entry is None:
            differences.append(
                Difference(
                    "PYGANINI005",
                    "generated-state",
                    display,
                    "expected generated file is missing; run pyganini generate",
                )
            )
        elif entry.kind is not EntryKind.REGULAR:
            differences.append(
                Difference(
                    "PYGANINI006",
                    "generated-ownership",
                    display,
                    "expected generated file has a conflicting type",
                )
            )
        else:
            try:
                current = filesystem.read_regular(relative)
            except OSError as error:
                differences.append(
                    Difference(
                        "PYGANINI006",
                        "generated-ownership",
                        display,
                        f"cannot read generated file: {error}",
                    )
                )
            else:
                if current != content:
                    differences.append(
                        Difference(
                            "PYGANINI005",
                            "generated-state",
                            display,
                            "generated file is stale; run pyganini generate",
                        )
                    )

    for relative in sorted(entries, key=str):
        if relative not in expected and relative not in expected_parents:
            differences.append(
                Difference(
                    "PYGANINI005",
                    "generated-state",
                    _outside(relative),
                    "obsolete generated entry exists; run pyganini generate",
                )
            )
    return tuple(sorted(differences, key=lambda item: item.path.as_posix()))


def check_generated_state(
    paths: ProjectPaths, plan: Sequence[GeneratedArtifact]
) -> tuple[Difference, ...]:
    """Compare expected generated state without mutating the application."""
    ordered = _validate_plan(paths, plan)
    try:
        filesystem = open_generated_filesystem(paths)
    except OSError as error:
        return (
            Difference(
                "PYGANINI006",
                "generated-ownership",
                _GENERATED_ROOT,
                f"cannot anchor generated directory: {error}",
            ),
        )
    try:
        try:
            state, entries = _ownership(filesystem)
        except GenerationError as error:
            return (
                Difference(
                    error.code,
                    error.phase,
                    PurePosixPath(error.path),
                    error.message,
                ),
            )
        if state == "absent":
            return (
                Difference(
                    "PYGANINI005",
                    "generated-state",
                    _GENERATED_ROOT,
                    "generated directory is missing; run pyganini generate",
                ),
            )
        expected = _expected_map(ordered, include_marker=True)
        if state == "empty":
            return tuple(
                Difference(
                    "PYGANINI005",
                    "generated-state",
                    _outside(relative),
                    "expected generated file is missing; run pyganini generate",
                )
                for relative in sorted(expected, key=str)
            )
        return _differences(filesystem, entries, expected)
    finally:
        filesystem.close()


def _cleanup_staging(
    filesystem: GeneratedFilesystem, staged: Sequence[StagedFile]
) -> tuple[str, ...]:
    failures: list[str] = []
    for item in staged:
        try:
            filesystem.discard(item)
        except Exception as error:
            failures.append(
                f"could not remove staging file {item.temporary_name}: {error}"
            )
    return tuple(sorted(failures))


def _stage(
    filesystem: GeneratedFilesystem, relative: PurePosixPath, content: bytes
) -> StagedFile:
    return filesystem.stage(relative, content)


def _record_filesystem_mutations(
    journal: _MutationJournal, error: FilesystemOperationError
) -> None:
    for relative in error.mutations:
        journal.record(f"created {_outside(relative).as_posix()}")


def _normalize_generation_failure(
    journal: _MutationJournal, error: Exception
) -> GenerationError:
    if isinstance(error, GenerationError):
        if journal.completed and error.code != "PYGANINI008":
            return journal.failure(
                path=error.path,
                message=error.message,
                details=error.details,
            )
        return error
    if isinstance(error, FilesystemOperationError):
        _record_filesystem_mutations(journal, error)
        path = _outside(error.relative_path).as_posix()
        return journal.failure(
            path=path,
            message=f"filesystem operation failed: {error}",
        )
    if isinstance(error, OSError):
        return journal.failure(
            path=_GENERATED_ROOT.as_posix(),
            message=f"filesystem operation failed: {error}",
        )
    return journal.failure(
        path=_GENERATED_ROOT.as_posix(),
        message=f"unexpected internal failure: {error}",
    )


def _append_generation_detail(error: GenerationError, detail: str) -> GenerationError:
    return GenerationError(
        error.code,
        error.phase,
        error.path,
        error.message,
        details=(*error.details, detail),
    )


def _preflight_entry_conflicts(
    entries: dict[PurePosixPath, FilesystemEntry],
    expected: dict[PurePosixPath, bytes],
) -> None:
    for relative in sorted(expected, key=str):
        entry = entries.get(relative)
        if entry is not None and entry.kind is not EntryKind.REGULAR:
            raise _ownership_error(
                _outside(relative), "expected generated file has a conflicting type"
            )
        for parent in relative.parents:
            if parent == PurePosixPath("."):
                break
            parent_entry = entries.get(parent)
            if (
                parent_entry is not None
                and parent_entry.kind is not EntryKind.DIRECTORY
            ):
                raise _ownership_error(
                    _outside(parent), "expected generated parent has a conflicting type"
                )


def generate(
    paths: ProjectPaths, plan: Sequence[GeneratedArtifact]
) -> GenerationResult:
    """Write the validated plan and remove obsolete owned output."""
    ordered = _validate_plan(paths, plan)
    journal = _MutationJournal()
    try:
        filesystem = open_generated_filesystem(paths)
    except OSError as error:
        raise _ownership_error(
            _GENERATED_ROOT, f"cannot anchor generated directory: {error}"
        ) from error
    result: GenerationResult | None = None
    failure: GenerationError | None = None
    try:
        try:
            state, entries = _ownership(filesystem)
            written: list[PurePosixPath] = []
            unchanged: list[PurePosixPath] = []

            if state == "absent":
                filesystem.create_root()
                journal.record(f"created {_GENERATED_ROOT.as_posix()}")
                created_entries = _entries(filesystem)
                if created_entries:
                    raise journal.failure(
                        path=_GENERATED_ROOT.as_posix(),
                        message="new generated directory is no longer empty",
                    )

            expected = _expected_map(ordered, include_marker=True)
            _preflight_entry_conflicts(entries, expected)
            changed: list[tuple[PurePosixPath, bytes]] = []
            for relative, content in sorted(
                expected.items(), key=lambda item: str(item[0])
            ):
                entry = entries.get(relative)
                if entry is not None:
                    try:
                        if filesystem.read_regular(relative) == content:
                            unchanged.append(_outside(relative))
                            continue
                    except OSError as error:
                        raise journal.failure(
                            path=_outside(relative).as_posix(),
                            message=f"could not read generated file: {error}",
                        ) from error
                changed.append((relative, content))

            for relative, _ in changed:
                created = filesystem.ensure_parents(relative)
                for parent in created:
                    journal.record(f"created {_outside(parent).as_posix()}")

            staged: list[tuple[PurePosixPath, StagedFile]] = []
            try:
                for relative, content in changed:
                    staged.append((relative, _stage(filesystem, relative, content)))
            except Exception as error:
                cleanup = _cleanup_staging(
                    filesystem, tuple(item[1] for item in staged)
                )
                staged_failure = _normalize_generation_failure(journal, error)
                if cleanup:
                    staged_failure = _append_generation_detail(
                        staged_failure, "; ".join(cleanup)
                    )
                raise staged_failure from error

            for index, (relative, staged_file) in enumerate(staged):
                try:
                    filesystem.replace(staged_file)
                except Exception as error:
                    cleanup = _cleanup_staging(
                        filesystem, tuple(item[1] for item in staged[index:])
                    )
                    replacement_failure = _normalize_generation_failure(journal, error)
                    if cleanup:
                        replacement_failure = _append_generation_detail(
                            replacement_failure, "; ".join(cleanup)
                        )
                    raise replacement_failure from error
                written.append(_outside(relative))
                journal.record(f"replaced {_outside(relative).as_posix()}")

            all_expected = set(expected)
            expected_parents = _expected_parents(all_expected)
            current_entries = _entries(filesystem)
            if _marker_status(filesystem, current_entries) != "valid":
                raise journal.failure(
                    path=_GENERATED_ROOT.as_posix(),
                    message="could not verify generated state after writing",
                )

            obsolete = [
                entry
                for relative, entry in current_entries.items()
                if relative not in all_expected and relative not in expected_parents
            ]
            obsolete.sort(
                key=lambda entry: (
                    -len(entry.relative_path.parts),
                    entry.relative_path.as_posix(),
                )
            )
            removed: list[PurePosixPath] = []
            for entry in obsolete:
                try:
                    filesystem.remove(entry)
                except Exception as error:
                    raise journal.failure(
                        path=_outside(entry.relative_path).as_posix(),
                        message=(f"could not remove obsolete generated entry: {error}"),
                    ) from error
                removed.append(_outside(entry.relative_path))
                journal.record(f"removed {_outside(entry.relative_path).as_posix()}")

            result = GenerationResult(
                written=tuple(sorted(written, key=str)),
                unchanged=tuple(sorted(unchanged, key=str)),
                removed=tuple(sorted(removed, key=str)),
            )
        except Exception as error:
            failure = _normalize_generation_failure(journal, error)
    finally:
        try:
            filesystem.close()
        except Exception as error:
            close_detail = f"could not close generated filesystem: {error}"
            if failure is None:
                failure = journal.failure(
                    path=_GENERATED_ROOT.as_posix(),
                    message=close_detail,
                    details=(close_detail,),
                )
            else:
                failure = _append_generation_detail(failure, close_detail)

    if failure is not None:
        raise failure
    assert result is not None
    return result
