# Code generated by the foundation probe; DO NOT EDIT.
from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class UserNode:
    user_id: int

    @property
    def path(self) -> str:
        return f"/users/{self.user_id}"

    @property
    def edit(self) -> str:
        return f"{self.path}/edit"


class URLs:
    @property
    def home(self) -> str:
        return "/"

    def user(self, user_id: int) -> UserNode:
        return UserNode(user_id)


urls = URLs()
